// =============================================================================
// g2_dw_weight_rom.v -- Group 2 Depthwise Weight ROM (Step 6, Path A)
// -----------------------------------------------------------------------------
// Stores BN-folded, quantized DW conv weights for all 16 Shuffle block loops.
// One entry per loop: 58 filters x 9 taps x 15 bits = 7830 bits packed.
// Bit layout: weight[f][t] at bits (f*9+t)*15 +: 15 (f=0..57, t=0..8)
// Tap order: t=0..8 = [r0c0, r0c1, r0c2, r1c0, r1c1, r1c2, r2c0, r2c1, r2c2]
// ROM style: distributed (LUT-based), 16 entries x 7832-bit wide.
// Read: combinational (zero-latency). Addr changes once per loop transition.
// INIT_FILE path is relative to the project root (N:\GP\shufflenet_rtl\).
// Generated by: scripts/group2/extract_weights_g2_g3.py
// =============================================================================

`timescale 1ns / 1ps
`default_nettype none
`include "shufflenet_pkg.vh"

module g2_dw_weight_rom #(
 parameter INIT_FILE = "rtl/group2/weights/g2_dw_weights.hex"
) (
 // address = loop_id (0..15)
 input wire [3:0] addr,
 // data = all 58 DW filter weights packed (7830 bits)
 // weight[f][t] at bits (f*9+t)*15 +: 15
 output wire [7829:0] data_out
);

 localparam integer DEPTH = 16;
 localparam integer DW = 7830; // 58 * 9 * G2_DW_WW = 58*9*15

 (* rom_style = "distributed" *) reg [DW-1:0] rom [0:DEPTH-1];

 integer i;
 initial begin
 for (i = 0; i < DEPTH; i = i + 1)
 rom[i] = {DW{1'b0}};
 $readmemh(INIT_FILE, rom);
 end

 assign data_out = rom[addr];

endmodule

`default_nettype wire
// =============================================================================
// END g2_dw_weight_rom.v
// =============================================================================
