# =============================================================================
# shufflenet.xdc -- Constraints for ShuffleNet V2 accelerator on iWave ZU19EG
# -----------------------------------------------------------------------------
# Target : XCZU19EG-FFVC1760-2-I (iWave ZU19EG Development Kit)
# Top : shufflenet_board_top (instantiated as module reference in BD)
# Clock : s_axi_aclk -- 100 MHz from PS pl_clk0 (generated by Zynq MPSoC PS)
# MMCM : MMCME4_BASE re-generates 100 MHz for PL logic; Vivado auto-derives
# the CLKOUT0 generated clock from MMCM parameters.
# =============================================================================

# -----------------------------------------------------------------------------
# 1. Primary input clock (PS pl_clk0 via AXI interconnect to s_axi_aclk)
# Period = 10.000 ns = 100 MHz.
# When the PS IP is configured for 100 MHz pl_clk0, Vivado's BD automation
# generates this constraint automatically. Listed here as a fallback for
# standalone synthesis runs outside the block design flow.
# -----------------------------------------------------------------------------
create_clock -name s_axi_aclk -period 10.000 \
 [get_ports -quiet s_axi_aclk]

# -----------------------------------------------------------------------------
# 2. MMCM output clock (auto-derived by Vivado from MMCME4_BASE parameters)
# Vivado creates a generated clock on u_mmcm/CLKOUT0 automatically.
# The constraint below names it explicitly so timing reports are readable.
# -----------------------------------------------------------------------------
create_generated_clock -name clk_100m \
 -source [get_pins -hierarchical -filter {NAME =~ */u_mmcm/CLKIN1}] \
 -master_clock s_axi_aclk \
 -multiply_by 10 -divide_by 10 \
 [get_pins -hierarchical -filter {NAME =~ */u_mmcm/CLKOUT0}]

# -----------------------------------------------------------------------------
# 3. Asynchronous reset false path
# s_axi_aresetn is an asynchronous PS output; the reset synchronizer inside
# shufflenet_board_top handles the CDC. Mark the port as a false path so
# Vivado does not attempt to time it.
# -----------------------------------------------------------------------------
set_false_path -from [get_ports -quiet s_axi_aresetn]

# -----------------------------------------------------------------------------
# 4. Clock domain relationship
# s_axi_aclk and clk_100m are both 100 MHz. The MMCM adds a small but
# bounded phase offset. Declare them as asynchronous so Vivado does not
# set up impossible cross-clock paths between the PS AXI interconnect
# (on s_axi_aclk) and the PL logic (on clk_100m).
# All AXI handshake signals are registered in the same MMCM output domain
# inside shufflenet_board_top, so there is no real CDC to worry about.
# -----------------------------------------------------------------------------
set_clock_groups -asynchronous \
 -group [get_clocks s_axi_aclk] \
 -group [get_clocks clk_100m]

# -----------------------------------------------------------------------------
# 5. I/O constraints
# busy_led and done_led connect to on-board LEDs.
# Uncomment and fill in the correct package pin and voltage for the
# iWave ZU19EG board after consulting the board schematic / UCF.
# Example (fill in actual pin from board schematic):
# set_property PACKAGE_PIN <PIN> [get_ports busy_led]
# set_property IOSTANDARD LVCMOS18 [get_ports busy_led]
# set_property PACKAGE_PIN <PIN> [get_ports done_led]
# set_property IOSTANDARD LVCMOS18 [get_ports done_led]
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# 6. Synthesis / implementation hints
# Keep DSP48E2 columns close for the accumulator chains.
# Relax non-critical paths on weight ROMs.
# -----------------------------------------------------------------------------
set_multicycle_path -setup 2 \
 -from [get_cells -hierarchical -filter {NAME =~ *g2_pw_weight_rom*}]
set_multicycle_path -hold 1 \
 -from [get_cells -hierarchical -filter {NAME =~ *g2_pw_weight_rom*}]
