// =============================================================================
// tb_Adder3.v - Self-checking testbench for the 3-input CSA adder
// -----------------------------------------------------------------------------
// Methodology: Thesis Sec 5.8.1 "Testing Strategy"
//   "we use the python model to generate files containing the input ... and
//    generation files containing the correct outputs to compare it with the
//    outputs of the RTL model. Then we create a self-checking testbench to
//    read the input files and pass them to the design then write the output
//    of the RTL to files and compare them with the files generated from the
//    python model."
//
// This TB:
//   1) Reads vectors from tb/common/vectors/adder3_vectors.hex (generated by
//      scripts/gen_foundation_vectors.py).
//   2) Drives the Adder3 DUT combinationally (no clock needed since DUT is
//      purely combinational; we still use a small delay to let signals settle).
//   3) Compares DUT output against expected; counts pass/fail; prints summary.
//
// Run (with Vivado XSim):
//   vivado -mode batch -source vivado/scripts/sim_tb_Adder3.tcl
//
// Run (with Icarus Verilog, alternative):
//   iverilog -g2012 -I rtl/common -o build/tb_Adder3 \
//            tb/common/tb_Adder3.v rtl/common/Adder3.v
//   vvp build/tb_Adder3
// =============================================================================

`timescale 1ns / 1ps
`default_nettype none

module tb_Adder3;

    // -------------------------------------------------------------------------
    // Parameters MUST match the Python generator's defaults:
    //   in_width = 23 (matches MUL_OUT_W),   out_width = 25
    // -------------------------------------------------------------------------
    localparam integer IN_W   = 23;
    localparam integer OUT_W  = IN_W + 2;

    localparam integer MAX_VECTORS = 1024;       // upper bound on TB rows

    // -------------------------------------------------------------------------
    // Vector storage
    // -------------------------------------------------------------------------
    reg signed [IN_W-1:0]   v_a   [0:MAX_VECTORS-1];
    reg signed [IN_W-1:0]   v_b   [0:MAX_VECTORS-1];
    reg signed [IN_W-1:0]   v_c   [0:MAX_VECTORS-1];
    reg signed [OUT_W-1:0]  v_exp [0:MAX_VECTORS-1];

    // -------------------------------------------------------------------------
    // DUT signals
    // -------------------------------------------------------------------------
    reg  signed [IN_W-1:0]  a_i, b_i, c_i;
    wire signed [OUT_W-1:0] sum_o;

    Adder3 #(.IN_W(IN_W), .OUT_W(OUT_W)) dut (
        .a       (a_i),
        .b       (b_i),
        .c       (c_i),
        .sum_out (sum_o)
    );

    // -------------------------------------------------------------------------
    // Vector loading
    // -------------------------------------------------------------------------
    // The hex file has one line per vector with 4 fields: a b c expected.
    // We parse it manually with $fscanf so we can support 4 fields per line.
    // -------------------------------------------------------------------------
    integer fd;
    integer scan_status;
    integer n_vectors;
    integer i;
    integer pass_count, fail_count;
    integer dump_first_failures;

    // Temp registers for one parsed line (sized to fit any field as hex).
    reg [IN_W-1:0]  tmp_a, tmp_b, tmp_c;
    reg [OUT_W-1:0] tmp_exp;

    initial begin
        n_vectors           = 0;
        pass_count          = 0;
        fail_count          = 0;
        dump_first_failures = 0;

        $display("=========================================================");
        $display("Adder3 Self-Checking Testbench (Thesis Sec 5.3.2.1)");
        $display("=========================================================");

        // Vector file path: allow override via +VECTORS=<path> plusarg, so
        // Vivado XSim Tcl runners can pass an absolute path. Otherwise fall
        // back to a couple of likely relative locations.
        begin : open_file
            // 512 chars = 4096 bits, enough for any realistic Windows/Linux path
            reg [8*512-1:0] path_arg;
            integer have_arg;
            have_arg = $value$plusargs("VECTORS=%s", path_arg);
            if (have_arg)
                fd = $fopen(path_arg, "r");
            else
                fd = $fopen("tb/common/vectors/adder3_vectors.hex", "r");
            if (fd == 0)
                fd = $fopen("../tb/common/vectors/adder3_vectors.hex", "r");
            if (fd == 0)
                fd = $fopen("../../../../../../tb/common/vectors/adder3_vectors.hex", "r");
            if (fd == 0)
                fd = $fopen("./adder3_vectors.hex", "r");
        end
        if (fd == 0) begin
            $display("ERROR: cannot open adder3_vectors.hex");
            $display("Hint: pass +VECTORS=/absolute/path/adder3_vectors.hex");
            $finish;
        end

        // Parse each line: $sscanf returns 4 only when the line is a valid
        // four-hex-field vector, so comment lines ('//...') and blank lines
        // are skipped automatically (they return 0).
        begin : load_loop
            reg [1023:0] line;
            integer      r;
            while (!$feof(fd)) begin
                r = $fgets(line, fd);
                if (r == 0) disable load_loop;
                scan_status = $sscanf(line, "%h %h %h %h",
                                      tmp_a, tmp_b, tmp_c, tmp_exp);
                if (scan_status == 4) begin
                    v_a  [n_vectors] = $signed(tmp_a);
                    v_b  [n_vectors] = $signed(tmp_b);
                    v_c  [n_vectors] = $signed(tmp_c);
                    v_exp[n_vectors] = $signed(tmp_exp);
                    n_vectors        = n_vectors + 1;
                    if (n_vectors >= MAX_VECTORS) disable load_loop;
                end
            end
        end
        $fclose(fd);

        $display("Loaded %0d vectors.", n_vectors);
        if (n_vectors == 0) begin
            $display("ERROR: no vectors loaded");
            $finish;
        end

        // ---------------------------------------------------------------------
        // Drive each vector and check
        // ---------------------------------------------------------------------
        for (i = 0; i < n_vectors; i = i + 1) begin
            a_i = v_a[i];
            b_i = v_b[i];
            c_i = v_c[i];
            #1;  // settle combinational delay

            if (sum_o === v_exp[i]) begin
                pass_count = pass_count + 1;
            end else begin
                fail_count = fail_count + 1;
                if (dump_first_failures < 10) begin
                    $display("FAIL #%0d: a=%0d b=%0d c=%0d  got=%0d  exp=%0d",
                             i, a_i, b_i, c_i, sum_o, v_exp[i]);
                    dump_first_failures = dump_first_failures + 1;
                end
            end
        end

        // ---------------------------------------------------------------------
        // Summary
        // ---------------------------------------------------------------------
        $display("---------------------------------------------------------");
        $display("PASS: %0d / %0d", pass_count, n_vectors);
        $display("FAIL: %0d / %0d", fail_count, n_vectors);
        if (fail_count == 0)
            $display("RESULT: *** ALL TESTS PASSED ***");
        else
            $display("RESULT: *** %0d TESTS FAILED ***", fail_count);
        $display("=========================================================");
        $finish;
    end

endmodule

`default_nettype wire
// =============================================================================
// END tb_Adder3.v
// =============================================================================
