// =============================================================================
// tb_fifo_ctrl.v -- Self-checking testbench for Module 1.7 (fifo_ctrl)
// -----------------------------------------------------------------------------
// Thesis Sec 5.3.4.1 "3x3 Convolution FIFOs Controller" / Figure 5.14
// Thesis Sec 5.8.1 (Python golden -> hex file -> self-checking TB)
//
// Instantiates fifo_ctrl with SMALL parameters (IMG_W=4, IMG_H=4, PAD=1,
// STRIDE=2) for fast simulation.  Vectors are generated by
// scripts/gen_fifo_ctrl_vectors.py.
//
// Vector file format (one line per active clock cycle):
//   shift_and_load(0/1)  padding_sel(0/1)  rd_addr(4-hex-digits)
//   Lines where $sscanf returns != 3 are skipped (comments / blank).
//
// Checks performed each active clock cycle (after posedge, 1 ns delay):
//   1. shift_and_load == expected (always 1 outside IDLE)
//   2. padding_sel    == expected
//   3. rd_addr        == expected  (only checked when padding_sel expected = 0)
//
// Additional checks:
//   4. done fires exactly once, on the last active cycle
//   5. fsm_state returns to 0 (IDLE) after done
//   6. shift_and_load = 0 in IDLE after done
//
// Pass criterion: "RESULT: *** ALL TESTS PASSED ***"
// =============================================================================

`timescale 1ns / 1ps
`default_nettype none

`include "shufflenet_pkg.vh"

module tb_fifo_ctrl;

    // -------------------------------------------------------------------------
    // Small DUT parameters (fast simulation, easy to inspect by hand)
    // -------------------------------------------------------------------------
    localparam integer IMG_W   = 4;
    localparam integer IMG_H   = 4;
    localparam integer PAD     = 1;
    localparam integer STRIDE  = 2;
    localparam integer AW      = 16;

    localparam integer PADDED_W  = IMG_W + 2*PAD;
    localparam integer OUT_H     = (IMG_H + 2*PAD - 3) / STRIDE + 1;
    localparam integer MAX_CYCLES = 4096;

    // -------------------------------------------------------------------------
    // Clock and reset
    // -------------------------------------------------------------------------
    reg clk, rst, start;

    initial clk = 1'b0;
    always #5 clk = ~clk;   // 100 MHz

    // -------------------------------------------------------------------------
    // DUT
    // -------------------------------------------------------------------------
    wire        dut_sal;        // shift_and_load
    wire        dut_ps;         // padding_sel
    wire [AW-1:0] dut_addr;    // rd_addr
    wire [1:0]  dut_state;      // fsm_state
    wire        dut_done;

    fifo_ctrl #(
        .IMG_W  (IMG_W),
        .IMG_H  (IMG_H),
        .PAD    (PAD),
        .STRIDE (STRIDE),
        .AW     (AW)
    ) dut (
        .clk           (clk),
        .rst           (rst),
        .start         (start),
        .shift_and_load(dut_sal),
        .padding_sel   (dut_ps),
        .rd_addr       (dut_addr),
        .fsm_state     (dut_state),
        .done          (dut_done)
    );

    // -------------------------------------------------------------------------
    // Test state
    // -------------------------------------------------------------------------
    integer fd, r, sc;
    integer n_vectors, pass_count, fail_count, dump_count;
    integer cyc_idx, done_count, done_cyc;
    integer exp_sal, exp_ps;
    reg [AW-1:0] exp_addr;
    reg [8*512-1:0] path_arg;
    integer have_arg;
    reg [8*256-1:0] line_buf;

    localparam integer MAX_DUMP = 20;

    // -------------------------------------------------------------------------
    // Helper task: compare one cycle
    // -------------------------------------------------------------------------
    task check_cycle;
        input integer cyc;
        input e_sal, e_ps;
        input [AW-1:0] e_addr;
        begin
            if (dut_sal !== e_sal || dut_ps !== e_ps ||
                (e_ps == 0 && dut_addr !== e_addr)) begin
                fail_count = fail_count + 1;
                if (dump_count < MAX_DUMP) begin
                    $display("FAIL cyc %0d: sal=%b(exp %b) ps=%b(exp %b) addr=%04X(exp %04X)",
                        cyc, dut_sal, e_sal, dut_ps, e_ps, dut_addr, e_addr);
                    dump_count = dump_count + 1;
                end
            end else begin
                pass_count = pass_count + 1;
            end
        end
    endtask

    // -------------------------------------------------------------------------
    // Main test body
    // -------------------------------------------------------------------------
    initial begin
        n_vectors  = 0;
        pass_count = 0;
        fail_count = 0;
        dump_count = 0;
        cyc_idx    = 0;
        done_count = 0;
        done_cyc   = -1;

        $display("=========================================================");
        $display("fifo_ctrl Testbench (Thesis Sec 5.3.4.1 / Fig 5.14)");
        $display("IMG_W=%0d IMG_H=%0d PAD=%0d STRIDE=%0d  OUT_H=%0d",
                 IMG_W, IMG_H, PAD, STRIDE, OUT_H);
        $display("=========================================================");

        // ---- Open vector file ----
        have_arg = $value$plusargs("VECTORS=%s", path_arg);
        if (have_arg)
            fd = $fopen(path_arg, "r");
        else
            fd = $fopen("tb/common/vectors/fifo_ctrl_vectors.hex", "r");
        if (fd == 0)
            fd = $fopen("../tb/common/vectors/fifo_ctrl_vectors.hex", "r");
        if (fd == 0)
            fd = $fopen("../../../../../../tb/common/vectors/fifo_ctrl_vectors.hex", "r");
        if (fd == 0)
            fd = $fopen("./fifo_ctrl_vectors.hex", "r");
        if (fd == 0) begin
            $display("ERROR: cannot open fifo_ctrl_vectors.hex");
            $display("Run: python scripts/gen_fifo_ctrl_vectors.py");
            $finish;
        end

        // ---- Reset: 4 cycles, active-high ----
        rst   = 1'b1;
        start = 1'b0;
        repeat(4) @(posedge clk);
        @(negedge clk); rst = 1'b0;

        // Verify: IDLE state before start -> shift_and_load = 0
        @(negedge clk);
        @(posedge clk); #1;
        if (dut_sal !== 1'b0 || dut_state !== 2'd0) begin
            $display("FAIL: before start: sal=%b (exp 0), state=%0d (exp 0)",
                     dut_sal, dut_state);
            fail_count = fail_count + 1;
        end else begin
            $display("PASS: IDLE state before start (sal=0, state=0)");
            pass_count = pass_count + 1;
        end

        // ---- Pulse start for 1 cycle ----
        @(negedge clk); start = 1'b1;
        @(negedge clk); start = 1'b0;

        // ---- Main checking loop: read vector file and check each cycle ----
        begin : main_loop
            while (!$feof(fd)) begin
                r = $fgets(line_buf, fd);
                if (r == 0) disable main_loop;

                sc = $sscanf(line_buf, " %d %d %h",
                             exp_sal, exp_ps, exp_addr);
                if (sc != 3) begin
                    // Comment or blank line -- skip, do not advance clock
                end else begin
                    // Wait for next clock edge, then sample outputs
                    @(posedge clk); #1;

                    // Capture done BEFORE checking (it's valid at this posedge)
                    if (dut_done) begin
                        done_count = done_count + 1;
                        done_cyc   = cyc_idx;
                    end

                    check_cycle(cyc_idx, exp_sal, exp_ps, exp_addr);
                    n_vectors = n_vectors + 1;
                    cyc_idx   = cyc_idx + 1;
                end
            end
        end
        $fclose(fd);

        // ---- Check done fired exactly once ----
        if (done_count == 1) begin
            $display("PASS: done pulsed exactly once (at active cycle %0d)",
                     done_cyc);
            pass_count = pass_count + 1;
        end else begin
            $display("FAIL: done count = %0d (expected 1)", done_count);
            fail_count = fail_count + 1;
        end

        // ---- Check state returns to IDLE after done ----
        @(posedge clk); #1;
        if (dut_state === 2'd0) begin
            $display("PASS: fsm_state = IDLE (0) after done");
            pass_count = pass_count + 1;
        end else begin
            $display("FAIL: fsm_state = %0d after done (expected 0)", dut_state);
            fail_count = fail_count + 1;
        end

        if (dut_sal === 1'b0) begin
            $display("PASS: shift_and_load = 0 in IDLE after done");
            pass_count = pass_count + 1;
        end else begin
            $display("FAIL: shift_and_load = %b in IDLE after done (expected 0)",
                     dut_sal);
            fail_count = fail_count + 1;
        end

        // ---- Summary ----
        $display("---------------------------------------------------------");
        $display("Vectors checked : %0d", n_vectors);
        $display("PASS: %0d / %0d", pass_count, pass_count + fail_count);
        $display("FAIL: %0d / %0d", fail_count, pass_count + fail_count);
        $display("---------------------------------------------------------");
        if (fail_count == 0)
            $display("RESULT: *** ALL TESTS PASSED ***");
        else
            $display("RESULT: *** %0d TESTS FAILED ***", fail_count);
        $display("=========================================================");

        $finish;
    end

    // -------------------------------------------------------------------------
    // Timeout guard
    // -------------------------------------------------------------------------
    initial begin
        #(MAX_CYCLES * 10 + 5000);
        $display("TIMEOUT after %0d cycles", MAX_CYCLES);
        $finish;
    end

endmodule

`default_nettype wire
// =============================================================================
// END tb_fifo_ctrl.v
// =============================================================================
