// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================
`timescale 1 ns / 1 ps
module Shuffle_Model_shuffle_block_s1_1_Pipeline_VITIS_LOOP_183_1_VITIS_LOOP_184_2_VITIS_LOOP_185_g8j (
    address0, ce0, q0, 
    reset, clk);

parameter DataWidth = 11;
parameter AddressWidth = 10;
parameter AddressRange = 522;
 
input[AddressWidth-1:0] address0;
input ce0;
output reg[DataWidth-1:0] q0;

input reset;
input clk;

 
reg [DataWidth-1:0] rom0[0:AddressRange-1];


initial begin
     
    $readmemh("./Shuffle_Model_shuffle_block_s1_1_Pipeline_VITIS_LOOP_183_1_VITIS_LOOP_184_2_VITIS_LOOP_185_g8j.dat", rom0);
end

  
always @(posedge clk) 
begin 
    if (ce0) 
    begin
        q0 <= rom0[address0];
    end
end


endmodule

