// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Shuffle_Model_shuffle_block_s1_4_Pipeline_VITIS_LOOP_316_11_VITIS_LOOP_317_12 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        temp_pw2_address0,
        temp_pw2_ce0,
        temp_pw2_q0,
        concat_1_address0,
        concat_1_ce0,
        concat_1_we0,
        concat_1_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [15:0] temp_pw2_address0;
output   temp_pw2_ce0;
input  [13:0] temp_pw2_q0;
output  [16:0] concat_1_address0;
output   concat_1_ce0;
output   concat_1_we0;
output  [15:0] concat_1_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln316_fu_98_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [7:0] select_ln316_fu_122_p3;
reg   [7:0] select_ln316_reg_242;
wire   [6:0] select_ln316_3_fu_136_p3;
reg   [6:0] select_ln316_3_reg_247;
wire   [15:0] add_ln318_3_fu_202_p2;
reg   [15:0] add_ln318_3_reg_257;
wire   [63:0] zext_ln318_fu_187_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln318_9_fu_213_p1;
reg   [7:0] i_fu_42;
wire   [7:0] add_ln317_fu_144_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_i_load;
reg   [6:0] c_fu_46;
reg   [6:0] ap_sig_allocacmp_c_load;
reg   [14:0] indvar_flatten147_fu_50;
wire   [14:0] add_ln316_fu_104_p2;
reg   [14:0] ap_sig_allocacmp_indvar_flatten147_load;
reg    temp_pw2_ce0_local;
reg    concat_1_we0_local;
wire   [15:0] zext_ln318_7_fu_208_p1;
reg    concat_1_ce0_local;
wire   [0:0] icmp_ln317_fu_116_p2;
wire   [6:0] add_ln316_3_fu_130_p2;
wire   [6:0] empty_fu_168_p0;
wire   [8:0] empty_fu_168_p1;
wire   [14:0] empty_fu_168_p2;
wire   [14:0] zext_ln317_3_fu_178_p1;
wire   [14:0] add_ln318_fu_181_p2;
wire   [14:0] add_ln318_4_fu_192_p2;
wire   [15:0] zext_ln318_8_fu_198_p1;
wire   [15:0] zext_ln317_fu_174_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [14:0] empty_fu_168_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 i_fu_42 = 8'd0;
#0 c_fu_46 = 7'd0;
#0 indvar_flatten147_fu_50 = 15'd0;
#0 ap_done_reg = 1'b0;
end

Shuffle_Model_mul_7ns_9ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 15 ))
mul_7ns_9ns_15_1_1_U370(
    .din0(empty_fu_168_p0),
    .din1(empty_fu_168_p1),
    .dout(empty_fu_168_p2)
);

Shuffle_Model_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln316_fu_98_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            c_fu_46 <= select_ln316_3_fu_136_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_46 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln316_fu_98_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_42 <= add_ln317_fu_144_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_42 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln316_fu_98_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten147_fu_50 <= add_ln316_fu_104_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten147_fu_50 <= 15'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln318_3_reg_257 <= add_ln318_3_fu_202_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        select_ln316_3_reg_247 <= select_ln316_3_fu_136_p3;
        select_ln316_reg_242 <= select_ln316_fu_122_p3;
    end
end

always @ (*) begin
    if (((icmp_ln316_fu_98_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_c_load = 7'd0;
    end else begin
        ap_sig_allocacmp_c_load = c_fu_46;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_load = 8'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_42;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten147_load = 15'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten147_load = indvar_flatten147_fu_50;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        concat_1_ce0_local = 1'b1;
    end else begin
        concat_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        concat_1_we0_local = 1'b1;
    end else begin
        concat_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_pw2_ce0_local = 1'b1;
    end else begin
        temp_pw2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln316_3_fu_130_p2 = (ap_sig_allocacmp_c_load + 7'd1);

assign add_ln316_fu_104_p2 = (ap_sig_allocacmp_indvar_flatten147_load + 15'd1);

assign add_ln317_fu_144_p2 = (select_ln316_fu_122_p3 + 8'd1);

assign add_ln318_3_fu_202_p2 = (zext_ln318_8_fu_198_p1 + zext_ln317_fu_174_p1);

assign add_ln318_4_fu_192_p2 = ($signed(zext_ln317_3_fu_178_p1) + $signed(15'd22736));

assign add_ln318_fu_181_p2 = (zext_ln317_3_fu_178_p1 + empty_fu_168_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign concat_1_address0 = zext_ln318_9_fu_213_p1;

assign concat_1_ce0 = concat_1_ce0_local;

assign concat_1_d0 = zext_ln318_7_fu_208_p1;

assign concat_1_we0 = concat_1_we0_local;

assign empty_fu_168_p0 = empty_fu_168_p00;

assign empty_fu_168_p00 = select_ln316_3_reg_247;

assign empty_fu_168_p1 = 15'd196;

assign icmp_ln316_fu_98_p2 = ((ap_sig_allocacmp_indvar_flatten147_load == 15'd22736) ? 1'b1 : 1'b0);

assign icmp_ln317_fu_116_p2 = ((ap_sig_allocacmp_i_load == 8'd196) ? 1'b1 : 1'b0);

assign select_ln316_3_fu_136_p3 = ((icmp_ln317_fu_116_p2[0:0] == 1'b1) ? add_ln316_3_fu_130_p2 : ap_sig_allocacmp_c_load);

assign select_ln316_fu_122_p3 = ((icmp_ln317_fu_116_p2[0:0] == 1'b1) ? 8'd0 : ap_sig_allocacmp_i_load);

assign temp_pw2_address0 = zext_ln318_fu_187_p1;

assign temp_pw2_ce0 = temp_pw2_ce0_local;

assign zext_ln317_3_fu_178_p1 = select_ln316_reg_242;

assign zext_ln317_fu_174_p1 = empty_fu_168_p2;

assign zext_ln318_7_fu_208_p1 = temp_pw2_q0;

assign zext_ln318_8_fu_198_p1 = add_ln318_4_fu_192_p2;

assign zext_ln318_9_fu_213_p1 = add_ln318_3_reg_257;

assign zext_ln318_fu_187_p1 = add_ln318_fu_181_p2;

endmodule //Shuffle_Model_shuffle_block_s1_4_Pipeline_VITIS_LOOP_316_11_VITIS_LOOP_317_12
