// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Shuffle_Model_shuffle_block_s2_2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        b1_pw_out_address0,
        b1_pw_out_ce0,
        b1_pw_out_q0,
        concat_address0,
        concat_ce0,
        concat_we0,
        concat_d0,
        concat_address1,
        concat_ce1,
        concat_we1,
        concat_d1,
        b2_pw2_out_address0,
        b2_pw2_out_ce0,
        b2_pw2_out_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [14:0] b1_pw_out_address0;
output   b1_pw_out_ce0;
input  [13:0] b1_pw_out_q0;
output  [16:0] concat_address0;
output   concat_ce0;
output   concat_we0;
output  [15:0] concat_d0;
output  [16:0] concat_address1;
output   concat_ce1;
output   concat_we1;
output  [15:0] concat_d1;
output  [14:0] b2_pw2_out_address0;
output   b2_pw2_out_ce0;
input  [13:0] b2_pw2_out_q0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln436_fu_125_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [7:0] select_ln436_fu_149_p3;
reg   [7:0] select_ln436_reg_275;
wire   [6:0] select_ln436_2_fu_163_p3;
reg   [6:0] select_ln436_2_reg_280;
wire   [63:0] zext_ln438_fu_214_p1;
reg   [63:0] zext_ln438_reg_285;
wire   [15:0] add_ln439_fu_230_p2;
reg   [15:0] add_ln439_reg_300;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln439_4_fu_246_p1;
reg   [7:0] i_fu_44;
wire   [7:0] add_ln437_fu_171_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_i_load;
reg   [6:0] c_fu_48;
reg   [6:0] ap_sig_allocacmp_c_load;
reg   [14:0] indvar_flatten68_fu_52;
wire   [14:0] add_ln436_fu_131_p2;
reg   [14:0] ap_sig_allocacmp_indvar_flatten68_load;
reg    b1_pw_out_ce0_local;
reg    b2_pw2_out_ce0_local;
reg    concat_we1_local;
wire   [15:0] zext_ln438_2_fu_236_p1;
reg    concat_ce1_local;
reg    concat_we0_local;
wire   [15:0] zext_ln439_fu_241_p1;
reg    concat_ce0_local;
wire   [0:0] icmp_ln437_fu_143_p2;
wire   [6:0] add_ln436_2_fu_157_p2;
wire   [6:0] empty_fu_195_p0;
wire   [8:0] empty_fu_195_p1;
wire   [14:0] empty_fu_195_p2;
wire   [14:0] zext_ln437_2_fu_205_p1;
wire   [14:0] add_ln438_fu_208_p2;
wire   [14:0] add_ln439_2_fu_220_p2;
wire   [15:0] zext_ln439_3_fu_226_p1;
wire   [15:0] zext_ln437_fu_201_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [14:0] empty_fu_195_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 i_fu_44 = 8'd0;
#0 c_fu_48 = 7'd0;
#0 indvar_flatten68_fu_52 = 15'd0;
#0 ap_done_reg = 1'b0;
end

Shuffle_Model_mul_7ns_9ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 15 ))
mul_7ns_9ns_15_1_1_U267(
    .din0(empty_fu_195_p0),
    .din1(empty_fu_195_p1),
    .dout(empty_fu_195_p2)
);

Shuffle_Model_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln436_fu_125_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            c_fu_48 <= select_ln436_2_fu_163_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_48 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln436_fu_125_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_44 <= add_ln437_fu_171_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_44 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln436_fu_125_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten68_fu_52 <= add_ln436_fu_131_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten68_fu_52 <= 15'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln439_reg_300 <= add_ln439_fu_230_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        select_ln436_2_reg_280 <= select_ln436_2_fu_163_p3;
        select_ln436_reg_275 <= select_ln436_fu_149_p3;
        zext_ln438_reg_285[14 : 0] <= zext_ln438_fu_214_p1[14 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln436_fu_125_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_c_load = 7'd0;
    end else begin
        ap_sig_allocacmp_c_load = c_fu_48;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_load = 8'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_44;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten68_load = 15'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten68_load = indvar_flatten68_fu_52;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b1_pw_out_ce0_local = 1'b1;
    end else begin
        b1_pw_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b2_pw2_out_ce0_local = 1'b1;
    end else begin
        b2_pw2_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        concat_ce0_local = 1'b1;
    end else begin
        concat_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        concat_ce1_local = 1'b1;
    end else begin
        concat_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        concat_we0_local = 1'b1;
    end else begin
        concat_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        concat_we1_local = 1'b1;
    end else begin
        concat_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln436_2_fu_157_p2 = (ap_sig_allocacmp_c_load + 7'd1);

assign add_ln436_fu_131_p2 = (ap_sig_allocacmp_indvar_flatten68_load + 15'd1);

assign add_ln437_fu_171_p2 = (select_ln436_fu_149_p3 + 8'd1);

assign add_ln438_fu_208_p2 = (zext_ln437_2_fu_205_p1 + empty_fu_195_p2);

assign add_ln439_2_fu_220_p2 = ($signed(zext_ln437_2_fu_205_p1) + $signed(15'd22736));

assign add_ln439_fu_230_p2 = (zext_ln439_3_fu_226_p1 + zext_ln437_fu_201_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign b1_pw_out_address0 = zext_ln438_fu_214_p1;

assign b1_pw_out_ce0 = b1_pw_out_ce0_local;

assign b2_pw2_out_address0 = zext_ln438_fu_214_p1;

assign b2_pw2_out_ce0 = b2_pw2_out_ce0_local;

assign concat_address0 = zext_ln439_4_fu_246_p1;

assign concat_address1 = zext_ln438_reg_285;

assign concat_ce0 = concat_ce0_local;

assign concat_ce1 = concat_ce1_local;

assign concat_d0 = zext_ln439_fu_241_p1;

assign concat_d1 = zext_ln438_2_fu_236_p1;

assign concat_we0 = concat_we0_local;

assign concat_we1 = concat_we1_local;

assign empty_fu_195_p0 = empty_fu_195_p00;

assign empty_fu_195_p00 = select_ln436_2_reg_280;

assign empty_fu_195_p1 = 15'd196;

assign icmp_ln436_fu_125_p2 = ((ap_sig_allocacmp_indvar_flatten68_load == 15'd22736) ? 1'b1 : 1'b0);

assign icmp_ln437_fu_143_p2 = ((ap_sig_allocacmp_i_load == 8'd196) ? 1'b1 : 1'b0);

assign select_ln436_2_fu_163_p3 = ((icmp_ln437_fu_143_p2[0:0] == 1'b1) ? add_ln436_2_fu_157_p2 : ap_sig_allocacmp_c_load);

assign select_ln436_fu_149_p3 = ((icmp_ln437_fu_143_p2[0:0] == 1'b1) ? 8'd0 : ap_sig_allocacmp_i_load);

assign zext_ln437_2_fu_205_p1 = select_ln436_reg_275;

assign zext_ln437_fu_201_p1 = empty_fu_195_p2;

assign zext_ln438_2_fu_236_p1 = b1_pw_out_q0;

assign zext_ln438_fu_214_p1 = add_ln438_fu_208_p2;

assign zext_ln439_3_fu_226_p1 = add_ln439_2_fu_220_p2;

assign zext_ln439_4_fu_246_p1 = add_ln439_reg_300;

assign zext_ln439_fu_241_p1 = b2_pw2_out_q0;

always @ (posedge ap_clk) begin
    zext_ln438_reg_285[63:15] <= 49'b0000000000000000000000000000000000000000000000000;
end

endmodule //Shuffle_Model_shuffle_block_s2_2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10
