// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Shuffle_Model_shuffle_block_s2_Pipeline_VITIS_LOOP_385_1_VITIS_LOOP_386_2_VITIS_LOOP_387_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sm1_address0,
        sm1_ce0,
        sm1_q0,
        b2_in_address0,
        b2_in_ce0,
        b2_in_we0,
        b2_in_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [17:0] sm1_address0;
output   sm1_ce0;
input  [15:0] sm1_q0;
output  [16:0] b2_in_address0;
output   b2_in_ce0;
output   b2_in_we0;
output  [15:0] b2_in_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln385_fu_149_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln386_fu_167_p2;
reg   [0:0] icmp_ln386_reg_450;
wire   [16:0] zext_ln385_fu_187_p1;
reg   [10:0] tmp_1_reg_463;
wire   [5:0] add_ln389_fu_354_p2;
reg   [5:0] add_ln389_reg_473;
wire   [16:0] add_ln388_fu_367_p2;
reg   [16:0] add_ln388_reg_478;
reg   [16:0] add_ln388_reg_478_pp0_iter3_reg;
reg   [16:0] add_ln388_reg_478_pp0_iter4_reg;
reg   [16:0] add_ln388_reg_478_pp0_iter5_reg;
wire   [16:0] grp_fu_394_p3;
wire   [63:0] zext_ln389_1_fu_386_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln388_fu_390_p1;
reg   [5:0] w_i_fu_74;
wire    ap_loop_init;
reg   [5:0] h_fu_78;
wire   [5:0] select_ln386_fu_312_p3;
reg   [11:0] indvar_flatten_fu_82;
wire   [11:0] select_ln386_1_fu_213_p3;
reg   [4:0] c_fu_86;
wire   [4:0] select_ln385_2_fu_179_p3;
reg   [16:0] indvar_flatten14_fu_90;
wire   [16:0] add_ln385_fu_155_p2;
reg    sm1_ce0_local;
reg    b2_in_we0_local;
reg    b2_in_ce0_local;
wire   [4:0] add_ln385_1_fu_173_p2;
wire   [4:0] empty_53_fu_191_p0;
wire   [12:0] empty_53_fu_191_p1;
wire   [16:0] empty_53_fu_191_p2;
wire   [11:0] add_ln386_fu_207_p2;
wire   [5:0] indvars_iv_next96108_fu_249_p2;
wire   [0:0] icmp_ln387_fu_267_p2;
wire   [0:0] xor_ln385_fu_262_p2;
wire   [5:0] select_ln385_fu_242_p3;
wire   [0:0] and_ln385_fu_273_p2;
wire   [0:0] empty_fu_285_p2;
wire   [5:0] indvars_iv_next96_mid1_fu_298_p2;
wire   [5:0] select_ln385_1_fu_255_p3;
wire   [5:0] indvars_iv_next96_dup_fu_279_p2;
wire   [5:0] indvars_iv_next96_mid2_fu_304_p3;
wire   [8:0] tmp_1_2_fu_332_p3;
wire   [11:0] p_shl_fu_324_p3;
wire   [11:0] p_shl5_fu_340_p1;
wire   [11:0] empty_55_fu_344_p2;
wire   [5:0] w_i_mid2_fu_290_p3;
wire   [16:0] tmp1_fu_360_p3;
wire   [16:0] zext_ln387_fu_350_p1;
wire   [16:0] grp_fu_402_p3;
wire   [11:0] grp_fu_394_p0;
wire   [4:0] grp_fu_394_p1;
wire   [5:0] grp_fu_394_p2;
wire   [5:0] grp_fu_402_p0;
wire   [5:0] grp_fu_402_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [16:0] grp_fu_394_p20;
wire   [11:0] grp_fu_402_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 w_i_fu_74 = 6'd0;
#0 h_fu_78 = 6'd0;
#0 indvar_flatten_fu_82 = 12'd0;
#0 c_fu_86 = 5'd0;
#0 indvar_flatten14_fu_90 = 17'd0;
#0 ap_done_reg = 1'b0;
end

Shuffle_Model_mul_5ns_13ns_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 17 ))
mul_5ns_13ns_17_1_1_U49(
    .din0(empty_53_fu_191_p0),
    .din1(empty_53_fu_191_p1),
    .dout(empty_53_fu_191_p2)
);

Shuffle_Model_mac_muladd_12ns_5ns_6ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 5 ),
    .din2_WIDTH( 6 ),
    .dout_WIDTH( 17 ))
mac_muladd_12ns_5ns_6ns_17_4_1_U50(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_394_p0),
    .din1(grp_fu_394_p1),
    .din2(grp_fu_394_p2),
    .ce(1'b1),
    .dout(grp_fu_394_p3)
);

Shuffle_Model_mac_muladd_6ns_6ns_17ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 17 ))
mac_muladd_6ns_6ns_17ns_17_4_1_U51(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_402_p0),
    .din1(grp_fu_402_p1),
    .din2(grp_fu_394_p3),
    .ce(1'b1),
    .dout(grp_fu_402_p3)
);

Shuffle_Model_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            c_fu_86 <= 5'd0;
        end else if (((icmp_ln385_fu_149_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            c_fu_86 <= select_ln385_2_fu_179_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            h_fu_78 <= 6'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            h_fu_78 <= select_ln386_fu_312_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten14_fu_90 <= 17'd0;
        end else if (((icmp_ln385_fu_149_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten14_fu_90 <= add_ln385_fu_155_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_82 <= 12'd0;
        end else if (((icmp_ln385_fu_149_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten_fu_82 <= select_ln386_1_fu_213_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            w_i_fu_74 <= 6'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            w_i_fu_74 <= add_ln389_fu_354_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln388_reg_478 <= add_ln388_fu_367_p2;
        add_ln388_reg_478_pp0_iter3_reg <= add_ln388_reg_478;
        add_ln388_reg_478_pp0_iter4_reg <= add_ln388_reg_478_pp0_iter3_reg;
        add_ln388_reg_478_pp0_iter5_reg <= add_ln388_reg_478_pp0_iter4_reg;
        add_ln389_reg_473 <= add_ln389_fu_354_p2;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln386_reg_450 <= icmp_ln386_fu_167_p2;
        tmp_1_reg_463 <= {{empty_53_fu_191_p2[16:6]}};
    end
end

always @ (*) begin
    if (((icmp_ln385_fu_149_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        b2_in_ce0_local = 1'b1;
    end else begin
        b2_in_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        b2_in_we0_local = 1'b1;
    end else begin
        b2_in_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        sm1_ce0_local = 1'b1;
    end else begin
        sm1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln385_1_fu_173_p2 = (c_fu_86 + 5'd1);

assign add_ln385_fu_155_p2 = (indvar_flatten14_fu_90 + 17'd1);

assign add_ln386_fu_207_p2 = (indvar_flatten_fu_82 + 12'd1);

assign add_ln388_fu_367_p2 = (tmp1_fu_360_p3 + zext_ln387_fu_350_p1);

assign add_ln389_fu_354_p2 = (w_i_mid2_fu_290_p3 + 6'd1);

assign and_ln385_fu_273_p2 = (xor_ln385_fu_262_p2 & icmp_ln387_fu_267_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign b2_in_address0 = zext_ln388_fu_390_p1;

assign b2_in_ce0 = b2_in_ce0_local;

assign b2_in_d0 = sm1_q0;

assign b2_in_we0 = b2_in_we0_local;

assign empty_53_fu_191_p0 = zext_ln385_fu_187_p1;

assign empty_53_fu_191_p1 = 17'd3136;

assign empty_55_fu_344_p2 = (p_shl_fu_324_p3 - p_shl5_fu_340_p1);

assign empty_fu_285_p2 = (icmp_ln386_reg_450 | and_ln385_fu_273_p2);

assign grp_fu_394_p0 = 17'd3364;

assign grp_fu_394_p1 = zext_ln385_fu_187_p1;

assign grp_fu_394_p2 = grp_fu_394_p20;

assign grp_fu_394_p20 = add_ln389_reg_473;

assign grp_fu_402_p0 = grp_fu_402_p00;

assign grp_fu_402_p00 = indvars_iv_next96_mid2_fu_304_p3;

assign grp_fu_402_p1 = 12'd58;

assign icmp_ln385_fu_149_p2 = ((indvar_flatten14_fu_90 == 17'd75264) ? 1'b1 : 1'b0);

assign icmp_ln386_fu_167_p2 = ((indvar_flatten_fu_82 == 12'd3136) ? 1'b1 : 1'b0);

assign icmp_ln387_fu_267_p2 = ((w_i_fu_74 == 6'd56) ? 1'b1 : 1'b0);

assign indvars_iv_next96108_fu_249_p2 = (h_fu_78 + 6'd1);

assign indvars_iv_next96_dup_fu_279_p2 = (select_ln385_fu_242_p3 + 6'd1);

assign indvars_iv_next96_mid1_fu_298_p2 = (select_ln385_fu_242_p3 + 6'd2);

assign indvars_iv_next96_mid2_fu_304_p3 = ((and_ln385_fu_273_p2[0:0] == 1'b1) ? indvars_iv_next96_mid1_fu_298_p2 : select_ln385_1_fu_255_p3);

assign p_shl5_fu_340_p1 = tmp_1_2_fu_332_p3;

assign p_shl_fu_324_p3 = {{select_ln386_fu_312_p3}, {6'd0}};

assign select_ln385_1_fu_255_p3 = ((icmp_ln386_reg_450[0:0] == 1'b1) ? 6'd1 : indvars_iv_next96108_fu_249_p2);

assign select_ln385_2_fu_179_p3 = ((icmp_ln386_fu_167_p2[0:0] == 1'b1) ? add_ln385_1_fu_173_p2 : c_fu_86);

assign select_ln385_fu_242_p3 = ((icmp_ln386_reg_450[0:0] == 1'b1) ? 6'd0 : h_fu_78);

assign select_ln386_1_fu_213_p3 = ((icmp_ln386_fu_167_p2[0:0] == 1'b1) ? 12'd1 : add_ln386_fu_207_p2);

assign select_ln386_fu_312_p3 = ((and_ln385_fu_273_p2[0:0] == 1'b1) ? indvars_iv_next96_dup_fu_279_p2 : select_ln385_fu_242_p3);

assign sm1_address0 = zext_ln389_1_fu_386_p1;

assign sm1_ce0 = sm1_ce0_local;

assign tmp1_fu_360_p3 = {{tmp_1_reg_463}, {w_i_mid2_fu_290_p3}};

assign tmp_1_2_fu_332_p3 = {{select_ln386_fu_312_p3}, {3'd0}};

assign w_i_mid2_fu_290_p3 = ((empty_fu_285_p2[0:0] == 1'b1) ? 6'd0 : w_i_fu_74);

assign xor_ln385_fu_262_p2 = (icmp_ln386_reg_450 ^ 1'd1);

assign zext_ln385_fu_187_p1 = select_ln385_2_fu_179_p3;

assign zext_ln387_fu_350_p1 = empty_55_fu_344_p2;

assign zext_ln388_fu_390_p1 = add_ln388_reg_478_pp0_iter5_reg;

assign zext_ln389_1_fu_386_p1 = grp_fu_402_p3;

endmodule //Shuffle_Model_shuffle_block_s2_Pipeline_VITIS_LOOP_385_1_VITIS_LOOP_386_2_VITIS_LOOP_387_3
