// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Shuffle_Model_shuffle_block_s1_3_Pipeline_VITIS_LOOP_183_1_VITIS_LOOP_184_2_VITIS_LOOP_185_3_V (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        b2_dw_b_address0,
        b2_dw_b_ce0,
        b2_dw_b_q0,
        b2_dw_w_address0,
        b2_dw_w_ce0,
        b2_dw_w_q0,
        temp_dw_out_address0,
        temp_dw_out_ce0,
        temp_dw_out_we0,
        temp_dw_out_d0,
        temp_dw_in_address0,
        temp_dw_in_ce0,
        temp_dw_in_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [6:0] b2_dw_b_address0;
output   b2_dw_b_ce0;
input  [9:0] b2_dw_b_q0;
output  [10:0] b2_dw_w_address0;
output   b2_dw_w_ce0;
input  [14:0] b2_dw_w_q0;
output  [15:0] temp_dw_out_address0;
output   temp_dw_out_ce0;
output   temp_dw_out_we0;
output  [15:0] temp_dw_out_d0;
output  [15:0] temp_dw_in_address0;
output   temp_dw_in_ce0;
input  [13:0] temp_dw_in_q0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln183_fu_258_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln184_fu_273_p2;
reg   [0:0] icmp_ln184_reg_930;
wire   [0:0] xor_ln183_fu_279_p2;
reg   [0:0] xor_ln183_reg_935;
wire   [0:0] and_ln183_8_fu_297_p2;
reg   [0:0] and_ln183_8_reg_940;
wire   [6:0] select_ln183_5_fu_309_p3;
reg   [6:0] select_ln183_5_reg_945;
reg   [6:0] select_ln183_5_reg_945_pp0_iter2_reg;
wire   [0:0] empty_fu_317_p2;
reg   [0:0] empty_reg_954;
wire   [0:0] not_exitcond_flatten82_mid2139_fu_329_p2;
reg   [0:0] not_exitcond_flatten82_mid2139_reg_960;
wire   [0:0] exitcond_flatten67_mid2104_fu_341_p2;
reg   [0:0] exitcond_flatten67_mid2104_reg_965;
wire   [0:0] empty_186_fu_353_p2;
reg   [0:0] empty_186_reg_972;
reg   [0:0] empty_186_reg_972_pp0_iter2_reg;
reg   [0:0] empty_186_reg_972_pp0_iter3_reg;
wire   [3:0] select_ln184_fu_474_p3;
reg   [3:0] select_ln184_reg_978;
reg   [3:0] select_ln184_reg_978_pp0_iter3_reg;
reg   [3:0] select_ln184_reg_978_pp0_iter4_reg;
wire   [3:0] select_ln185_fu_505_p3;
reg   [3:0] select_ln185_reg_984;
reg   [3:0] select_ln185_reg_984_pp0_iter3_reg;
wire   [0:0] icmp_ln188_4_fu_656_p2;
reg   [0:0] icmp_ln188_4_reg_1004;
reg   [0:0] icmp_ln188_4_reg_1004_pp0_iter3_reg;
reg   [0:0] icmp_ln188_4_reg_1004_pp0_iter4_reg;
wire   [0:0] icmp_ln187_4_fu_662_p2;
reg   [0:0] icmp_ln187_4_reg_1008;
reg   [0:0] icmp_ln187_4_reg_1008_pp0_iter3_reg;
reg   [0:0] icmp_ln187_4_reg_1008_pp0_iter4_reg;
wire   [28:0] mul_ln193_fu_700_p2;
reg   [28:0] mul_ln193_reg_1017;
wire   [14:0] select_ln39_fu_792_p3;
reg   [14:0] select_ln39_reg_1027;
wire   [63:0] zext_ln192_4_fu_628_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln193_4_fu_645_p1;
wire   [63:0] zext_ln183_fu_688_p1;
wire   [63:0] zext_ln197_fu_842_p1;
reg   [63:0] acc_7_fu_104;
wire   [63:0] acc_fu_726_p2;
wire    ap_loop_init;
reg   [1:0] kw_fu_108;
wire   [1:0] add_ln188_fu_650_p2;
reg   [1:0] kh_fu_112;
wire   [1:0] select_ln187_fu_536_p3;
reg   [3:0] indvar_flatten65_fu_116;
wire   [3:0] select_ln187_5_fu_365_p3;
reg   [3:0] ow_fu_120;
reg   [7:0] indvar_flatten80_fu_124;
wire   [7:0] select_ln185_4_fu_379_p3;
reg   [3:0] oh_fu_128;
reg   [10:0] indvar_flatten105_fu_132;
wire   [10:0] select_ln184_4_fu_393_p3;
reg   [6:0] c_fu_136;
reg   [17:0] indvar_flatten140_fu_140;
wire   [17:0] add_ln183_fu_264_p2;
reg    temp_dw_in_ce0_local;
reg    b2_dw_w_ce0_local;
reg    b2_dw_b_ce0_local;
reg    temp_dw_out_we0_local;
wire  signed [15:0] sext_ln197_fu_833_p1;
reg    temp_dw_out_ce0_local;
wire   [0:0] icmp_ln185_fu_291_p2;
wire   [6:0] add_ln183_4_fu_303_p2;
wire   [0:0] exitcond_flatten82_not_fu_323_p2;
wire   [0:0] icmp_ln187_fu_285_p2;
wire   [0:0] and_ln183_7_fu_335_p2;
wire   [0:0] empty_185_fu_347_p2;
wire   [3:0] add_ln187_4_fu_359_p2;
wire   [7:0] add_ln185_4_fu_373_p2;
wire   [10:0] add_ln184_4_fu_387_p2;
wire   [0:0] icmp_ln188_fu_445_p2;
wire   [3:0] select_ln183_fu_438_p3;
wire   [0:0] and_ln183_fu_451_p2;
wire   [3:0] add_ln184_fu_456_p2;
wire   [3:0] ow_mid287_fu_462_p3;
wire   [0:0] icmp_ln188_mid2100_fu_469_p2;
wire   [0:0] not_exitcond_flatten67_mid2104_fu_494_p2;
wire   [3:0] add_ln185_fu_481_p2;
wire   [1:0] kh_mid272_fu_487_p3;
wire   [0:0] empty_187_fu_518_p2;
wire   [0:0] icmp_ln188_mid279_fu_499_p2;
wire   [0:0] empty_188_fu_522_p2;
wire   [1:0] add_ln187_fu_512_p2;
wire   [9:0] tmp_1_fu_550_p3;
wire   [10:0] p_shl4_fu_557_p1;
wire   [10:0] zext_ln183_9_fu_544_p1;
wire   [3:0] zext_ln187_fu_567_p1;
wire   [3:0] p_shl_fu_577_p3;
wire   [3:0] empty_193_fu_585_p2;
wire   [1:0] kw_mid2_fu_528_p3;
wire   [3:0] empty_192_fu_571_p2;
wire   [7:0] tmp8_fu_608_p4;
wire   [14:0] zext_ln192_fu_618_p1;
wire   [14:0] tmp7_fu_599_p4;
wire   [14:0] add_ln192_fu_622_p2;
wire   [10:0] empty_189_fu_561_p2;
wire   [10:0] zext_ln188_6_fu_595_p1;
wire   [10:0] add_ln193_4_fu_633_p2;
wire   [10:0] zext_ln188_fu_591_p1;
wire   [10:0] add_ln193_fu_639_p2;
wire   [13:0] mul_ln193_fu_700_p1;
wire  signed [63:0] sext_ln192_fu_723_p1;
wire   [63:0] acc_14_mid275_fu_709_p3;
wire   [55:0] trunc_ln_fu_732_p4;
wire  signed [56:0] sext_ln198_fu_742_p1;
wire  signed [56:0] sext_ln184_fu_716_p1;
wire   [56:0] add_ln198_fu_746_p2;
wire   [42:0] tmp_23_fu_752_p4;
wire   [0:0] icmp_ln39_fu_762_p2;
wire   [0:0] icmp_ln40_fu_768_p2;
wire   [0:0] or_ln39_fu_786_p2;
wire   [14:0] select_ln39_7_fu_778_p3;
wire   [14:0] trunc_ln41_fu_774_p1;
wire   [4:0] tmp_22_fu_812_p3;
wire   [7:0] p_shl2_fu_805_p3;
wire   [7:0] p_shl3_fu_819_p1;
wire   [7:0] empty_191_fu_823_p2;
wire   [14:0] grp_fu_847_p3;
wire   [14:0] p_cast9_fu_829_p1;
(* use_dsp48 = "no" *) wire   [14:0] add_ln197_fu_837_p2;
wire   [7:0] grp_fu_847_p0;
wire   [6:0] grp_fu_847_p1;
wire   [3:0] grp_fu_847_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [14:0] grp_fu_847_p10;
wire   [14:0] grp_fu_847_p20;
wire   [28:0] mul_ln193_fu_700_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 acc_7_fu_104 = 64'd0;
#0 kw_fu_108 = 2'd0;
#0 kh_fu_112 = 2'd0;
#0 indvar_flatten65_fu_116 = 4'd0;
#0 ow_fu_120 = 4'd0;
#0 indvar_flatten80_fu_124 = 8'd0;
#0 oh_fu_128 = 4'd0;
#0 indvar_flatten105_fu_132 = 11'd0;
#0 c_fu_136 = 7'd0;
#0 indvar_flatten140_fu_140 = 18'd0;
#0 ap_done_reg = 1'b0;
end

Shuffle_Model_mul_15s_14ns_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 29 ))
mul_15s_14ns_29_1_1_U318(
    .din0(b2_dw_w_q0),
    .din1(mul_ln193_fu_700_p1),
    .dout(mul_ln193_fu_700_p2)
);

Shuffle_Model_mac_muladd_8ns_7ns_4ns_15_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 4 ),
    .dout_WIDTH( 15 ))
mac_muladd_8ns_7ns_4ns_15_4_1_U319(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_847_p0),
    .din1(grp_fu_847_p1),
    .din2(grp_fu_847_p2),
    .ce(1'b1),
    .dout(grp_fu_847_p3)
);

Shuffle_Model_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            acc_7_fu_104 <= 64'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            acc_7_fu_104 <= acc_fu_726_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            c_fu_136 <= 7'd0;
        end else if (((icmp_ln183_fu_258_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            c_fu_136 <= select_ln183_5_fu_309_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten105_fu_132 <= 11'd0;
        end else if (((icmp_ln183_fu_258_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten105_fu_132 <= select_ln184_4_fu_393_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten140_fu_140 <= 18'd0;
        end else if (((icmp_ln183_fu_258_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten140_fu_140 <= add_ln183_fu_264_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten65_fu_116 <= 4'd0;
        end else if (((icmp_ln183_fu_258_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten65_fu_116 <= select_ln187_5_fu_365_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten80_fu_124 <= 8'd0;
        end else if (((icmp_ln183_fu_258_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten80_fu_124 <= select_ln185_4_fu_379_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            kh_fu_112 <= 2'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            kh_fu_112 <= select_ln187_fu_536_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            kw_fu_108 <= 2'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            kw_fu_108 <= add_ln188_fu_650_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            oh_fu_128 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            oh_fu_128 <= select_ln184_fu_474_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            ow_fu_120 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            ow_fu_120 <= select_ln185_fu_505_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln183_8_reg_940 <= and_ln183_8_fu_297_p2;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        empty_186_reg_972 <= empty_186_fu_353_p2;
        empty_reg_954 <= empty_fu_317_p2;
        exitcond_flatten67_mid2104_reg_965 <= exitcond_flatten67_mid2104_fu_341_p2;
        icmp_ln184_reg_930 <= icmp_ln184_fu_273_p2;
        not_exitcond_flatten82_mid2139_reg_960 <= not_exitcond_flatten82_mid2139_fu_329_p2;
        select_ln183_5_reg_945 <= select_ln183_5_fu_309_p3;
        xor_ln183_reg_935 <= xor_ln183_fu_279_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        empty_186_reg_972_pp0_iter2_reg <= empty_186_reg_972;
        empty_186_reg_972_pp0_iter3_reg <= empty_186_reg_972_pp0_iter2_reg;
        icmp_ln187_4_reg_1008 <= icmp_ln187_4_fu_662_p2;
        icmp_ln187_4_reg_1008_pp0_iter3_reg <= icmp_ln187_4_reg_1008;
        icmp_ln187_4_reg_1008_pp0_iter4_reg <= icmp_ln187_4_reg_1008_pp0_iter3_reg;
        icmp_ln188_4_reg_1004 <= icmp_ln188_4_fu_656_p2;
        icmp_ln188_4_reg_1004_pp0_iter3_reg <= icmp_ln188_4_reg_1004;
        icmp_ln188_4_reg_1004_pp0_iter4_reg <= icmp_ln188_4_reg_1004_pp0_iter3_reg;
        mul_ln193_reg_1017 <= mul_ln193_fu_700_p2;
        select_ln183_5_reg_945_pp0_iter2_reg <= select_ln183_5_reg_945;
        select_ln184_reg_978 <= select_ln184_fu_474_p3;
        select_ln184_reg_978_pp0_iter3_reg <= select_ln184_reg_978;
        select_ln184_reg_978_pp0_iter4_reg <= select_ln184_reg_978_pp0_iter3_reg;
        select_ln185_reg_984 <= select_ln185_fu_505_p3;
        select_ln185_reg_984_pp0_iter3_reg <= select_ln185_reg_984;
        select_ln39_reg_1027 <= select_ln39_fu_792_p3;
    end
end

always @ (*) begin
    if (((icmp_ln183_fu_258_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        b2_dw_b_ce0_local = 1'b1;
    end else begin
        b2_dw_b_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        b2_dw_w_ce0_local = 1'b1;
    end else begin
        b2_dw_w_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        temp_dw_in_ce0_local = 1'b1;
    end else begin
        temp_dw_in_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        temp_dw_out_ce0_local = 1'b1;
    end else begin
        temp_dw_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln187_4_reg_1008_pp0_iter4_reg == 1'd1) & (icmp_ln188_4_reg_1004_pp0_iter4_reg == 1'd1))) begin
        temp_dw_out_we0_local = 1'b1;
    end else begin
        temp_dw_out_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_14_mid275_fu_709_p3 = ((empty_186_reg_972_pp0_iter3_reg[0:0] == 1'b1) ? 64'd0 : acc_7_fu_104);

assign acc_fu_726_p2 = ($signed(sext_ln192_fu_723_p1) + $signed(acc_14_mid275_fu_709_p3));

assign add_ln183_4_fu_303_p2 = (c_fu_136 + 7'd1);

assign add_ln183_fu_264_p2 = (indvar_flatten140_fu_140 + 18'd1);

assign add_ln184_4_fu_387_p2 = (indvar_flatten105_fu_132 + 11'd1);

assign add_ln184_fu_456_p2 = (select_ln183_fu_438_p3 + 4'd1);

assign add_ln185_4_fu_373_p2 = (indvar_flatten80_fu_124 + 8'd1);

assign add_ln185_fu_481_p2 = (ow_mid287_fu_462_p3 + 4'd1);

assign add_ln187_4_fu_359_p2 = (indvar_flatten65_fu_116 + 4'd1);

assign add_ln187_fu_512_p2 = (kh_mid272_fu_487_p3 + 2'd1);

assign add_ln188_fu_650_p2 = (kw_mid2_fu_528_p3 + 2'd1);

assign add_ln192_fu_622_p2 = (zext_ln192_fu_618_p1 + tmp7_fu_599_p4);

assign add_ln193_4_fu_633_p2 = (empty_189_fu_561_p2 + zext_ln188_6_fu_595_p1);

assign add_ln193_fu_639_p2 = (add_ln193_4_fu_633_p2 + zext_ln188_fu_591_p1);

assign add_ln197_fu_837_p2 = (grp_fu_847_p3 + p_cast9_fu_829_p1);

assign add_ln198_fu_746_p2 = ($signed(sext_ln198_fu_742_p1) + $signed(sext_ln184_fu_716_p1));

assign and_ln183_7_fu_335_p2 = (xor_ln183_fu_279_p2 & icmp_ln187_fu_285_p2);

assign and_ln183_8_fu_297_p2 = (xor_ln183_fu_279_p2 & icmp_ln185_fu_291_p2);

assign and_ln183_fu_451_p2 = (xor_ln183_reg_935 & icmp_ln188_fu_445_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign b2_dw_b_address0 = zext_ln183_fu_688_p1;

assign b2_dw_b_ce0 = b2_dw_b_ce0_local;

assign b2_dw_w_address0 = zext_ln193_4_fu_645_p1;

assign b2_dw_w_ce0 = b2_dw_w_ce0_local;

assign empty_185_fu_347_p2 = (exitcond_flatten67_mid2104_fu_341_p2 | and_ln183_8_fu_297_p2);

assign empty_186_fu_353_p2 = (icmp_ln184_fu_273_p2 | empty_185_fu_347_p2);

assign empty_187_fu_518_p2 = (exitcond_flatten67_mid2104_reg_965 | empty_reg_954);

assign empty_188_fu_522_p2 = (icmp_ln188_mid279_fu_499_p2 | empty_187_fu_518_p2);

assign empty_189_fu_561_p2 = (p_shl4_fu_557_p1 + zext_ln183_9_fu_544_p1);

assign empty_191_fu_823_p2 = (p_shl2_fu_805_p3 - p_shl3_fu_819_p1);

assign empty_192_fu_571_p2 = (zext_ln187_fu_567_p1 + select_ln184_fu_474_p3);

assign empty_193_fu_585_p2 = (p_shl_fu_577_p3 - zext_ln187_fu_567_p1);

assign empty_fu_317_p2 = (icmp_ln184_fu_273_p2 | and_ln183_8_fu_297_p2);

assign exitcond_flatten67_mid2104_fu_341_p2 = (not_exitcond_flatten82_mid2139_fu_329_p2 & and_ln183_7_fu_335_p2);

assign exitcond_flatten82_not_fu_323_p2 = (icmp_ln185_fu_291_p2 ^ 1'd1);

assign grp_fu_847_p0 = 15'd196;

assign grp_fu_847_p1 = grp_fu_847_p10;

assign grp_fu_847_p10 = select_ln183_5_reg_945;

assign grp_fu_847_p2 = grp_fu_847_p20;

assign grp_fu_847_p20 = select_ln185_reg_984_pp0_iter3_reg;

assign icmp_ln183_fu_258_p2 = ((indvar_flatten140_fu_140 == 18'd204624) ? 1'b1 : 1'b0);

assign icmp_ln184_fu_273_p2 = ((indvar_flatten105_fu_132 == 11'd1764) ? 1'b1 : 1'b0);

assign icmp_ln185_fu_291_p2 = ((indvar_flatten80_fu_124 == 8'd126) ? 1'b1 : 1'b0);

assign icmp_ln187_4_fu_662_p2 = ((select_ln187_fu_536_p3 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln187_fu_285_p2 = ((indvar_flatten65_fu_116 == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln188_4_fu_656_p2 = ((add_ln188_fu_650_p2 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln188_fu_445_p2 = ((kw_fu_108 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln188_mid2100_fu_469_p2 = (not_exitcond_flatten82_mid2139_reg_960 & and_ln183_fu_451_p2);

assign icmp_ln188_mid279_fu_499_p2 = (not_exitcond_flatten67_mid2104_fu_494_p2 & icmp_ln188_mid2100_fu_469_p2);

assign icmp_ln39_fu_762_p2 = (($signed(tmp_23_fu_752_p4) > $signed(43'd0)) ? 1'b1 : 1'b0);

assign icmp_ln40_fu_768_p2 = (($signed(add_ln198_fu_746_p2) < $signed(57'd144115188075839488)) ? 1'b1 : 1'b0);

assign kh_mid272_fu_487_p3 = ((empty_186_reg_972[0:0] == 1'b1) ? 2'd0 : kh_fu_112);

assign kw_mid2_fu_528_p3 = ((empty_188_fu_522_p2[0:0] == 1'b1) ? 2'd0 : kw_fu_108);

assign mul_ln193_fu_700_p1 = mul_ln193_fu_700_p10;

assign mul_ln193_fu_700_p10 = temp_dw_in_q0;

assign not_exitcond_flatten67_mid2104_fu_494_p2 = (exitcond_flatten67_mid2104_reg_965 ^ 1'd1);

assign not_exitcond_flatten82_mid2139_fu_329_p2 = (icmp_ln184_fu_273_p2 | exitcond_flatten82_not_fu_323_p2);

assign or_ln39_fu_786_p2 = (icmp_ln40_fu_768_p2 | icmp_ln39_fu_762_p2);

assign ow_mid287_fu_462_p3 = ((empty_reg_954[0:0] == 1'b1) ? 4'd0 : ow_fu_120);

assign p_cast9_fu_829_p1 = empty_191_fu_823_p2;

assign p_shl2_fu_805_p3 = {{select_ln184_reg_978_pp0_iter4_reg}, {4'd0}};

assign p_shl3_fu_819_p1 = tmp_22_fu_812_p3;

assign p_shl4_fu_557_p1 = tmp_1_fu_550_p3;

assign p_shl_fu_577_p3 = {{select_ln187_fu_536_p3}, {2'd0}};

assign select_ln183_5_fu_309_p3 = ((icmp_ln184_fu_273_p2[0:0] == 1'b1) ? add_ln183_4_fu_303_p2 : c_fu_136);

assign select_ln183_fu_438_p3 = ((icmp_ln184_reg_930[0:0] == 1'b1) ? 4'd0 : oh_fu_128);

assign select_ln184_4_fu_393_p3 = ((icmp_ln184_fu_273_p2[0:0] == 1'b1) ? 11'd1 : add_ln184_4_fu_387_p2);

assign select_ln184_fu_474_p3 = ((and_ln183_8_reg_940[0:0] == 1'b1) ? add_ln184_fu_456_p2 : select_ln183_fu_438_p3);

assign select_ln185_4_fu_379_p3 = ((empty_fu_317_p2[0:0] == 1'b1) ? 8'd1 : add_ln185_4_fu_373_p2);

assign select_ln185_fu_505_p3 = ((exitcond_flatten67_mid2104_reg_965[0:0] == 1'b1) ? add_ln185_fu_481_p2 : ow_mid287_fu_462_p3);

assign select_ln187_5_fu_365_p3 = ((empty_186_fu_353_p2[0:0] == 1'b1) ? 4'd1 : add_ln187_4_fu_359_p2);

assign select_ln187_fu_536_p3 = ((icmp_ln188_mid279_fu_499_p2[0:0] == 1'b1) ? add_ln187_fu_512_p2 : kh_mid272_fu_487_p3);

assign select_ln39_7_fu_778_p3 = ((icmp_ln39_fu_762_p2[0:0] == 1'b1) ? 15'd16383 : 15'd16384);

assign select_ln39_fu_792_p3 = ((or_ln39_fu_786_p2[0:0] == 1'b1) ? select_ln39_7_fu_778_p3 : trunc_ln41_fu_774_p1);

assign sext_ln184_fu_716_p1 = $signed(b2_dw_b_q0);

assign sext_ln192_fu_723_p1 = $signed(mul_ln193_reg_1017);

assign sext_ln197_fu_833_p1 = $signed(select_ln39_reg_1027);

assign sext_ln198_fu_742_p1 = $signed(trunc_ln_fu_732_p4);

assign temp_dw_in_address0 = zext_ln192_4_fu_628_p1;

assign temp_dw_in_ce0 = temp_dw_in_ce0_local;

assign temp_dw_out_address0 = zext_ln197_fu_842_p1;

assign temp_dw_out_ce0 = temp_dw_out_ce0_local;

assign temp_dw_out_d0 = sext_ln197_fu_833_p1;

assign temp_dw_out_we0 = temp_dw_out_we0_local;

assign tmp7_fu_599_p4 = {{{select_ln183_5_reg_945}, {4'd0}}, {select_ln185_fu_505_p3}};

assign tmp8_fu_608_p4 = {{{empty_192_fu_571_p2}, {2'd0}}, {kw_mid2_fu_528_p3}};

assign tmp_1_fu_550_p3 = {{select_ln183_5_reg_945}, {3'd0}};

assign tmp_22_fu_812_p3 = {{select_ln184_reg_978_pp0_iter4_reg}, {1'd0}};

assign tmp_23_fu_752_p4 = {{add_ln198_fu_746_p2[56:14]}};

assign trunc_ln41_fu_774_p1 = add_ln198_fu_746_p2[14:0];

assign trunc_ln_fu_732_p4 = {{acc_fu_726_p2[63:8]}};

assign xor_ln183_fu_279_p2 = (icmp_ln184_fu_273_p2 ^ 1'd1);

assign zext_ln183_9_fu_544_p1 = select_ln183_5_reg_945;

assign zext_ln183_fu_688_p1 = select_ln183_5_reg_945_pp0_iter2_reg;

assign zext_ln187_fu_567_p1 = select_ln187_fu_536_p3;

assign zext_ln188_6_fu_595_p1 = kw_mid2_fu_528_p3;

assign zext_ln188_fu_591_p1 = empty_193_fu_585_p2;

assign zext_ln192_4_fu_628_p1 = add_ln192_fu_622_p2;

assign zext_ln192_fu_618_p1 = tmp8_fu_608_p4;

assign zext_ln193_4_fu_645_p1 = add_ln193_fu_639_p2;

assign zext_ln197_fu_842_p1 = add_ln197_fu_837_p2;

endmodule //Shuffle_Model_shuffle_block_s1_3_Pipeline_VITIS_LOOP_183_1_VITIS_LOOP_184_2_VITIS_LOOP_185_3_V
