// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Shuffle_Model_shuffle_block_s1_Pipeline_VITIS_LOOP_290_4_VITIS_LOOP_291_5_VITIS_LOOP_292_6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sm2_address0,
        sm2_ce0,
        sm2_q0,
        b2_in_1_address0,
        b2_in_1_ce0,
        b2_in_1_we0,
        b2_in_1_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [18:0] sm2_address0;
output   sm2_ce0;
input  [15:0] sm2_q0;
output  [15:0] b2_in_1_address0;
output   b2_in_1_ce0;
output   b2_in_1_we0;
output  [15:0] b2_in_1_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln290_fu_145_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln291_fu_163_p2;
reg   [0:0] icmp_ln291_reg_475;
reg   [0:0] icmp_ln291_reg_475_pp0_iter1_reg;
wire   [15:0] zext_ln290_fu_183_p1;
wire   [4:0] w_i_19_mid2_fu_270_p3;
reg   [4:0] w_i_19_mid2_reg_489;
wire   [4:0] select_ln291_fu_292_p3;
reg   [4:0] select_ln291_reg_494;
(* use_dsp48 = "no" *) wire   [15:0] add_ln293_fu_409_p2;
reg   [15:0] add_ln293_reg_515;
wire   [63:0] zext_ln294_2_fu_404_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln293_fu_414_p1;
reg   [4:0] w_i_fu_70;
wire   [4:0] add_ln294_fu_334_p2;
wire    ap_loop_init;
reg   [4:0] h_fu_74;
reg   [9:0] indvar_flatten21_fu_78;
wire   [9:0] select_ln291_1_fu_193_p3;
reg   [9:0] ap_sig_allocacmp_indvar_flatten21_load;
reg   [5:0] c_fu_82;
wire   [5:0] select_ln290_2_fu_175_p3;
reg   [5:0] ap_sig_allocacmp_c_load;
reg   [15:0] indvar_flatten36_fu_86;
wire   [15:0] add_ln290_fu_151_p2;
reg   [15:0] ap_sig_allocacmp_indvar_flatten36_load;
reg    sm2_ce0_local;
reg    b2_in_1_we0_local;
reg    b2_in_1_ce0_local;
wire   [5:0] add_ln290_1_fu_169_p2;
wire   [9:0] add_ln291_fu_187_p2;
wire   [4:0] indvars_iv_next92200_fu_229_p2;
wire   [0:0] icmp_ln292_fu_247_p2;
wire   [0:0] xor_ln290_fu_242_p2;
wire   [4:0] select_ln290_fu_222_p3;
wire   [0:0] and_ln290_fu_253_p2;
wire   [0:0] empty_fu_265_p2;
wire   [4:0] indvars_iv_next92_mid1_fu_278_p2;
wire   [4:0] select_ln290_1_fu_235_p3;
wire   [4:0] indvars_iv_next92_dup_fu_259_p2;
wire   [4:0] indvars_iv_next92_mid2_fu_284_p3;
wire   [5:0] tmp_1_fu_308_p3;
wire   [9:0] p_shl2_fu_300_p3;
wire   [9:0] p_shl3_fu_316_p1;
wire   [9:0] empty_90_fu_320_p2;
wire   [6:0] tmp_13_fu_357_p3;
wire   [9:0] p_shl_fu_350_p3;
wire   [9:0] p_shl1_fu_364_p1;
wire   [9:0] empty_91_fu_368_p2;
wire   [15:0] grp_fu_418_p3;
wire   [14:0] zext_ln292_2_fu_378_p1;
wire   [14:0] add_ln294_2_fu_384_p2;
wire  signed [15:0] sext_ln294_fu_390_p1;
wire   [16:0] zext_ln294_1_fu_394_p1;
wire   [16:0] zext_ln294_fu_381_p1;
wire   [16:0] add_ln294_3_fu_398_p2;
wire   [15:0] grp_fu_427_p3;
wire   [15:0] zext_ln292_fu_374_p1;
wire   [9:0] grp_fu_418_p0;
wire   [5:0] grp_fu_418_p1;
wire   [9:0] grp_fu_418_p2;
wire   [9:0] grp_fu_427_p0;
wire   [5:0] grp_fu_427_p1;
wire   [4:0] grp_fu_427_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [15:0] grp_fu_418_p20;
wire   [15:0] grp_fu_427_p20;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 w_i_fu_70 = 5'd0;
#0 h_fu_74 = 5'd0;
#0 indvar_flatten21_fu_78 = 10'd0;
#0 c_fu_82 = 6'd0;
#0 indvar_flatten36_fu_86 = 16'd0;
#0 ap_done_reg = 1'b0;
end

Shuffle_Model_mac_muladd_10ns_6ns_10ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 10 ),
    .dout_WIDTH( 16 ))
mac_muladd_10ns_6ns_10ns_16_4_1_U122(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_418_p0),
    .din1(grp_fu_418_p1),
    .din2(grp_fu_418_p2),
    .ce(1'b1),
    .dout(grp_fu_418_p3)
);

Shuffle_Model_mac_muladd_10ns_6ns_5ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 5 ),
    .dout_WIDTH( 16 ))
mac_muladd_10ns_6ns_5ns_16_4_1_U123(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_427_p0),
    .din1(grp_fu_427_p1),
    .din2(grp_fu_427_p2),
    .ce(1'b1),
    .dout(grp_fu_427_p3)
);

Shuffle_Model_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln290_fu_145_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            c_fu_82 <= select_ln290_2_fu_175_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_82 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            h_fu_74 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            h_fu_74 <= select_ln291_fu_292_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln290_fu_145_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten21_fu_78 <= select_ln291_1_fu_193_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten21_fu_78 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln290_fu_145_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten36_fu_86 <= add_ln290_fu_151_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten36_fu_86 <= 16'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            w_i_fu_70 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            w_i_fu_70 <= add_ln294_fu_334_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln293_reg_515 <= add_ln293_fu_409_p2;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        select_ln291_reg_494 <= select_ln291_fu_292_p3;
        w_i_19_mid2_reg_489 <= w_i_19_mid2_fu_270_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln291_reg_475 <= icmp_ln291_fu_163_p2;
        icmp_ln291_reg_475_pp0_iter1_reg <= icmp_ln291_reg_475;
    end
end

always @ (*) begin
    if (((icmp_ln290_fu_145_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_c_load = 6'd0;
    end else begin
        ap_sig_allocacmp_c_load = c_fu_82;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten21_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten21_load = indvar_flatten21_fu_78;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten36_load = 16'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten36_load = indvar_flatten36_fu_86;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        b2_in_1_ce0_local = 1'b1;
    end else begin
        b2_in_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        b2_in_1_we0_local = 1'b1;
    end else begin
        b2_in_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        sm2_ce0_local = 1'b1;
    end else begin
        sm2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln290_1_fu_169_p2 = (ap_sig_allocacmp_c_load + 6'd1);

assign add_ln290_fu_151_p2 = (ap_sig_allocacmp_indvar_flatten36_load + 16'd1);

assign add_ln291_fu_187_p2 = (ap_sig_allocacmp_indvar_flatten21_load + 10'd1);

assign add_ln293_fu_409_p2 = (grp_fu_427_p3 + zext_ln292_fu_374_p1);

assign add_ln294_2_fu_384_p2 = ($signed(zext_ln292_2_fu_378_p1) + $signed(15'd19433));

assign add_ln294_3_fu_398_p2 = (zext_ln294_1_fu_394_p1 + zext_ln294_fu_381_p1);

assign add_ln294_fu_334_p2 = (w_i_19_mid2_fu_270_p3 + 5'd1);

assign and_ln290_fu_253_p2 = (xor_ln290_fu_242_p2 & icmp_ln292_fu_247_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign b2_in_1_address0 = zext_ln293_fu_414_p1;

assign b2_in_1_ce0 = b2_in_1_ce0_local;

assign b2_in_1_d0 = sm2_q0;

assign b2_in_1_we0 = b2_in_1_we0_local;

assign empty_90_fu_320_p2 = (p_shl2_fu_300_p3 - p_shl3_fu_316_p1);

assign empty_91_fu_368_p2 = (p_shl_fu_350_p3 - p_shl1_fu_364_p1);

assign empty_fu_265_p2 = (icmp_ln291_reg_475_pp0_iter1_reg | and_ln290_fu_253_p2);

assign grp_fu_418_p0 = 16'd900;

assign grp_fu_418_p1 = zext_ln290_fu_183_p1;

assign grp_fu_418_p2 = grp_fu_418_p20;

assign grp_fu_418_p20 = empty_90_fu_320_p2;

assign grp_fu_427_p0 = 16'd784;

assign grp_fu_427_p1 = zext_ln290_fu_183_p1;

assign grp_fu_427_p2 = grp_fu_427_p20;

assign grp_fu_427_p20 = w_i_19_mid2_fu_270_p3;

assign icmp_ln290_fu_145_p2 = ((ap_sig_allocacmp_indvar_flatten36_load == 16'd45472) ? 1'b1 : 1'b0);

assign icmp_ln291_fu_163_p2 = ((ap_sig_allocacmp_indvar_flatten21_load == 10'd784) ? 1'b1 : 1'b0);

assign icmp_ln292_fu_247_p2 = ((w_i_fu_70 == 5'd28) ? 1'b1 : 1'b0);

assign indvars_iv_next92200_fu_229_p2 = (h_fu_74 + 5'd1);

assign indvars_iv_next92_dup_fu_259_p2 = (select_ln290_fu_222_p3 + 5'd1);

assign indvars_iv_next92_mid1_fu_278_p2 = (select_ln290_fu_222_p3 + 5'd2);

assign indvars_iv_next92_mid2_fu_284_p3 = ((and_ln290_fu_253_p2[0:0] == 1'b1) ? indvars_iv_next92_mid1_fu_278_p2 : select_ln290_1_fu_235_p3);

assign p_shl1_fu_364_p1 = tmp_13_fu_357_p3;

assign p_shl2_fu_300_p3 = {{indvars_iv_next92_mid2_fu_284_p3}, {5'd0}};

assign p_shl3_fu_316_p1 = tmp_1_fu_308_p3;

assign p_shl_fu_350_p3 = {{select_ln291_reg_494}, {5'd0}};

assign select_ln290_1_fu_235_p3 = ((icmp_ln291_reg_475_pp0_iter1_reg[0:0] == 1'b1) ? 5'd1 : indvars_iv_next92200_fu_229_p2);

assign select_ln290_2_fu_175_p3 = ((icmp_ln291_fu_163_p2[0:0] == 1'b1) ? add_ln290_1_fu_169_p2 : ap_sig_allocacmp_c_load);

assign select_ln290_fu_222_p3 = ((icmp_ln291_reg_475_pp0_iter1_reg[0:0] == 1'b1) ? 5'd0 : h_fu_74);

assign select_ln291_1_fu_193_p3 = ((icmp_ln291_fu_163_p2[0:0] == 1'b1) ? 10'd1 : add_ln291_fu_187_p2);

assign select_ln291_fu_292_p3 = ((and_ln290_fu_253_p2[0:0] == 1'b1) ? indvars_iv_next92_dup_fu_259_p2 : select_ln290_fu_222_p3);

assign sext_ln294_fu_390_p1 = $signed(add_ln294_2_fu_384_p2);

assign sm2_address0 = zext_ln294_2_fu_404_p1;

assign sm2_ce0 = sm2_ce0_local;

assign tmp_13_fu_357_p3 = {{select_ln291_reg_494}, {2'd0}};

assign tmp_1_fu_308_p3 = {{indvars_iv_next92_mid2_fu_284_p3}, {1'd0}};

assign w_i_19_mid2_fu_270_p3 = ((empty_fu_265_p2[0:0] == 1'b1) ? 5'd0 : w_i_fu_70);

assign xor_ln290_fu_242_p2 = (icmp_ln291_reg_475_pp0_iter1_reg ^ 1'd1);

assign zext_ln290_fu_183_p1 = select_ln290_2_fu_175_p3;

assign zext_ln292_2_fu_378_p1 = w_i_19_mid2_reg_489;

assign zext_ln292_fu_374_p1 = empty_91_fu_368_p2;

assign zext_ln293_fu_414_p1 = add_ln293_reg_515;

assign zext_ln294_1_fu_394_p1 = $unsigned(sext_ln294_fu_390_p1);

assign zext_ln294_2_fu_404_p1 = add_ln294_3_fu_398_p2;

assign zext_ln294_fu_381_p1 = grp_fu_418_p3;

endmodule //Shuffle_Model_shuffle_block_s1_Pipeline_VITIS_LOOP_290_4_VITIS_LOOP_291_5_VITIS_LOOP_292_6
