// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Shuffle_Model_shuffle_block_s2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sm1_address0,
        sm1_ce0,
        sm1_q0,
        sm2_address0,
        sm2_ce0,
        sm2_we0,
        sm2_d0,
        sm3_address0,
        sm3_ce0,
        sm3_we0,
        sm3_d0,
        sm3_q0,
        b1_dw_out_address0,
        b1_dw_out_ce0,
        b1_dw_out_we0,
        b1_dw_out_d0,
        b1_dw_out_q0,
        b1_pw_out_address0,
        b1_pw_out_ce0,
        b1_pw_out_we0,
        b1_pw_out_d0,
        b1_pw_out_q0,
        b2_in_address0,
        b2_in_ce0,
        b2_in_we0,
        b2_in_d0,
        b2_in_q0,
        b2_dw_out_address0,
        b2_dw_out_ce0,
        b2_dw_out_we0,
        b2_dw_out_d0,
        b2_dw_out_q0,
        b2_pw2_out_address0,
        b2_pw2_out_ce0,
        b2_pw2_out_we0,
        b2_pw2_out_d0,
        b2_pw2_out_q0,
        concat_address0,
        concat_ce0,
        concat_we0,
        concat_d0,
        concat_q0,
        concat_address1,
        concat_ce1,
        concat_we1,
        concat_d1,
        tmp_address0,
        tmp_ce0,
        tmp_we0,
        tmp_d0,
        tmp_q0
);

parameter    ap_ST_fsm_state1 = 18'd1;
parameter    ap_ST_fsm_state2 = 18'd2;
parameter    ap_ST_fsm_state3 = 18'd4;
parameter    ap_ST_fsm_state4 = 18'd8;
parameter    ap_ST_fsm_state5 = 18'd16;
parameter    ap_ST_fsm_state6 = 18'd32;
parameter    ap_ST_fsm_state7 = 18'd64;
parameter    ap_ST_fsm_state8 = 18'd128;
parameter    ap_ST_fsm_state9 = 18'd256;
parameter    ap_ST_fsm_state10 = 18'd512;
parameter    ap_ST_fsm_state11 = 18'd1024;
parameter    ap_ST_fsm_state12 = 18'd2048;
parameter    ap_ST_fsm_state13 = 18'd4096;
parameter    ap_ST_fsm_state14 = 18'd8192;
parameter    ap_ST_fsm_state15 = 18'd16384;
parameter    ap_ST_fsm_state16 = 18'd32768;
parameter    ap_ST_fsm_state17 = 18'd65536;
parameter    ap_ST_fsm_state18 = 18'd131072;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [17:0] sm1_address0;
output   sm1_ce0;
input  [15:0] sm1_q0;
output  [18:0] sm2_address0;
output   sm2_ce0;
output   sm2_we0;
output  [15:0] sm2_d0;
output  [17:0] sm3_address0;
output   sm3_ce0;
output   sm3_we0;
output  [15:0] sm3_d0;
input  [15:0] sm3_q0;
output  [14:0] b1_dw_out_address0;
output   b1_dw_out_ce0;
output   b1_dw_out_we0;
output  [14:0] b1_dw_out_d0;
input  [14:0] b1_dw_out_q0;
output  [14:0] b1_pw_out_address0;
output   b1_pw_out_ce0;
output   b1_pw_out_we0;
output  [13:0] b1_pw_out_d0;
input  [13:0] b1_pw_out_q0;
output  [16:0] b2_in_address0;
output   b2_in_ce0;
output   b2_in_we0;
output  [15:0] b2_in_d0;
input  [15:0] b2_in_q0;
output  [14:0] b2_dw_out_address0;
output   b2_dw_out_ce0;
output   b2_dw_out_we0;
output  [14:0] b2_dw_out_d0;
input  [14:0] b2_dw_out_q0;
output  [14:0] b2_pw2_out_address0;
output   b2_pw2_out_ce0;
output   b2_pw2_out_we0;
output  [13:0] b2_pw2_out_d0;
input  [13:0] b2_pw2_out_q0;
output  [16:0] concat_address0;
output   concat_ce0;
output   concat_we0;
output  [15:0] concat_d0;
input  [15:0] concat_q0;
output  [16:0] concat_address1;
output   concat_ce1;
output   concat_we1;
output  [15:0] concat_d1;
output  [16:0] tmp_address0;
output   tmp_ce0;
output   tmp_we0;
output  [15:0] tmp_d0;
input  [15:0] tmp_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[17:0] sm1_address0;
reg sm1_ce0;
reg[18:0] sm2_address0;
reg sm2_ce0;
reg sm2_we0;
reg[15:0] sm2_d0;
reg[17:0] sm3_address0;
reg sm3_ce0;
reg sm3_we0;
reg[15:0] sm3_d0;
reg[14:0] b1_dw_out_address0;
reg b1_dw_out_ce0;
reg b1_dw_out_we0;
reg[14:0] b1_pw_out_address0;
reg b1_pw_out_ce0;
reg b1_pw_out_we0;
reg[16:0] b2_in_address0;
reg b2_in_ce0;
reg b2_in_we0;
reg[14:0] b2_dw_out_address0;
reg b2_dw_out_ce0;
reg b2_dw_out_we0;
reg[14:0] b2_pw2_out_address0;
reg b2_pw2_out_ce0;
reg b2_pw2_out_we0;
reg[16:0] concat_address0;
reg concat_ce0;
reg concat_we0;
reg[15:0] concat_d0;
reg concat_ce1;
reg concat_we1;
reg[16:0] tmp_address0;
reg tmp_ce0;
reg tmp_we0;

(* fsm_encoding = "none" *) reg   [17:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_dw_conv3x3_15_fu_74_ap_start;
wire    grp_dw_conv3x3_15_fu_74_ap_done;
wire    grp_dw_conv3x3_15_fu_74_ap_idle;
wire    grp_dw_conv3x3_15_fu_74_ap_ready;
wire   [17:0] grp_dw_conv3x3_15_fu_74_sm1_address0;
wire    grp_dw_conv3x3_15_fu_74_sm1_ce0;
wire   [14:0] grp_dw_conv3x3_15_fu_74_b1_dw_out_address0;
wire    grp_dw_conv3x3_15_fu_74_b1_dw_out_ce0;
wire    grp_dw_conv3x3_15_fu_74_b1_dw_out_we0;
wire   [14:0] grp_dw_conv3x3_15_fu_74_b1_dw_out_d0;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_403_4_fu_86_ap_start;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_403_4_fu_86_ap_done;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_403_4_fu_86_ap_idle;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_403_4_fu_86_ap_ready;
wire   [17:0] grp_shuffle_block_s2_Pipeline_VITIS_LOOP_403_4_fu_86_sm3_address0;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_403_4_fu_86_sm3_ce0;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_403_4_fu_86_sm3_we0;
wire   [15:0] grp_shuffle_block_s2_Pipeline_VITIS_LOOP_403_4_fu_86_sm3_d0;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_50_1_fu_92_ap_start;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_50_1_fu_92_ap_done;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_50_1_fu_92_ap_idle;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_50_1_fu_92_ap_ready;
wire   [18:0] grp_shuffle_block_s2_Pipeline_VITIS_LOOP_50_1_fu_92_sm2_address0;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_50_1_fu_92_sm2_ce0;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_50_1_fu_92_sm2_we0;
wire   [15:0] grp_shuffle_block_s2_Pipeline_VITIS_LOOP_50_1_fu_92_sm2_d0;
wire    grp_conv1x1_16_fu_98_ap_start;
wire    grp_conv1x1_16_fu_98_ap_done;
wire    grp_conv1x1_16_fu_98_ap_idle;
wire    grp_conv1x1_16_fu_98_ap_ready;
wire   [14:0] grp_conv1x1_16_fu_98_b1_pw_out_address0;
wire    grp_conv1x1_16_fu_98_b1_pw_out_ce0;
wire    grp_conv1x1_16_fu_98_b1_pw_out_we0;
wire   [13:0] grp_conv1x1_16_fu_98_b1_pw_out_d0;
wire   [14:0] grp_conv1x1_16_fu_98_b1_dw_out_address0;
wire    grp_conv1x1_16_fu_98_b1_dw_out_ce0;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_385_1_VITIS_LOOP_386_2_VITIS_LOOP_387_3_fu_110_ap_start;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_385_1_VITIS_LOOP_386_2_VITIS_LOOP_387_3_fu_110_ap_done;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_385_1_VITIS_LOOP_386_2_VITIS_LOOP_387_3_fu_110_ap_idle;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_385_1_VITIS_LOOP_386_2_VITIS_LOOP_387_3_fu_110_ap_ready;
wire   [17:0] grp_shuffle_block_s2_Pipeline_VITIS_LOOP_385_1_VITIS_LOOP_386_2_VITIS_LOOP_387_3_fu_110_sm1_address0;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_385_1_VITIS_LOOP_386_2_VITIS_LOOP_387_3_fu_110_sm1_ce0;
wire   [16:0] grp_shuffle_block_s2_Pipeline_VITIS_LOOP_385_1_VITIS_LOOP_386_2_VITIS_LOOP_387_3_fu_110_b2_in_address0;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_385_1_VITIS_LOOP_386_2_VITIS_LOOP_387_3_fu_110_b2_in_ce0;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_385_1_VITIS_LOOP_386_2_VITIS_LOOP_387_3_fu_110_b2_in_we0;
wire   [15:0] grp_shuffle_block_s2_Pipeline_VITIS_LOOP_385_1_VITIS_LOOP_386_2_VITIS_LOOP_387_3_fu_110_b2_in_d0;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_7_VIT_fu_118_ap_start;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_7_VIT_fu_118_ap_done;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_7_VIT_fu_118_ap_idle;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_7_VIT_fu_118_ap_ready;
wire   [17:0] grp_shuffle_block_s2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_7_VIT_fu_118_sm3_address0;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_7_VIT_fu_118_sm3_ce0;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_7_VIT_fu_118_sm3_we0;
wire   [15:0] grp_shuffle_block_s2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_7_VIT_fu_118_sm3_d0;
wire   [16:0] grp_shuffle_block_s2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_7_VIT_fu_118_b2_in_address0;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_7_VIT_fu_118_b2_in_ce0;
wire    grp_dw_conv3x3_17_fu_130_ap_start;
wire    grp_dw_conv3x3_17_fu_130_ap_done;
wire    grp_dw_conv3x3_17_fu_130_ap_idle;
wire    grp_dw_conv3x3_17_fu_130_ap_ready;
wire   [17:0] grp_dw_conv3x3_17_fu_130_sm3_address0;
wire    grp_dw_conv3x3_17_fu_130_sm3_ce0;
wire   [14:0] grp_dw_conv3x3_17_fu_130_b2_dw_out_address0;
wire    grp_dw_conv3x3_17_fu_130_b2_dw_out_ce0;
wire    grp_dw_conv3x3_17_fu_130_b2_dw_out_we0;
wire   [14:0] grp_dw_conv3x3_17_fu_130_b2_dw_out_d0;
wire    grp_conv1x1_18_fu_142_ap_start;
wire    grp_conv1x1_18_fu_142_ap_done;
wire    grp_conv1x1_18_fu_142_ap_idle;
wire    grp_conv1x1_18_fu_142_ap_ready;
wire   [14:0] grp_conv1x1_18_fu_142_b2_pw2_out_address0;
wire    grp_conv1x1_18_fu_142_b2_pw2_out_ce0;
wire    grp_conv1x1_18_fu_142_b2_pw2_out_we0;
wire   [13:0] grp_conv1x1_18_fu_142_b2_pw2_out_d0;
wire   [14:0] grp_conv1x1_18_fu_142_b2_dw_out_address0;
wire    grp_conv1x1_18_fu_142_b2_dw_out_ce0;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_ap_start;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_ap_done;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_ap_idle;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_ap_ready;
wire   [14:0] grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_b1_pw_out_address0;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_b1_pw_out_ce0;
wire   [16:0] grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_concat_address0;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_concat_ce0;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_concat_we0;
wire   [15:0] grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_concat_d0;
wire   [16:0] grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_concat_address1;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_concat_ce1;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_concat_we1;
wire   [15:0] grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_concat_d1;
wire   [14:0] grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_b2_pw2_out_address0;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_b2_pw2_out_ce0;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_221_1_fu_164_ap_start;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_221_1_fu_164_ap_done;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_221_1_fu_164_ap_idle;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_221_1_fu_164_ap_ready;
wire   [16:0] grp_shuffle_block_s2_Pipeline_VITIS_LOOP_221_1_fu_164_concat_address0;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_221_1_fu_164_concat_ce0;
wire   [16:0] grp_shuffle_block_s2_Pipeline_VITIS_LOOP_221_1_fu_164_tmp_address0;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_221_1_fu_164_tmp_ce0;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_221_1_fu_164_tmp_we0;
wire   [15:0] grp_shuffle_block_s2_Pipeline_VITIS_LOOP_221_1_fu_164_tmp_d0;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_223_2_VITIS_LOOP_226_3_fu_172_ap_start;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_223_2_VITIS_LOOP_226_3_fu_172_ap_done;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_223_2_VITIS_LOOP_226_3_fu_172_ap_idle;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_223_2_VITIS_LOOP_226_3_fu_172_ap_ready;
wire   [16:0] grp_shuffle_block_s2_Pipeline_VITIS_LOOP_223_2_VITIS_LOOP_226_3_fu_172_tmp_address0;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_223_2_VITIS_LOOP_226_3_fu_172_tmp_ce0;
wire   [16:0] grp_shuffle_block_s2_Pipeline_VITIS_LOOP_223_2_VITIS_LOOP_226_3_fu_172_concat_address0;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_223_2_VITIS_LOOP_226_3_fu_172_concat_ce0;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_223_2_VITIS_LOOP_226_3_fu_172_concat_we0;
wire   [15:0] grp_shuffle_block_s2_Pipeline_VITIS_LOOP_223_2_VITIS_LOOP_226_3_fu_172_concat_d0;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_447_11_VITIS_LOOP_448_12_VITIS_LOOP_449_13_fu_180_ap_start;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_447_11_VITIS_LOOP_448_12_VITIS_LOOP_449_13_fu_180_ap_done;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_447_11_VITIS_LOOP_448_12_VITIS_LOOP_449_13_fu_180_ap_idle;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_447_11_VITIS_LOOP_448_12_VITIS_LOOP_449_13_fu_180_ap_ready;
wire   [18:0] grp_shuffle_block_s2_Pipeline_VITIS_LOOP_447_11_VITIS_LOOP_448_12_VITIS_LOOP_449_13_fu_180_sm2_address0;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_447_11_VITIS_LOOP_448_12_VITIS_LOOP_449_13_fu_180_sm2_ce0;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_447_11_VITIS_LOOP_448_12_VITIS_LOOP_449_13_fu_180_sm2_we0;
wire   [15:0] grp_shuffle_block_s2_Pipeline_VITIS_LOOP_447_11_VITIS_LOOP_448_12_VITIS_LOOP_449_13_fu_180_sm2_d0;
wire   [16:0] grp_shuffle_block_s2_Pipeline_VITIS_LOOP_447_11_VITIS_LOOP_448_12_VITIS_LOOP_449_13_fu_180_concat_address0;
wire    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_447_11_VITIS_LOOP_448_12_VITIS_LOOP_449_13_fu_180_concat_ce0;
reg    grp_dw_conv3x3_15_fu_74_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_403_4_fu_86_ap_start_reg;
reg    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_50_1_fu_92_ap_start_reg;
reg    grp_conv1x1_16_fu_98_ap_start_reg;
reg   [17:0] ap_NS_fsm;
wire    ap_NS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_385_1_VITIS_LOOP_386_2_VITIS_LOOP_387_3_fu_110_ap_start_reg;
reg    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_7_VIT_fu_118_ap_start_reg;
wire    ap_NS_fsm_state5;
wire    ap_CS_fsm_state6;
reg    grp_dw_conv3x3_17_fu_130_ap_start_reg;
wire    ap_NS_fsm_state7;
wire    ap_CS_fsm_state8;
reg    grp_conv1x1_18_fu_142_ap_start_reg;
wire    ap_NS_fsm_state9;
wire    ap_CS_fsm_state10;
reg    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_ap_start_reg;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
reg    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_221_1_fu_164_ap_start_reg;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
reg    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_223_2_VITIS_LOOP_226_3_fu_172_ap_start_reg;
wire    ap_NS_fsm_state15;
wire    ap_CS_fsm_state16;
reg    grp_shuffle_block_s2_Pipeline_VITIS_LOOP_447_11_VITIS_LOOP_448_12_VITIS_LOOP_449_13_fu_180_ap_start_reg;
wire    ap_NS_fsm_state17;
wire    ap_CS_fsm_state18;
reg    ap_ST_fsm_state1_blk;
reg    ap_block_state2_on_subcall_done;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_block_state4_on_subcall_done;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
reg    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
reg    ap_ST_fsm_state18_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 18'd1;
#0 grp_dw_conv3x3_15_fu_74_ap_start_reg = 1'b0;
#0 grp_shuffle_block_s2_Pipeline_VITIS_LOOP_403_4_fu_86_ap_start_reg = 1'b0;
#0 grp_shuffle_block_s2_Pipeline_VITIS_LOOP_50_1_fu_92_ap_start_reg = 1'b0;
#0 grp_conv1x1_16_fu_98_ap_start_reg = 1'b0;
#0 grp_shuffle_block_s2_Pipeline_VITIS_LOOP_385_1_VITIS_LOOP_386_2_VITIS_LOOP_387_3_fu_110_ap_start_reg = 1'b0;
#0 grp_shuffle_block_s2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_7_VIT_fu_118_ap_start_reg = 1'b0;
#0 grp_dw_conv3x3_17_fu_130_ap_start_reg = 1'b0;
#0 grp_conv1x1_18_fu_142_ap_start_reg = 1'b0;
#0 grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_ap_start_reg = 1'b0;
#0 grp_shuffle_block_s2_Pipeline_VITIS_LOOP_221_1_fu_164_ap_start_reg = 1'b0;
#0 grp_shuffle_block_s2_Pipeline_VITIS_LOOP_223_2_VITIS_LOOP_226_3_fu_172_ap_start_reg = 1'b0;
#0 grp_shuffle_block_s2_Pipeline_VITIS_LOOP_447_11_VITIS_LOOP_448_12_VITIS_LOOP_449_13_fu_180_ap_start_reg = 1'b0;
end

Shuffle_Model_dw_conv3x3_15 grp_dw_conv3x3_15_fu_74(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dw_conv3x3_15_fu_74_ap_start),
    .ap_done(grp_dw_conv3x3_15_fu_74_ap_done),
    .ap_idle(grp_dw_conv3x3_15_fu_74_ap_idle),
    .ap_ready(grp_dw_conv3x3_15_fu_74_ap_ready),
    .sm1_address0(grp_dw_conv3x3_15_fu_74_sm1_address0),
    .sm1_ce0(grp_dw_conv3x3_15_fu_74_sm1_ce0),
    .sm1_q0(sm1_q0),
    .b1_dw_out_address0(grp_dw_conv3x3_15_fu_74_b1_dw_out_address0),
    .b1_dw_out_ce0(grp_dw_conv3x3_15_fu_74_b1_dw_out_ce0),
    .b1_dw_out_we0(grp_dw_conv3x3_15_fu_74_b1_dw_out_we0),
    .b1_dw_out_d0(grp_dw_conv3x3_15_fu_74_b1_dw_out_d0)
);

Shuffle_Model_shuffle_block_s2_Pipeline_VITIS_LOOP_403_4 grp_shuffle_block_s2_Pipeline_VITIS_LOOP_403_4_fu_86(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_403_4_fu_86_ap_start),
    .ap_done(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_403_4_fu_86_ap_done),
    .ap_idle(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_403_4_fu_86_ap_idle),
    .ap_ready(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_403_4_fu_86_ap_ready),
    .sm3_address0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_403_4_fu_86_sm3_address0),
    .sm3_ce0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_403_4_fu_86_sm3_ce0),
    .sm3_we0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_403_4_fu_86_sm3_we0),
    .sm3_d0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_403_4_fu_86_sm3_d0)
);

Shuffle_Model_shuffle_block_s2_Pipeline_VITIS_LOOP_50_1 grp_shuffle_block_s2_Pipeline_VITIS_LOOP_50_1_fu_92(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_50_1_fu_92_ap_start),
    .ap_done(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_50_1_fu_92_ap_done),
    .ap_idle(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_50_1_fu_92_ap_idle),
    .ap_ready(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_50_1_fu_92_ap_ready),
    .sm2_address0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_50_1_fu_92_sm2_address0),
    .sm2_ce0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_50_1_fu_92_sm2_ce0),
    .sm2_we0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_50_1_fu_92_sm2_we0),
    .sm2_d0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_50_1_fu_92_sm2_d0)
);

Shuffle_Model_conv1x1_16 grp_conv1x1_16_fu_98(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_conv1x1_16_fu_98_ap_start),
    .ap_done(grp_conv1x1_16_fu_98_ap_done),
    .ap_idle(grp_conv1x1_16_fu_98_ap_idle),
    .ap_ready(grp_conv1x1_16_fu_98_ap_ready),
    .b1_pw_out_address0(grp_conv1x1_16_fu_98_b1_pw_out_address0),
    .b1_pw_out_ce0(grp_conv1x1_16_fu_98_b1_pw_out_ce0),
    .b1_pw_out_we0(grp_conv1x1_16_fu_98_b1_pw_out_we0),
    .b1_pw_out_d0(grp_conv1x1_16_fu_98_b1_pw_out_d0),
    .b1_dw_out_address0(grp_conv1x1_16_fu_98_b1_dw_out_address0),
    .b1_dw_out_ce0(grp_conv1x1_16_fu_98_b1_dw_out_ce0),
    .b1_dw_out_q0(b1_dw_out_q0)
);

Shuffle_Model_shuffle_block_s2_Pipeline_VITIS_LOOP_385_1_VITIS_LOOP_386_2_VITIS_LOOP_387_3 grp_shuffle_block_s2_Pipeline_VITIS_LOOP_385_1_VITIS_LOOP_386_2_VITIS_LOOP_387_3_fu_110(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_385_1_VITIS_LOOP_386_2_VITIS_LOOP_387_3_fu_110_ap_start),
    .ap_done(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_385_1_VITIS_LOOP_386_2_VITIS_LOOP_387_3_fu_110_ap_done),
    .ap_idle(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_385_1_VITIS_LOOP_386_2_VITIS_LOOP_387_3_fu_110_ap_idle),
    .ap_ready(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_385_1_VITIS_LOOP_386_2_VITIS_LOOP_387_3_fu_110_ap_ready),
    .sm1_address0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_385_1_VITIS_LOOP_386_2_VITIS_LOOP_387_3_fu_110_sm1_address0),
    .sm1_ce0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_385_1_VITIS_LOOP_386_2_VITIS_LOOP_387_3_fu_110_sm1_ce0),
    .sm1_q0(sm1_q0),
    .b2_in_address0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_385_1_VITIS_LOOP_386_2_VITIS_LOOP_387_3_fu_110_b2_in_address0),
    .b2_in_ce0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_385_1_VITIS_LOOP_386_2_VITIS_LOOP_387_3_fu_110_b2_in_ce0),
    .b2_in_we0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_385_1_VITIS_LOOP_386_2_VITIS_LOOP_387_3_fu_110_b2_in_we0),
    .b2_in_d0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_385_1_VITIS_LOOP_386_2_VITIS_LOOP_387_3_fu_110_b2_in_d0)
);

Shuffle_Model_shuffle_block_s2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_7_VIT grp_shuffle_block_s2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_7_VIT_fu_118(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_7_VIT_fu_118_ap_start),
    .ap_done(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_7_VIT_fu_118_ap_done),
    .ap_idle(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_7_VIT_fu_118_ap_idle),
    .ap_ready(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_7_VIT_fu_118_ap_ready),
    .sm3_address0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_7_VIT_fu_118_sm3_address0),
    .sm3_ce0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_7_VIT_fu_118_sm3_ce0),
    .sm3_we0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_7_VIT_fu_118_sm3_we0),
    .sm3_d0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_7_VIT_fu_118_sm3_d0),
    .b2_in_address0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_7_VIT_fu_118_b2_in_address0),
    .b2_in_ce0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_7_VIT_fu_118_b2_in_ce0),
    .b2_in_q0(b2_in_q0)
);

Shuffle_Model_dw_conv3x3_17 grp_dw_conv3x3_17_fu_130(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dw_conv3x3_17_fu_130_ap_start),
    .ap_done(grp_dw_conv3x3_17_fu_130_ap_done),
    .ap_idle(grp_dw_conv3x3_17_fu_130_ap_idle),
    .ap_ready(grp_dw_conv3x3_17_fu_130_ap_ready),
    .sm3_address0(grp_dw_conv3x3_17_fu_130_sm3_address0),
    .sm3_ce0(grp_dw_conv3x3_17_fu_130_sm3_ce0),
    .sm3_q0(sm3_q0),
    .b2_dw_out_address0(grp_dw_conv3x3_17_fu_130_b2_dw_out_address0),
    .b2_dw_out_ce0(grp_dw_conv3x3_17_fu_130_b2_dw_out_ce0),
    .b2_dw_out_we0(grp_dw_conv3x3_17_fu_130_b2_dw_out_we0),
    .b2_dw_out_d0(grp_dw_conv3x3_17_fu_130_b2_dw_out_d0)
);

Shuffle_Model_conv1x1_18 grp_conv1x1_18_fu_142(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_conv1x1_18_fu_142_ap_start),
    .ap_done(grp_conv1x1_18_fu_142_ap_done),
    .ap_idle(grp_conv1x1_18_fu_142_ap_idle),
    .ap_ready(grp_conv1x1_18_fu_142_ap_ready),
    .b2_pw2_out_address0(grp_conv1x1_18_fu_142_b2_pw2_out_address0),
    .b2_pw2_out_ce0(grp_conv1x1_18_fu_142_b2_pw2_out_ce0),
    .b2_pw2_out_we0(grp_conv1x1_18_fu_142_b2_pw2_out_we0),
    .b2_pw2_out_d0(grp_conv1x1_18_fu_142_b2_pw2_out_d0),
    .b2_dw_out_address0(grp_conv1x1_18_fu_142_b2_dw_out_address0),
    .b2_dw_out_ce0(grp_conv1x1_18_fu_142_b2_dw_out_ce0),
    .b2_dw_out_q0(b2_dw_out_q0)
);

Shuffle_Model_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10 grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_ap_start),
    .ap_done(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_ap_done),
    .ap_idle(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_ap_idle),
    .ap_ready(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_ap_ready),
    .b1_pw_out_address0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_b1_pw_out_address0),
    .b1_pw_out_ce0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_b1_pw_out_ce0),
    .b1_pw_out_q0(b1_pw_out_q0),
    .concat_address0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_concat_address0),
    .concat_ce0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_concat_ce0),
    .concat_we0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_concat_we0),
    .concat_d0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_concat_d0),
    .concat_address1(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_concat_address1),
    .concat_ce1(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_concat_ce1),
    .concat_we1(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_concat_we1),
    .concat_d1(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_concat_d1),
    .b2_pw2_out_address0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_b2_pw2_out_address0),
    .b2_pw2_out_ce0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_b2_pw2_out_ce0),
    .b2_pw2_out_q0(b2_pw2_out_q0)
);

Shuffle_Model_shuffle_block_s2_Pipeline_VITIS_LOOP_221_1 grp_shuffle_block_s2_Pipeline_VITIS_LOOP_221_1_fu_164(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_221_1_fu_164_ap_start),
    .ap_done(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_221_1_fu_164_ap_done),
    .ap_idle(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_221_1_fu_164_ap_idle),
    .ap_ready(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_221_1_fu_164_ap_ready),
    .concat_address0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_221_1_fu_164_concat_address0),
    .concat_ce0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_221_1_fu_164_concat_ce0),
    .concat_q0(concat_q0),
    .tmp_address0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_221_1_fu_164_tmp_address0),
    .tmp_ce0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_221_1_fu_164_tmp_ce0),
    .tmp_we0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_221_1_fu_164_tmp_we0),
    .tmp_d0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_221_1_fu_164_tmp_d0)
);

Shuffle_Model_shuffle_block_s2_Pipeline_VITIS_LOOP_223_2_VITIS_LOOP_226_3 grp_shuffle_block_s2_Pipeline_VITIS_LOOP_223_2_VITIS_LOOP_226_3_fu_172(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_223_2_VITIS_LOOP_226_3_fu_172_ap_start),
    .ap_done(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_223_2_VITIS_LOOP_226_3_fu_172_ap_done),
    .ap_idle(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_223_2_VITIS_LOOP_226_3_fu_172_ap_idle),
    .ap_ready(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_223_2_VITIS_LOOP_226_3_fu_172_ap_ready),
    .tmp_address0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_223_2_VITIS_LOOP_226_3_fu_172_tmp_address0),
    .tmp_ce0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_223_2_VITIS_LOOP_226_3_fu_172_tmp_ce0),
    .tmp_q0(tmp_q0),
    .concat_address0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_223_2_VITIS_LOOP_226_3_fu_172_concat_address0),
    .concat_ce0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_223_2_VITIS_LOOP_226_3_fu_172_concat_ce0),
    .concat_we0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_223_2_VITIS_LOOP_226_3_fu_172_concat_we0),
    .concat_d0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_223_2_VITIS_LOOP_226_3_fu_172_concat_d0)
);

Shuffle_Model_shuffle_block_s2_Pipeline_VITIS_LOOP_447_11_VITIS_LOOP_448_12_VITIS_LOOP_449_13 grp_shuffle_block_s2_Pipeline_VITIS_LOOP_447_11_VITIS_LOOP_448_12_VITIS_LOOP_449_13_fu_180(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_447_11_VITIS_LOOP_448_12_VITIS_LOOP_449_13_fu_180_ap_start),
    .ap_done(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_447_11_VITIS_LOOP_448_12_VITIS_LOOP_449_13_fu_180_ap_done),
    .ap_idle(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_447_11_VITIS_LOOP_448_12_VITIS_LOOP_449_13_fu_180_ap_idle),
    .ap_ready(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_447_11_VITIS_LOOP_448_12_VITIS_LOOP_449_13_fu_180_ap_ready),
    .sm2_address0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_447_11_VITIS_LOOP_448_12_VITIS_LOOP_449_13_fu_180_sm2_address0),
    .sm2_ce0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_447_11_VITIS_LOOP_448_12_VITIS_LOOP_449_13_fu_180_sm2_ce0),
    .sm2_we0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_447_11_VITIS_LOOP_448_12_VITIS_LOOP_449_13_fu_180_sm2_we0),
    .sm2_d0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_447_11_VITIS_LOOP_448_12_VITIS_LOOP_449_13_fu_180_sm2_d0),
    .concat_address0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_447_11_VITIS_LOOP_448_12_VITIS_LOOP_449_13_fu_180_concat_address0),
    .concat_ce0(grp_shuffle_block_s2_Pipeline_VITIS_LOOP_447_11_VITIS_LOOP_448_12_VITIS_LOOP_449_13_fu_180_concat_ce0),
    .concat_q0(concat_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_conv1x1_16_fu_98_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state3) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_conv1x1_16_fu_98_ap_start_reg <= 1'b1;
        end else if ((grp_conv1x1_16_fu_98_ap_ready == 1'b1)) begin
            grp_conv1x1_16_fu_98_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_conv1x1_18_fu_142_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state9) & (1'b1 == ap_CS_fsm_state8))) begin
            grp_conv1x1_18_fu_142_ap_start_reg <= 1'b1;
        end else if ((grp_conv1x1_18_fu_142_ap_ready == 1'b1)) begin
            grp_conv1x1_18_fu_142_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dw_conv3x3_15_fu_74_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_dw_conv3x3_15_fu_74_ap_start_reg <= 1'b1;
        end else if ((grp_dw_conv3x3_15_fu_74_ap_ready == 1'b1)) begin
            grp_dw_conv3x3_15_fu_74_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dw_conv3x3_17_fu_130_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state7) & (1'b1 == ap_CS_fsm_state6))) begin
            grp_dw_conv3x3_17_fu_130_ap_start_reg <= 1'b1;
        end else if ((grp_dw_conv3x3_17_fu_130_ap_ready == 1'b1)) begin
            grp_dw_conv3x3_17_fu_130_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_shuffle_block_s2_Pipeline_VITIS_LOOP_221_1_fu_164_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            grp_shuffle_block_s2_Pipeline_VITIS_LOOP_221_1_fu_164_ap_start_reg <= 1'b1;
        end else if ((grp_shuffle_block_s2_Pipeline_VITIS_LOOP_221_1_fu_164_ap_ready == 1'b1)) begin
            grp_shuffle_block_s2_Pipeline_VITIS_LOOP_221_1_fu_164_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_shuffle_block_s2_Pipeline_VITIS_LOOP_223_2_VITIS_LOOP_226_3_fu_172_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state15) & (1'b1 == ap_CS_fsm_state14))) begin
            grp_shuffle_block_s2_Pipeline_VITIS_LOOP_223_2_VITIS_LOOP_226_3_fu_172_ap_start_reg <= 1'b1;
        end else if ((grp_shuffle_block_s2_Pipeline_VITIS_LOOP_223_2_VITIS_LOOP_226_3_fu_172_ap_ready == 1'b1)) begin
            grp_shuffle_block_s2_Pipeline_VITIS_LOOP_223_2_VITIS_LOOP_226_3_fu_172_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_shuffle_block_s2_Pipeline_VITIS_LOOP_385_1_VITIS_LOOP_386_2_VITIS_LOOP_387_3_fu_110_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state3) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_shuffle_block_s2_Pipeline_VITIS_LOOP_385_1_VITIS_LOOP_386_2_VITIS_LOOP_387_3_fu_110_ap_start_reg <= 1'b1;
        end else if ((grp_shuffle_block_s2_Pipeline_VITIS_LOOP_385_1_VITIS_LOOP_386_2_VITIS_LOOP_387_3_fu_110_ap_ready == 1'b1)) begin
            grp_shuffle_block_s2_Pipeline_VITIS_LOOP_385_1_VITIS_LOOP_386_2_VITIS_LOOP_387_3_fu_110_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_shuffle_block_s2_Pipeline_VITIS_LOOP_403_4_fu_86_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_shuffle_block_s2_Pipeline_VITIS_LOOP_403_4_fu_86_ap_start_reg <= 1'b1;
        end else if ((grp_shuffle_block_s2_Pipeline_VITIS_LOOP_403_4_fu_86_ap_ready == 1'b1)) begin
            grp_shuffle_block_s2_Pipeline_VITIS_LOOP_403_4_fu_86_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_shuffle_block_s2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_7_VIT_fu_118_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state5) & (1'b1 == ap_CS_fsm_state4))) begin
            grp_shuffle_block_s2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_7_VIT_fu_118_ap_start_reg <= 1'b1;
        end else if ((grp_shuffle_block_s2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_7_VIT_fu_118_ap_ready == 1'b1)) begin
            grp_shuffle_block_s2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_7_VIT_fu_118_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_ap_start_reg <= 1'b1;
        end else if ((grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_ap_ready == 1'b1)) begin
            grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_shuffle_block_s2_Pipeline_VITIS_LOOP_447_11_VITIS_LOOP_448_12_VITIS_LOOP_449_13_fu_180_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state17) & (1'b1 == ap_CS_fsm_state16))) begin
            grp_shuffle_block_s2_Pipeline_VITIS_LOOP_447_11_VITIS_LOOP_448_12_VITIS_LOOP_449_13_fu_180_ap_start_reg <= 1'b1;
        end else if ((grp_shuffle_block_s2_Pipeline_VITIS_LOOP_447_11_VITIS_LOOP_448_12_VITIS_LOOP_449_13_fu_180_ap_ready == 1'b1)) begin
            grp_shuffle_block_s2_Pipeline_VITIS_LOOP_447_11_VITIS_LOOP_448_12_VITIS_LOOP_449_13_fu_180_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_shuffle_block_s2_Pipeline_VITIS_LOOP_50_1_fu_92_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_shuffle_block_s2_Pipeline_VITIS_LOOP_50_1_fu_92_ap_start_reg <= 1'b1;
        end else if ((grp_shuffle_block_s2_Pipeline_VITIS_LOOP_50_1_fu_92_ap_ready == 1'b1)) begin
            grp_shuffle_block_s2_Pipeline_VITIS_LOOP_50_1_fu_92_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((grp_conv1x1_18_fu_142_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

always @ (*) begin
    if ((grp_shuffle_block_s2_Pipeline_VITIS_LOOP_221_1_fu_164_ap_done == 1'b0)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

assign ap_ST_fsm_state15_blk = 1'b0;

always @ (*) begin
    if ((grp_shuffle_block_s2_Pipeline_VITIS_LOOP_223_2_VITIS_LOOP_226_3_fu_172_ap_done == 1'b0)) begin
        ap_ST_fsm_state16_blk = 1'b1;
    end else begin
        ap_ST_fsm_state16_blk = 1'b0;
    end
end

assign ap_ST_fsm_state17_blk = 1'b0;

always @ (*) begin
    if ((grp_shuffle_block_s2_Pipeline_VITIS_LOOP_447_11_VITIS_LOOP_448_12_VITIS_LOOP_449_13_fu_180_ap_done == 1'b0)) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state4_on_subcall_done)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_shuffle_block_s2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_7_VIT_fu_118_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_dw_conv3x3_17_fu_130_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((grp_shuffle_block_s2_Pipeline_VITIS_LOOP_447_11_VITIS_LOOP_448_12_VITIS_LOOP_449_13_fu_180_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_shuffle_block_s2_Pipeline_VITIS_LOOP_447_11_VITIS_LOOP_448_12_VITIS_LOOP_449_13_fu_180_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        b1_dw_out_address0 = grp_conv1x1_16_fu_98_b1_dw_out_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        b1_dw_out_address0 = grp_dw_conv3x3_15_fu_74_b1_dw_out_address0;
    end else begin
        b1_dw_out_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        b1_dw_out_ce0 = grp_conv1x1_16_fu_98_b1_dw_out_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        b1_dw_out_ce0 = grp_dw_conv3x3_15_fu_74_b1_dw_out_ce0;
    end else begin
        b1_dw_out_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        b1_dw_out_we0 = grp_dw_conv3x3_15_fu_74_b1_dw_out_we0;
    end else begin
        b1_dw_out_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        b1_pw_out_address0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_b1_pw_out_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        b1_pw_out_address0 = grp_conv1x1_16_fu_98_b1_pw_out_address0;
    end else begin
        b1_pw_out_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        b1_pw_out_ce0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_b1_pw_out_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        b1_pw_out_ce0 = grp_conv1x1_16_fu_98_b1_pw_out_ce0;
    end else begin
        b1_pw_out_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        b1_pw_out_we0 = grp_conv1x1_16_fu_98_b1_pw_out_we0;
    end else begin
        b1_pw_out_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        b2_dw_out_address0 = grp_conv1x1_18_fu_142_b2_dw_out_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        b2_dw_out_address0 = grp_dw_conv3x3_17_fu_130_b2_dw_out_address0;
    end else begin
        b2_dw_out_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        b2_dw_out_ce0 = grp_conv1x1_18_fu_142_b2_dw_out_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        b2_dw_out_ce0 = grp_dw_conv3x3_17_fu_130_b2_dw_out_ce0;
    end else begin
        b2_dw_out_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        b2_dw_out_we0 = grp_dw_conv3x3_17_fu_130_b2_dw_out_we0;
    end else begin
        b2_dw_out_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        b2_in_address0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_7_VIT_fu_118_b2_in_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        b2_in_address0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_385_1_VITIS_LOOP_386_2_VITIS_LOOP_387_3_fu_110_b2_in_address0;
    end else begin
        b2_in_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        b2_in_ce0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_7_VIT_fu_118_b2_in_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        b2_in_ce0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_385_1_VITIS_LOOP_386_2_VITIS_LOOP_387_3_fu_110_b2_in_ce0;
    end else begin
        b2_in_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        b2_in_we0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_385_1_VITIS_LOOP_386_2_VITIS_LOOP_387_3_fu_110_b2_in_we0;
    end else begin
        b2_in_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        b2_pw2_out_address0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_b2_pw2_out_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        b2_pw2_out_address0 = grp_conv1x1_18_fu_142_b2_pw2_out_address0;
    end else begin
        b2_pw2_out_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        b2_pw2_out_ce0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_b2_pw2_out_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        b2_pw2_out_ce0 = grp_conv1x1_18_fu_142_b2_pw2_out_ce0;
    end else begin
        b2_pw2_out_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        b2_pw2_out_we0 = grp_conv1x1_18_fu_142_b2_pw2_out_we0;
    end else begin
        b2_pw2_out_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        concat_address0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_447_11_VITIS_LOOP_448_12_VITIS_LOOP_449_13_fu_180_concat_address0;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        concat_address0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_223_2_VITIS_LOOP_226_3_fu_172_concat_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        concat_address0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_221_1_fu_164_concat_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        concat_address0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_concat_address0;
    end else begin
        concat_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        concat_ce0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_447_11_VITIS_LOOP_448_12_VITIS_LOOP_449_13_fu_180_concat_ce0;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        concat_ce0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_223_2_VITIS_LOOP_226_3_fu_172_concat_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        concat_ce0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_221_1_fu_164_concat_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        concat_ce0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_concat_ce0;
    end else begin
        concat_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        concat_ce1 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_concat_ce1;
    end else begin
        concat_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        concat_d0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_223_2_VITIS_LOOP_226_3_fu_172_concat_d0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        concat_d0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_concat_d0;
    end else begin
        concat_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        concat_we0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_223_2_VITIS_LOOP_226_3_fu_172_concat_we0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        concat_we0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_concat_we0;
    end else begin
        concat_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        concat_we1 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_concat_we1;
    end else begin
        concat_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        sm1_address0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_385_1_VITIS_LOOP_386_2_VITIS_LOOP_387_3_fu_110_sm1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        sm1_address0 = grp_dw_conv3x3_15_fu_74_sm1_address0;
    end else begin
        sm1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        sm1_ce0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_385_1_VITIS_LOOP_386_2_VITIS_LOOP_387_3_fu_110_sm1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        sm1_ce0 = grp_dw_conv3x3_15_fu_74_sm1_ce0;
    end else begin
        sm1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        sm2_address0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_447_11_VITIS_LOOP_448_12_VITIS_LOOP_449_13_fu_180_sm2_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        sm2_address0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_50_1_fu_92_sm2_address0;
    end else begin
        sm2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        sm2_ce0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_447_11_VITIS_LOOP_448_12_VITIS_LOOP_449_13_fu_180_sm2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        sm2_ce0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_50_1_fu_92_sm2_ce0;
    end else begin
        sm2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        sm2_d0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_447_11_VITIS_LOOP_448_12_VITIS_LOOP_449_13_fu_180_sm2_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        sm2_d0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_50_1_fu_92_sm2_d0;
    end else begin
        sm2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        sm2_we0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_447_11_VITIS_LOOP_448_12_VITIS_LOOP_449_13_fu_180_sm2_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        sm2_we0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_50_1_fu_92_sm2_we0;
    end else begin
        sm2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        sm3_address0 = grp_dw_conv3x3_17_fu_130_sm3_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        sm3_address0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_7_VIT_fu_118_sm3_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        sm3_address0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_403_4_fu_86_sm3_address0;
    end else begin
        sm3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        sm3_ce0 = grp_dw_conv3x3_17_fu_130_sm3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        sm3_ce0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_7_VIT_fu_118_sm3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        sm3_ce0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_403_4_fu_86_sm3_ce0;
    end else begin
        sm3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        sm3_d0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_7_VIT_fu_118_sm3_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        sm3_d0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_403_4_fu_86_sm3_d0;
    end else begin
        sm3_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        sm3_we0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_7_VIT_fu_118_sm3_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        sm3_we0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_403_4_fu_86_sm3_we0;
    end else begin
        sm3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        tmp_address0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_223_2_VITIS_LOOP_226_3_fu_172_tmp_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        tmp_address0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_221_1_fu_164_tmp_address0;
    end else begin
        tmp_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        tmp_ce0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_223_2_VITIS_LOOP_226_3_fu_172_tmp_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        tmp_ce0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_221_1_fu_164_tmp_ce0;
    end else begin
        tmp_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        tmp_we0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_221_1_fu_164_tmp_we0;
    end else begin
        tmp_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_shuffle_block_s2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_7_VIT_fu_118_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (grp_dw_conv3x3_17_fu_130_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((grp_conv1x1_18_fu_142_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((grp_shuffle_block_s2_Pipeline_VITIS_LOOP_221_1_fu_164_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            if (((grp_shuffle_block_s2_Pipeline_VITIS_LOOP_223_2_VITIS_LOOP_226_3_fu_172_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            if (((grp_shuffle_block_s2_Pipeline_VITIS_LOOP_447_11_VITIS_LOOP_448_12_VITIS_LOOP_449_13_fu_180_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_NS_fsm_state15 = ap_NS_fsm[32'd14];

assign ap_NS_fsm_state17 = ap_NS_fsm[32'd16];

assign ap_NS_fsm_state3 = ap_NS_fsm[32'd2];

assign ap_NS_fsm_state5 = ap_NS_fsm[32'd4];

assign ap_NS_fsm_state7 = ap_NS_fsm[32'd6];

assign ap_NS_fsm_state9 = ap_NS_fsm[32'd8];

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_shuffle_block_s2_Pipeline_VITIS_LOOP_50_1_fu_92_ap_done == 1'b0) | (grp_shuffle_block_s2_Pipeline_VITIS_LOOP_403_4_fu_86_ap_done == 1'b0) | (grp_dw_conv3x3_15_fu_74_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state4_on_subcall_done = ((grp_shuffle_block_s2_Pipeline_VITIS_LOOP_385_1_VITIS_LOOP_386_2_VITIS_LOOP_387_3_fu_110_ap_done == 1'b0) | (grp_conv1x1_16_fu_98_ap_done == 1'b0));
end

assign b1_dw_out_d0 = grp_dw_conv3x3_15_fu_74_b1_dw_out_d0;

assign b1_pw_out_d0 = grp_conv1x1_16_fu_98_b1_pw_out_d0;

assign b2_dw_out_d0 = grp_dw_conv3x3_17_fu_130_b2_dw_out_d0;

assign b2_in_d0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_385_1_VITIS_LOOP_386_2_VITIS_LOOP_387_3_fu_110_b2_in_d0;

assign b2_pw2_out_d0 = grp_conv1x1_18_fu_142_b2_pw2_out_d0;

assign concat_address1 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_concat_address1;

assign concat_d1 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_concat_d1;

assign grp_conv1x1_16_fu_98_ap_start = grp_conv1x1_16_fu_98_ap_start_reg;

assign grp_conv1x1_18_fu_142_ap_start = grp_conv1x1_18_fu_142_ap_start_reg;

assign grp_dw_conv3x3_15_fu_74_ap_start = grp_dw_conv3x3_15_fu_74_ap_start_reg;

assign grp_dw_conv3x3_17_fu_130_ap_start = grp_dw_conv3x3_17_fu_130_ap_start_reg;

assign grp_shuffle_block_s2_Pipeline_VITIS_LOOP_221_1_fu_164_ap_start = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_221_1_fu_164_ap_start_reg;

assign grp_shuffle_block_s2_Pipeline_VITIS_LOOP_223_2_VITIS_LOOP_226_3_fu_172_ap_start = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_223_2_VITIS_LOOP_226_3_fu_172_ap_start_reg;

assign grp_shuffle_block_s2_Pipeline_VITIS_LOOP_385_1_VITIS_LOOP_386_2_VITIS_LOOP_387_3_fu_110_ap_start = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_385_1_VITIS_LOOP_386_2_VITIS_LOOP_387_3_fu_110_ap_start_reg;

assign grp_shuffle_block_s2_Pipeline_VITIS_LOOP_403_4_fu_86_ap_start = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_403_4_fu_86_ap_start_reg;

assign grp_shuffle_block_s2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_7_VIT_fu_118_ap_start = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_7_VIT_fu_118_ap_start_reg;

assign grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_ap_start = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_436_9_VITIS_LOOP_437_10_fu_154_ap_start_reg;

assign grp_shuffle_block_s2_Pipeline_VITIS_LOOP_447_11_VITIS_LOOP_448_12_VITIS_LOOP_449_13_fu_180_ap_start = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_447_11_VITIS_LOOP_448_12_VITIS_LOOP_449_13_fu_180_ap_start_reg;

assign grp_shuffle_block_s2_Pipeline_VITIS_LOOP_50_1_fu_92_ap_start = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_50_1_fu_92_ap_start_reg;

assign tmp_d0 = grp_shuffle_block_s2_Pipeline_VITIS_LOOP_221_1_fu_164_tmp_d0;

endmodule //Shuffle_Model_shuffle_block_s2
