"""
gen_bias_rom_3x3_init.py
========================
Reads tb/group1/vectors/bias_rom_3x3.hex (24 x 15-bit Q6.8 values) and
generates:
 rtl/group1/bias_rom_3x3_init.vh -- localparam for RTL inclusion
 tb/group1/vectors/bias_rom_3x3_tb_vectors.hex -- testbench check vectors

If bias_rom_3x3.hex contains PLACEHOLDER values (from gen_weights_rom_3x3_vectors.py),
the same placeholder values will be used. After extract_weights_conv1.py is run
(producing real BN-folded biases), re-run this script to update both outputs.

 "24 bias that should be read in parallel, so we also implement this memory
 as LUTs and get the output to the 3x3 core"
"""

import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJ_ROOT = os.path.join(SCRIPT_DIR, "..", "..")
HEX_IN = os.path.join(PROJ_ROOT, "tb", "group1", "vectors", "bias_rom_3x3.hex")
VH_OUT = os.path.join(PROJ_ROOT, "rtl", "group1", "bias_rom_3x3_init.vh")
TB_VEC_OUT = os.path.join(PROJ_ROOT, "tb", "group1", "vectors", "bias_rom_3x3_tb_vectors.hex")

N_FILT = 24
DATA_W = 15

# -----------------------------------------------------------------------
# Read hex file
# -----------------------------------------------------------------------
bias_hex = []
with open(HEX_IN) as f:
 for line in f:
 line = line.strip
 if not line or line.startswith("//"):
 continue
 bias_hex.append(line.upper)

if len(bias_hex) != N_FILT:
 print(f"ERROR: expected {N_FILT} bias entries, got {len(bias_hex)}")
 sys.exit(1)

print(f"Read {len(bias_hex)} bias values from {HEX_IN}")

# -----------------------------------------------------------------------
# Generate Verilog init file
# BIASES packed bus: biases_flat[f*DATA_W +: DATA_W] = bias[filter f]
# Verilog concatenation is MSB-first: {bias[23], bias[22], ..., bias[0]}
# -----------------------------------------------------------------------
packed_parts = [f"{DATA_W}'h{h}" for h in reversed(bias_hex)]
packed_str = ",\n ".join(packed_parts)
total_bits = N_FILT * DATA_W # 360

with open(VH_OUT, "w") as f:
 f.write("// =============================================================\n")
 f.write("// bias_rom_3x3_init.vh -- AUTO-GENERATED bias constants\n")
 f.write("// / Figure 5.7\n")
 f.write("// 15-bit Q6.8 BN-folded conv1 biases for 24 filters\n")
 f.write("// Generated by: scripts/gen_bias_rom_3x3_init.py\n")
 f.write("// =============================================================\n")
 f.write("`ifndef BIAS_ROM_3X3_INIT_VH\n")
 f.write("`define BIAS_ROM_3X3_INIT_VH\n\n")
 f.write(f"// biases_flat[f*{DATA_W} +: {DATA_W}] = bias for filter f\n")
 f.write(f"localparam [{total_bits}-1:0] BIASES = {{\n")
 f.write(f" {packed_str}\n}};\n\n")
 f.write("`endif\n")

print(f"Written: {VH_OUT}")

# -----------------------------------------------------------------------
# Generate testbench check vectors
# Format: filter expected_bias_hex
# -----------------------------------------------------------------------
with open(TB_VEC_OUT, "w") as f:
 f.write("// bias_rom_3x3 testbench check vectors\n")
 f.write("// Format: filter expected_bias_hex\n")
 f.write(f"// {N_FILT} entries (one per filter)\n")
 for fi, h in enumerate(bias_hex):
 f.write(f"{fi} {h}\n")

print(f"Written: {TB_VEC_OUT}")
print("Done.")
