"""
gen_hls_weights.py -- Extract BN-folded Q6.8 weights from pretrained
ShuffleNet V2 x1.0 and write C++ header files for Vitis HLS.

Output: one header per layer group in hls/weights/
Run from the project root:  python hls/scripts/gen_hls_weights.py

Weights are written in decimal integer format (not hex) so ap_fixed /
short int arrays read them correctly.
"""
import torch, copy, sys, os
import numpy as np
from torchvision import models

# ----------- Q6.8 constants (same as all other scripts) -----------
Q_FRAC = 8
DATA_MAX = (1 << 14) - 1   # 16383
DATA_MIN = -(1 << 14)       # -16384

def qarr(a):
    """Quantise float array to Q6.8 integers (clipped to 15-bit signed)."""
    return np.clip(
        np.round(np.asarray(a, dtype=np.float64) * (1 << Q_FRAC)),
        DATA_MIN, DATA_MAX
    ).astype(np.int32)

# ----------- BN folding (identical to verify_accuracy.py) ----------
def fold_conv_bn(conv, bn):
    conv = copy.deepcopy(conv)
    scale = bn.weight.data / torch.sqrt(bn.running_var + bn.eps)
    conv.weight = torch.nn.Parameter(conv.weight.data * scale.view(-1,1,1,1))
    bias = conv.bias.data if conv.bias is not None else torch.zeros_like(scale)
    conv.bias = torch.nn.Parameter(scale * (bias - bn.running_mean) + bn.bias.data)
    return conv

def fold_all_bn(module):
    for name, child in module.named_children():
        if isinstance(child, torch.nn.Sequential):
            layers = list(child.children()); nl = []; i = 0
            while i < len(layers):
                if (isinstance(layers[i], torch.nn.Conv2d) and
                        i + 1 < len(layers) and
                        isinstance(layers[i+1], torch.nn.BatchNorm2d)):
                    nl.append(fold_conv_bn(layers[i], layers[i+1]))
                    nl.append(torch.nn.Identity()); i += 2
                else:
                    nl.append(layers[i]); i += 1
            setattr(module, name, torch.nn.Sequential(*nl))
            fold_all_bn(getattr(module, name))
        else:
            fold_all_bn(child)

def get_convs(seq):
    return [m for m in seq.children() if isinstance(m, torch.nn.Conv2d)]

# ----------- Header writer helpers ---------------------------------
OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "weights")

def _write_array(f, name, arr, dtype="short int"):
    """Write a flat C++ const array in decimal format (Sec 7.3.2.1)."""
    flat = arr.flatten()
    f.write(f"const {dtype} {name}[{len(flat)}] = {{\n")
    per_row = 12
    for i in range(0, len(flat), per_row):
        chunk = flat[i:i+per_row]
        f.write("    " + ", ".join(str(int(v)) for v in chunk))
        if i + per_row < len(flat):
            f.write(",")
        f.write("\n")
    f.write("};\n\n")

def write_header(filename, arrays, comment=""):
    """Write a single header file containing multiple arrays."""
    guard = filename.upper().replace(".", "_").replace("/", "_")
    path = os.path.join(OUT_DIR, filename)
    with open(path, "w") as f:
        f.write(f"/* Auto-generated by gen_hls_weights.py -- do not edit */\n")
        if comment:
            f.write(f"/* {comment} */\n")
        f.write(f"#pragma once\n\n")
        for name, arr in arrays:
            _write_array(f, name, arr)
    print(f"  Wrote {path}  ({sum(a.size for _,a in arrays):,} values)")

# ----------- Main --------------------------------------------------
def main():
    os.makedirs(OUT_DIR, exist_ok=True)

    print("Loading ShuffleNet V2 x1.0 ...")
    wts = models.ShuffleNet_V2_X1_0_Weights.DEFAULT
    model = models.shufflenet_v2_x1_0(weights=wts).eval()

    print("Folding BN ...")
    fold_all_bn(model)
    model.eval()

    # ------ Group 1: conv1 ------
    # conv1.0 is the 3x3 conv (conv1.1 is BN, now folded → Identity)
    conv1 = None
    for m in model.conv1.children():
        if isinstance(m, torch.nn.Conv2d):
            conv1 = m; break
    assert conv1 is not None
    c1_w = qarr(conv1.weight.detach().numpy())   # [24,3,3,3]
    c1_b = qarr(conv1.bias.detach().numpy())     # [24]
    write_header("conv1_weights.h",
                 [("conv1_w", c1_w), ("conv1_b", c1_b)],
                 "Group 1: 3x3 conv weights+biases (24 filters, 3 in-ch, 3x3 kernel)")

    # ------ Groups 2: shuffle blocks ------
    stages = [("stage2", model.stage2), ("stage3", model.stage3),
               ("stage4", model.stage4)]
    blk_idx = 0  # global block counter (0..15)

    for stage_name, stage in stages:
        for local_idx, blk in enumerate(stage):
            tag = f"{stage_name[5]}_{local_idx}"  # e.g. "2_0", "3_2"
            arrays = []

            # branch2 always exists: PW1 -> DW -> PW2 (full architecture)
            b2_convs = get_convs(blk.branch2)
            # After BN folding, branch2 children are:
            # [Conv(pw1), Identity, ReLU?, Conv(dw), Identity, Conv(pw2), Identity, ReLU?]
            # get_convs filters only Conv2d → [pw1, dw, pw2]
            assert len(b2_convs) == 3, \
                f"Expected 3 convs in branch2 of {stage_name}[{local_idx}], got {len(b2_convs)}"
            pw1, dw, pw2 = b2_convs

            arrays.append((f"s{tag}_b2_pw1_w", qarr(pw1.weight.detach().numpy())))
            arrays.append((f"s{tag}_b2_pw1_b", qarr(pw1.bias.detach().numpy())))
            arrays.append((f"s{tag}_b2_dw_w",  qarr(dw.weight.detach().numpy())))
            arrays.append((f"s{tag}_b2_dw_b",  qarr(dw.bias.detach().numpy())))
            arrays.append((f"s{tag}_b2_pw2_w", qarr(pw2.weight.detach().numpy())))
            arrays.append((f"s{tag}_b2_pw2_b", qarr(pw2.bias.detach().numpy())))

            # branch1 exists only in stride-2 blocks (first block of each stage)
            if hasattr(blk, "branch1"):
                b1_convs = get_convs(blk.branch1)
                if len(b1_convs) >= 2:
                    dw1, pw1b = b1_convs[0], b1_convs[1]
                    arrays.append((f"s{tag}_b1_dw_w",  qarr(dw1.weight.detach().numpy())))
                    arrays.append((f"s{tag}_b1_dw_b",  qarr(dw1.bias.detach().numpy())))
                    arrays.append((f"s{tag}_b1_pw_w",  qarr(pw1b.weight.detach().numpy())))
                    arrays.append((f"s{tag}_b1_pw_b",  qarr(pw1b.bias.detach().numpy())))

            stride = int(dw.stride[0])
            write_header(f"block_s{tag}.h", arrays,
                         f"{stage_name} block {local_idx}, stride={stride}")
            blk_idx += 1

    # ------ Group 3: conv5 ------
    conv5 = None
    for m in model.conv5.children():
        if isinstance(m, torch.nn.Conv2d):
            conv5 = m; break
    assert conv5 is not None
    c5_w = qarr(conv5.weight.detach().numpy().reshape(1024, 464))  # [1024,464]
    c5_b = qarr(conv5.bias.detach().numpy())  # [1024]
    write_header("conv5_weights.h",
                 [("conv5_w", c5_w), ("conv5_b", c5_b)],
                 "Group 3: 1x1 conv5 weights+biases (1024 filters, 464 in-ch)")

    # ------ Group 3: FC ------
    fc_w = qarr(model.fc.weight.detach().numpy())  # [1000,1024]
    fc_b = qarr(model.fc.bias.detach().numpy())    # [1000]
    write_header("fc_weights.h",
                 [("fc_w", fc_w), ("fc_b", fc_b)],
                 "Group 3: FC weights+biases (1000 classes, 1024 in)")

    print(f"\nDone. {blk_idx} shuffle blocks processed.")
    print(f"Weight files written to: {os.path.abspath(OUT_DIR)}")
    print("\nNext: run C simulation with Vitis HLS.")

if __name__ == "__main__":
    main()
