// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Shuffle_Model_conv5_avgpool_Pipeline_VITIS_LOOP_151_1_VITIS_LOOP_152_2_VITIS_LOOP_153_3_VITIS_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        c5_out_address0,
        c5_out_ce0,
        c5_out_we0,
        c5_out_d0,
        c5_in_address0,
        c5_in_ce0,
        c5_in_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [15:0] c5_out_address0;
output   c5_out_ce0;
output   c5_out_we0;
output  [13:0] c5_out_d0;
output  [14:0] c5_in_address0;
output   c5_in_ce0;
input  [15:0] c5_in_q0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln151_fu_225_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [9:0] conv5_b_address0;
wire   [8:0] conv5_b_q0;
wire   [18:0] conv5_w_address0;
wire  signed [7:0] conv5_w_q0;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln152_fu_243_p2;
reg   [0:0] icmp_ln152_reg_741;
reg   [0:0] icmp_ln152_reg_741_pp0_iter2_reg;
wire   [0:0] and_ln151_1_fu_267_p2;
reg   [0:0] and_ln151_1_reg_746;
reg   [0:0] and_ln151_1_reg_746_pp0_iter2_reg;
wire   [10:0] select_ln151_1_fu_279_p3;
reg   [10:0] select_ln151_1_reg_751;
reg   [10:0] select_ln151_1_reg_751_pp0_iter2_reg;
reg   [10:0] select_ln151_1_reg_751_pp0_iter3_reg;
reg   [10:0] select_ln151_1_reg_751_pp0_iter4_reg;
reg   [10:0] select_ln151_1_reg_751_pp0_iter5_reg;
wire   [0:0] empty_fu_287_p2;
reg   [0:0] empty_reg_757;
reg   [0:0] empty_reg_757_pp0_iter2_reg;
reg   [0:0] empty_reg_757_pp0_iter3_reg;
wire   [0:0] icmp_ln155_mid234_fu_311_p2;
reg   [0:0] icmp_ln155_mid234_reg_762;
reg   [0:0] icmp_ln155_mid234_reg_762_pp0_iter2_reg;
reg   [0:0] icmp_ln155_mid234_reg_762_pp0_iter3_reg;
wire   [0:0] empty_289_fu_323_p2;
reg   [0:0] empty_289_reg_767;
reg   [0:0] empty_289_reg_767_pp0_iter2_reg;
reg   [0:0] empty_289_reg_767_pp0_iter3_reg;
reg   [0:0] empty_289_reg_767_pp0_iter4_reg;
reg   [0:0] empty_289_reg_767_pp0_iter5_reg;
reg   [0:0] empty_289_reg_767_pp0_iter6_reg;
wire   [8:0] ic_mid2_fu_329_p3;
reg   [8:0] ic_mid2_reg_772;
reg   [8:0] ic_mid2_reg_772_pp0_iter2_reg;
wire   [0:0] icmp_ln155_1_fu_351_p2;
reg   [0:0] icmp_ln155_1_reg_787;
reg   [0:0] icmp_ln155_1_reg_787_pp0_iter2_reg;
reg   [0:0] icmp_ln155_1_reg_787_pp0_iter3_reg;
reg   [0:0] icmp_ln155_1_reg_787_pp0_iter4_reg;
reg   [0:0] icmp_ln155_1_reg_787_pp0_iter5_reg;
reg   [0:0] icmp_ln155_1_reg_787_pp0_iter6_reg;
reg   [0:0] icmp_ln155_1_reg_787_pp0_iter7_reg;
reg   [0:0] icmp_ln155_1_reg_787_pp0_iter8_reg;
wire   [5:0] empty_292_fu_445_p2;
reg   [5:0] empty_292_reg_791;
reg   [5:0] empty_292_reg_791_pp0_iter4_reg;
reg   [5:0] empty_292_reg_791_pp0_iter5_reg;
reg   [5:0] empty_292_reg_791_pp0_iter6_reg;
reg   [5:0] empty_292_reg_791_pp0_iter7_reg;
reg   [5:0] empty_292_reg_791_pp0_iter8_reg;
wire   [2:0] select_ln153_fu_479_p3;
reg   [2:0] select_ln153_reg_806;
reg   [2:0] select_ln153_reg_806_pp0_iter5_reg;
reg   [2:0] select_ln153_reg_806_pp0_iter6_reg;
reg   [2:0] select_ln153_reg_806_pp0_iter7_reg;
reg   [8:0] conv5_b_load_reg_846;
wire   [13:0] val_4_fu_619_p3;
reg   [13:0] val_4_reg_856;
wire   [63:0] zext_ln157_fu_495_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln158_fu_500_p1;
wire   [63:0] zext_ln151_fu_517_p1;
wire   [63:0] zext_ln162_fu_639_p1;
reg   [31:0] acc_fu_92;
wire  signed [31:0] grp_fu_662_p3;
reg   [31:0] ap_sig_allocacmp_acc_load;
wire    ap_loop_init;
reg   [8:0] ic_fu_96;
wire   [8:0] add_ln155_fu_345_p2;
reg   [2:0] ow_fu_100;
reg   [11:0] indvar_flatten21_fu_104;
wire   [11:0] select_ln153_1_fu_363_p3;
reg   [2:0] oh_fu_108;
wire   [2:0] select_ln152_fu_426_p3;
reg   [14:0] indvar_flatten35_fu_112;
wire   [14:0] select_ln152_1_fu_377_p3;
reg   [10:0] oc_fu_116;
reg   [24:0] indvar_flatten59_fu_120;
wire   [24:0] add_ln151_fu_231_p2;
reg    c5_in_ce0_local;
reg    conv5_w_ce0_local;
reg    conv5_b_ce0_local;
reg    c5_out_we0_local;
reg    c5_out_ce0_local;
wire   [0:0] icmp_ln153_fu_261_p2;
wire   [0:0] xor_ln151_fu_249_p2;
wire   [10:0] add_ln151_1_fu_273_p2;
wire   [0:0] exitcond_flatten23_not_fu_293_p2;
wire   [0:0] icmp_ln155_fu_255_p2;
wire   [0:0] and_ln151_fu_305_p2;
wire   [0:0] not_exitcond_flatten23_mid258_fu_299_p2;
wire   [0:0] empty_288_fu_317_p2;
wire   [11:0] add_ln153_1_fu_357_p2;
wire   [14:0] add_ln152_1_fu_371_p2;
wire   [2:0] select_ln151_fu_413_p3;
wire   [2:0] add_ln152_fu_420_p2;
wire   [5:0] p_shl_fu_437_p3;
wire   [5:0] zext_ln152_fu_433_p1;
wire   [2:0] ow_mid228_fu_466_p3;
wire   [2:0] add_ln153_fu_473_p2;
wire   [14:0] grp_fu_653_p3;
wire   [14:0] zext_ln153_2_fu_486_p1;
(* use_dsp48 = "no" *) wire   [14:0] add_ln157_fu_490_p2;
wire   [18:0] grp_fu_644_p3;
wire   [23:0] trunc_ln_fu_540_p4;
wire  signed [24:0] sext_ln52_fu_549_p1;
wire  signed [24:0] sext_ln152_fu_534_p1;
wire   [24:0] result_fu_553_p2;
wire   [10:0] tmp_1_fu_559_p4;
wire   [0:0] icmp_ln39_fu_569_p2;
wire   [0:0] icmp_ln40_fu_575_p2;
wire   [0:0] or_ln39_fu_593_p2;
wire   [14:0] select_ln39_fu_585_p3;
wire   [14:0] trunc_ln41_fu_581_p1;
wire   [14:0] val_fu_599_p3;
wire   [0:0] tmp_41_fu_611_p3;
wire   [13:0] trunc_ln160_fu_607_p1;
wire   [15:0] grp_fu_672_p3;
wire   [15:0] zext_ln153_1_fu_631_p1;
(* use_dsp48 = "no" *) wire   [15:0] add_ln162_fu_634_p2;
wire   [10:0] grp_fu_644_p0;
wire   [8:0] grp_fu_644_p1;
wire   [8:0] grp_fu_644_p2;
wire   [8:0] grp_fu_653_p0;
wire   [5:0] grp_fu_653_p1;
wire   [5:0] grp_fu_653_p2;
wire  signed [31:0] grp_fu_662_p2;
wire   [10:0] grp_fu_672_p0;
wire   [5:0] grp_fu_672_p1;
wire   [2:0] grp_fu_672_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [18:0] grp_fu_644_p00;
wire   [18:0] grp_fu_644_p20;
wire   [14:0] grp_fu_653_p00;
wire   [14:0] grp_fu_653_p20;
wire   [15:0] grp_fu_672_p00;
wire   [15:0] grp_fu_672_p20;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 acc_fu_92 = 32'd0;
#0 ic_fu_96 = 9'd0;
#0 ow_fu_100 = 3'd0;
#0 indvar_flatten21_fu_104 = 12'd0;
#0 oh_fu_108 = 3'd0;
#0 indvar_flatten35_fu_112 = 15'd0;
#0 oc_fu_116 = 11'd0;
#0 indvar_flatten59_fu_120 = 25'd0;
#0 ap_done_reg = 1'b0;
end

Shuffle_Model_conv5_avgpool_Pipeline_VITIS_LOOP_151_1_VITIS_LOOP_152_2_VITIS_LOOP_153_3_VITncg #(
    .DataWidth( 9 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
conv5_b_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(conv5_b_address0),
    .ce0(conv5_b_ce0_local),
    .q0(conv5_b_q0)
);

Shuffle_Model_conv5_avgpool_Pipeline_VITIS_LOOP_151_1_VITIS_LOOP_152_2_VITIS_LOOP_153_3_VITocq #(
    .DataWidth( 8 ),
    .AddressRange( 475136 ),
    .AddressWidth( 19 ))
conv5_w_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(conv5_w_address0),
    .ce0(conv5_w_ce0_local),
    .q0(conv5_w_q0)
);

Shuffle_Model_mac_muladd_11ns_9ns_9ns_19_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 9 ),
    .dout_WIDTH( 19 ))
mac_muladd_11ns_9ns_9ns_19_4_1_U578(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_644_p0),
    .din1(grp_fu_644_p1),
    .din2(grp_fu_644_p2),
    .ce(1'b1),
    .dout(grp_fu_644_p3)
);

Shuffle_Model_mac_muladd_9ns_6ns_6ns_15_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mac_muladd_9ns_6ns_6ns_15_4_1_U579(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_653_p0),
    .din1(grp_fu_653_p1),
    .din2(grp_fu_653_p2),
    .ce(1'b1),
    .dout(grp_fu_653_p3)
);

Shuffle_Model_mac_muladd_16s_8s_32s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_8s_32s_32_4_1_U580(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(c5_in_q0),
    .din1(conv5_w_q0),
    .din2(grp_fu_662_p2),
    .ce(1'b1),
    .dout(grp_fu_662_p3)
);

Shuffle_Model_mac_muladd_11ns_6ns_3ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
mac_muladd_11ns_6ns_3ns_16_4_1_U581(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_672_p0),
    .din1(grp_fu_672_p1),
    .din2(grp_fu_672_p2),
    .ce(1'b1),
    .dout(grp_fu_672_p3)
);

Shuffle_Model_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_fu_92 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter8 == 1'b1)) begin
            acc_fu_92 <= grp_fu_662_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ic_fu_96 <= 9'd0;
        end else if (((icmp_ln151_fu_225_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            ic_fu_96 <= add_ln155_fu_345_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten21_fu_104 <= 12'd0;
        end else if (((icmp_ln151_fu_225_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten21_fu_104 <= select_ln153_1_fu_363_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten35_fu_112 <= 15'd0;
        end else if (((icmp_ln151_fu_225_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten35_fu_112 <= select_ln152_1_fu_377_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten59_fu_120 <= 25'd0;
        end else if (((icmp_ln151_fu_225_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten59_fu_120 <= add_ln151_fu_231_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            oc_fu_116 <= 11'd0;
        end else if (((icmp_ln151_fu_225_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            oc_fu_116 <= select_ln151_1_fu_279_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            oh_fu_108 <= 3'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            oh_fu_108 <= select_ln152_fu_426_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ow_fu_100 <= 3'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            ow_fu_100 <= select_ln153_fu_479_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln151_1_reg_746 <= and_ln151_1_fu_267_p2;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        empty_289_reg_767 <= empty_289_fu_323_p2;
        empty_reg_757 <= empty_fu_287_p2;
        ic_mid2_reg_772 <= ic_mid2_fu_329_p3;
        icmp_ln152_reg_741 <= icmp_ln152_fu_243_p2;
        icmp_ln155_1_reg_787 <= icmp_ln155_1_fu_351_p2;
        icmp_ln155_mid234_reg_762 <= icmp_ln155_mid234_fu_311_p2;
        select_ln151_1_reg_751 <= select_ln151_1_fu_279_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        and_ln151_1_reg_746_pp0_iter2_reg <= and_ln151_1_reg_746;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        conv5_b_load_reg_846 <= conv5_b_q0;
        empty_289_reg_767_pp0_iter2_reg <= empty_289_reg_767;
        empty_289_reg_767_pp0_iter3_reg <= empty_289_reg_767_pp0_iter2_reg;
        empty_289_reg_767_pp0_iter4_reg <= empty_289_reg_767_pp0_iter3_reg;
        empty_289_reg_767_pp0_iter5_reg <= empty_289_reg_767_pp0_iter4_reg;
        empty_289_reg_767_pp0_iter6_reg <= empty_289_reg_767_pp0_iter5_reg;
        empty_292_reg_791 <= empty_292_fu_445_p2;
        empty_292_reg_791_pp0_iter4_reg <= empty_292_reg_791;
        empty_292_reg_791_pp0_iter5_reg <= empty_292_reg_791_pp0_iter4_reg;
        empty_292_reg_791_pp0_iter6_reg <= empty_292_reg_791_pp0_iter5_reg;
        empty_292_reg_791_pp0_iter7_reg <= empty_292_reg_791_pp0_iter6_reg;
        empty_292_reg_791_pp0_iter8_reg <= empty_292_reg_791_pp0_iter7_reg;
        empty_reg_757_pp0_iter2_reg <= empty_reg_757;
        empty_reg_757_pp0_iter3_reg <= empty_reg_757_pp0_iter2_reg;
        ic_mid2_reg_772_pp0_iter2_reg <= ic_mid2_reg_772;
        icmp_ln152_reg_741_pp0_iter2_reg <= icmp_ln152_reg_741;
        icmp_ln155_1_reg_787_pp0_iter2_reg <= icmp_ln155_1_reg_787;
        icmp_ln155_1_reg_787_pp0_iter3_reg <= icmp_ln155_1_reg_787_pp0_iter2_reg;
        icmp_ln155_1_reg_787_pp0_iter4_reg <= icmp_ln155_1_reg_787_pp0_iter3_reg;
        icmp_ln155_1_reg_787_pp0_iter5_reg <= icmp_ln155_1_reg_787_pp0_iter4_reg;
        icmp_ln155_1_reg_787_pp0_iter6_reg <= icmp_ln155_1_reg_787_pp0_iter5_reg;
        icmp_ln155_1_reg_787_pp0_iter7_reg <= icmp_ln155_1_reg_787_pp0_iter6_reg;
        icmp_ln155_1_reg_787_pp0_iter8_reg <= icmp_ln155_1_reg_787_pp0_iter7_reg;
        icmp_ln155_mid234_reg_762_pp0_iter2_reg <= icmp_ln155_mid234_reg_762;
        icmp_ln155_mid234_reg_762_pp0_iter3_reg <= icmp_ln155_mid234_reg_762_pp0_iter2_reg;
        select_ln151_1_reg_751_pp0_iter2_reg <= select_ln151_1_reg_751;
        select_ln151_1_reg_751_pp0_iter3_reg <= select_ln151_1_reg_751_pp0_iter2_reg;
        select_ln151_1_reg_751_pp0_iter4_reg <= select_ln151_1_reg_751_pp0_iter3_reg;
        select_ln151_1_reg_751_pp0_iter5_reg <= select_ln151_1_reg_751_pp0_iter4_reg;
        select_ln153_reg_806 <= select_ln153_fu_479_p3;
        select_ln153_reg_806_pp0_iter5_reg <= select_ln153_reg_806;
        select_ln153_reg_806_pp0_iter6_reg <= select_ln153_reg_806_pp0_iter5_reg;
        select_ln153_reg_806_pp0_iter7_reg <= select_ln153_reg_806_pp0_iter6_reg;
        val_4_reg_856 <= val_4_fu_619_p3;
    end
end

always @ (*) begin
    if (((icmp_ln151_fu_225_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        ap_sig_allocacmp_acc_load = grp_fu_662_p3;
    end else begin
        ap_sig_allocacmp_acc_load = acc_fu_92;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        c5_in_ce0_local = 1'b1;
    end else begin
        c5_in_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        c5_out_ce0_local = 1'b1;
    end else begin
        c5_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (icmp_ln155_1_reg_787_pp0_iter8_reg == 1'd1))) begin
        c5_out_we0_local = 1'b1;
    end else begin
        c5_out_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        conv5_b_ce0_local = 1'b1;
    end else begin
        conv5_b_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        conv5_w_ce0_local = 1'b1;
    end else begin
        conv5_w_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln151_1_fu_273_p2 = (oc_fu_116 + 11'd1);

assign add_ln151_fu_231_p2 = (indvar_flatten59_fu_120 + 25'd1);

assign add_ln152_1_fu_371_p2 = (indvar_flatten35_fu_112 + 15'd1);

assign add_ln152_fu_420_p2 = (select_ln151_fu_413_p3 + 3'd1);

assign add_ln153_1_fu_357_p2 = (indvar_flatten21_fu_104 + 12'd1);

assign add_ln153_fu_473_p2 = (ow_mid228_fu_466_p3 + 3'd1);

assign add_ln155_fu_345_p2 = (ic_mid2_fu_329_p3 + 9'd1);

assign add_ln157_fu_490_p2 = (grp_fu_653_p3 + zext_ln153_2_fu_486_p1);

assign add_ln162_fu_634_p2 = (grp_fu_672_p3 + zext_ln153_1_fu_631_p1);

assign and_ln151_1_fu_267_p2 = (xor_ln151_fu_249_p2 & icmp_ln153_fu_261_p2);

assign and_ln151_fu_305_p2 = (xor_ln151_fu_249_p2 & icmp_ln155_fu_255_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign c5_in_address0 = zext_ln157_fu_495_p1;

assign c5_in_ce0 = c5_in_ce0_local;

assign c5_out_address0 = zext_ln162_fu_639_p1;

assign c5_out_ce0 = c5_out_ce0_local;

assign c5_out_d0 = val_4_reg_856;

assign c5_out_we0 = c5_out_we0_local;

assign conv5_b_address0 = zext_ln151_fu_517_p1;

assign conv5_w_address0 = zext_ln158_fu_500_p1;

assign empty_288_fu_317_p2 = (icmp_ln155_mid234_fu_311_p2 | and_ln151_1_fu_267_p2);

assign empty_289_fu_323_p2 = (icmp_ln152_fu_243_p2 | empty_288_fu_317_p2);

assign empty_292_fu_445_p2 = (p_shl_fu_437_p3 - zext_ln152_fu_433_p1);

assign empty_fu_287_p2 = (icmp_ln152_fu_243_p2 | and_ln151_1_fu_267_p2);

assign exitcond_flatten23_not_fu_293_p2 = (icmp_ln153_fu_261_p2 ^ 1'd1);

assign grp_fu_644_p0 = grp_fu_644_p00;

assign grp_fu_644_p00 = select_ln151_1_fu_279_p3;

assign grp_fu_644_p1 = 19'd464;

assign grp_fu_644_p2 = grp_fu_644_p20;

assign grp_fu_644_p20 = ic_mid2_reg_772_pp0_iter2_reg;

assign grp_fu_653_p0 = grp_fu_653_p00;

assign grp_fu_653_p00 = ic_mid2_fu_329_p3;

assign grp_fu_653_p1 = 15'd49;

assign grp_fu_653_p2 = grp_fu_653_p20;

assign grp_fu_653_p20 = empty_292_fu_445_p2;

assign grp_fu_662_p2 = ((empty_289_reg_767_pp0_iter6_reg[0:0] == 1'b1) ? 32'd0 : ap_sig_allocacmp_acc_load);

assign grp_fu_672_p0 = grp_fu_672_p00;

assign grp_fu_672_p00 = select_ln151_1_reg_751_pp0_iter5_reg;

assign grp_fu_672_p1 = 16'd49;

assign grp_fu_672_p2 = grp_fu_672_p20;

assign grp_fu_672_p20 = select_ln153_reg_806_pp0_iter7_reg;

assign ic_mid2_fu_329_p3 = ((empty_289_fu_323_p2[0:0] == 1'b1) ? 9'd0 : ic_fu_96);

assign icmp_ln151_fu_225_p2 = ((indvar_flatten59_fu_120 == 25'd23281664) ? 1'b1 : 1'b0);

assign icmp_ln152_fu_243_p2 = ((indvar_flatten35_fu_112 == 15'd22736) ? 1'b1 : 1'b0);

assign icmp_ln153_fu_261_p2 = ((indvar_flatten21_fu_104 == 12'd3248) ? 1'b1 : 1'b0);

assign icmp_ln155_1_fu_351_p2 = ((add_ln155_fu_345_p2 == 9'd464) ? 1'b1 : 1'b0);

assign icmp_ln155_fu_255_p2 = ((ic_fu_96 == 9'd464) ? 1'b1 : 1'b0);

assign icmp_ln155_mid234_fu_311_p2 = (not_exitcond_flatten23_mid258_fu_299_p2 & and_ln151_fu_305_p2);

assign icmp_ln39_fu_569_p2 = (($signed(tmp_1_fu_559_p4) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign icmp_ln40_fu_575_p2 = (($signed(result_fu_553_p2) < $signed(25'd33538048)) ? 1'b1 : 1'b0);

assign not_exitcond_flatten23_mid258_fu_299_p2 = (icmp_ln152_fu_243_p2 | exitcond_flatten23_not_fu_293_p2);

assign or_ln39_fu_593_p2 = (icmp_ln40_fu_575_p2 | icmp_ln39_fu_569_p2);

assign ow_mid228_fu_466_p3 = ((empty_reg_757_pp0_iter3_reg[0:0] == 1'b1) ? 3'd0 : ow_fu_100);

assign p_shl_fu_437_p3 = {{select_ln152_fu_426_p3}, {3'd0}};

assign result_fu_553_p2 = ($signed(sext_ln52_fu_549_p1) + $signed(sext_ln152_fu_534_p1));

assign select_ln151_1_fu_279_p3 = ((icmp_ln152_fu_243_p2[0:0] == 1'b1) ? add_ln151_1_fu_273_p2 : oc_fu_116);

assign select_ln151_fu_413_p3 = ((icmp_ln152_reg_741_pp0_iter2_reg[0:0] == 1'b1) ? 3'd0 : oh_fu_108);

assign select_ln152_1_fu_377_p3 = ((icmp_ln152_fu_243_p2[0:0] == 1'b1) ? 15'd1 : add_ln152_1_fu_371_p2);

assign select_ln152_fu_426_p3 = ((and_ln151_1_reg_746_pp0_iter2_reg[0:0] == 1'b1) ? add_ln152_fu_420_p2 : select_ln151_fu_413_p3);

assign select_ln153_1_fu_363_p3 = ((empty_fu_287_p2[0:0] == 1'b1) ? 12'd1 : add_ln153_1_fu_357_p2);

assign select_ln153_fu_479_p3 = ((icmp_ln155_mid234_reg_762_pp0_iter3_reg[0:0] == 1'b1) ? add_ln153_fu_473_p2 : ow_mid228_fu_466_p3);

assign select_ln39_fu_585_p3 = ((icmp_ln39_fu_569_p2[0:0] == 1'b1) ? 15'd16383 : 15'd16384);

assign sext_ln152_fu_534_p1 = $signed(conv5_b_load_reg_846);

assign sext_ln52_fu_549_p1 = $signed(trunc_ln_fu_540_p4);

assign tmp_1_fu_559_p4 = {{result_fu_553_p2[24:14]}};

assign tmp_41_fu_611_p3 = val_fu_599_p3[32'd14];

assign trunc_ln160_fu_607_p1 = val_fu_599_p3[13:0];

assign trunc_ln41_fu_581_p1 = result_fu_553_p2[14:0];

assign trunc_ln_fu_540_p4 = {{grp_fu_662_p3[31:8]}};

assign val_4_fu_619_p3 = ((tmp_41_fu_611_p3[0:0] == 1'b1) ? 14'd0 : trunc_ln160_fu_607_p1);

assign val_fu_599_p3 = ((or_ln39_fu_593_p2[0:0] == 1'b1) ? select_ln39_fu_585_p3 : trunc_ln41_fu_581_p1);

assign xor_ln151_fu_249_p2 = (icmp_ln152_fu_243_p2 ^ 1'd1);

assign zext_ln151_fu_517_p1 = select_ln151_1_reg_751_pp0_iter5_reg;

assign zext_ln152_fu_433_p1 = select_ln152_fu_426_p3;

assign zext_ln153_1_fu_631_p1 = empty_292_reg_791_pp0_iter8_reg;

assign zext_ln153_2_fu_486_p1 = select_ln153_fu_479_p3;

assign zext_ln157_fu_495_p1 = add_ln157_fu_490_p2;

assign zext_ln158_fu_500_p1 = grp_fu_644_p3;

assign zext_ln162_fu_639_p1 = add_ln162_fu_634_p2;

endmodule //Shuffle_Model_conv5_avgpool_Pipeline_VITIS_LOOP_151_1_VITIS_LOOP_152_2_VITIS_LOOP_153_3_VITIS_s
