// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Shuffle_Model_shuffle_block_s1_6_Pipeline_VITIS_LOOP_183_1_VITIS_LOOP_184_2_VITIS_LOOP_185_3_V (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        b2_dw_b_address0,
        b2_dw_b_ce0,
        b2_dw_b_q0,
        b2_dw_w_address0,
        b2_dw_w_ce0,
        b2_dw_w_q0,
        temp_dw_out_address0,
        temp_dw_out_ce0,
        temp_dw_out_we0,
        temp_dw_out_d0,
        temp_dw_in_address0,
        temp_dw_in_ce0,
        temp_dw_in_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] b2_dw_b_address0;
output   b2_dw_b_ce0;
input  [10:0] b2_dw_b_q0;
output  [11:0] b2_dw_w_address0;
output   b2_dw_w_ce0;
input  [14:0] b2_dw_w_q0;
output  [15:0] temp_dw_out_address0;
output   temp_dw_out_ce0;
output   temp_dw_out_we0;
output  [15:0] temp_dw_out_d0;
output  [15:0] temp_dw_in_address0;
output   temp_dw_in_ce0;
input  [13:0] temp_dw_in_q0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln183_fu_250_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln183_reg_945;
reg   [0:0] icmp_ln183_reg_945_pp0_iter2_reg;
wire   [0:0] icmp_ln184_fu_265_p2;
reg   [0:0] icmp_ln184_reg_949;
reg   [0:0] icmp_ln184_reg_949_pp0_iter2_reg;
wire   [7:0] select_ln183_3_fu_277_p3;
reg   [7:0] select_ln183_3_reg_958;
reg   [7:0] select_ln183_3_reg_958_pp0_iter2_reg;
reg   [7:0] select_ln183_3_reg_958_pp0_iter3_reg;
reg   [7:0] select_ln183_3_reg_958_pp0_iter4_reg;
wire   [2:0] select_ln184_fu_426_p3;
reg   [2:0] select_ln184_reg_971;
reg   [2:0] select_ln184_reg_971_pp0_iter4_reg;
reg   [2:0] select_ln184_reg_971_pp0_iter5_reg;
reg   [2:0] select_ln184_reg_971_pp0_iter6_reg;
wire   [0:0] empty_146_fu_446_p2;
reg   [0:0] empty_146_reg_978;
reg   [0:0] empty_146_reg_978_pp0_iter4_reg;
reg   [0:0] empty_146_reg_978_pp0_iter5_reg;
wire   [2:0] select_ln185_fu_471_p3;
reg   [2:0] select_ln185_reg_983;
reg   [2:0] select_ln185_reg_983_pp0_iter4_reg;
reg   [2:0] select_ln185_reg_983_pp0_iter5_reg;
wire   [1:0] kw_mid2_fu_497_p3;
reg   [1:0] kw_mid2_reg_988;
wire   [1:0] select_ln187_fu_505_p3;
reg   [1:0] select_ln187_reg_994;
wire   [0:0] icmp_ln188_2_fu_523_p2;
reg   [0:0] icmp_ln188_2_reg_1005;
reg   [0:0] icmp_ln188_2_reg_1005_pp0_iter4_reg;
reg   [0:0] icmp_ln188_2_reg_1005_pp0_iter5_reg;
reg   [0:0] icmp_ln188_2_reg_1005_pp0_iter6_reg;
wire   [0:0] icmp_ln187_2_fu_529_p2;
reg   [0:0] icmp_ln187_2_reg_1009;
reg   [0:0] icmp_ln187_2_reg_1009_pp0_iter4_reg;
reg   [0:0] icmp_ln187_2_reg_1009_pp0_iter5_reg;
reg   [0:0] icmp_ln187_2_reg_1009_pp0_iter6_reg;
wire   [28:0] mul_ln193_fu_718_p2;
reg   [28:0] mul_ln193_reg_1033;
wire   [14:0] select_ln39_fu_810_p3;
reg   [14:0] select_ln39_reg_1043;
reg    ap_condition_exit_pp0_iter3_stage0;
wire   [63:0] zext_ln192_2_fu_684_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln193_2_fu_701_p1;
wire   [63:0] zext_ln183_fu_706_p1;
wire   [63:0] zext_ln197_fu_852_p1;
reg   [63:0] acc_5_fu_102;
wire   [63:0] acc_fu_744_p2;
wire    ap_loop_init;
reg   [1:0] kw_fu_106;
wire   [1:0] add_ln188_fu_517_p2;
reg   [1:0] kh_fu_110;
reg   [3:0] indvar_flatten65_fu_114;
wire   [3:0] select_ln187_3_fu_541_p3;
reg   [2:0] ow_fu_118;
reg   [6:0] indvar_flatten80_fu_122;
wire   [6:0] select_ln185_2_fu_555_p3;
reg   [2:0] oh_fu_126;
reg   [8:0] indvar_flatten105_fu_130;
wire   [8:0] select_ln184_2_fu_295_p3;
reg   [7:0] c_fu_134;
reg   [16:0] indvar_flatten140_fu_138;
wire   [16:0] add_ln183_fu_256_p2;
reg    temp_dw_in_ce0_local;
reg    b2_dw_w_ce0_local;
reg    b2_dw_b_ce0_local;
reg    temp_dw_out_we0_local;
wire  signed [15:0] sext_ln197_fu_843_p1;
reg    temp_dw_out_ce0_local;
wire   [7:0] add_ln183_2_fu_271_p2;
wire   [8:0] add_ln184_2_fu_289_p2;
wire   [0:0] icmp_ln188_fu_348_p2;
wire   [0:0] xor_ln183_fu_343_p2;
wire   [0:0] icmp_ln185_fu_366_p2;
wire   [2:0] select_ln183_fu_336_p3;
wire   [0:0] and_ln183_4_fu_372_p2;
wire   [0:0] empty_fu_384_p2;
wire   [0:0] exitcond_flatten82_not_fu_397_p2;
wire   [0:0] and_ln183_fu_354_p2;
wire   [0:0] not_exitcond_flatten82_mid2139_fu_403_p2;
wire   [0:0] icmp_ln187_fu_360_p2;
wire   [0:0] and_ln183_3_fu_414_p2;
wire   [2:0] add_ln184_fu_378_p2;
wire   [2:0] ow_mid287_fu_389_p3;
wire   [0:0] exitcond_flatten67_mid2104_fu_420_p2;
wire   [0:0] empty_145_fu_440_p2;
wire   [0:0] icmp_ln188_mid2100_fu_408_p2;
wire   [0:0] not_exitcond_flatten67_mid2104_fu_459_p2;
wire   [2:0] add_ln185_fu_434_p2;
wire   [1:0] kh_mid272_fu_451_p3;
wire   [0:0] empty_147_fu_485_p2;
wire   [0:0] icmp_ln188_mid279_fu_465_p2;
wire   [0:0] empty_148_fu_491_p2;
wire   [1:0] add_ln187_fu_479_p2;
wire   [3:0] add_ln187_2_fu_535_p2;
wire   [6:0] add_ln185_2_fu_549_p2;
wire   [10:0] tmp_1_fu_599_p3;
wire   [11:0] p_shl4_fu_606_p1;
wire   [11:0] zext_ln183_6_fu_596_p1;
wire   [3:0] zext_ln187_fu_619_p1;
wire   [3:0] zext_ln184_fu_616_p1;
wire   [3:0] empty_153_fu_622_p2;
wire   [6:0] p_shl2_fu_632_p3;
wire   [6:0] p_cast17_fu_628_p1;
wire   [3:0] p_shl_fu_646_p3;
wire   [3:0] empty_155_fu_653_p2;
wire   [6:0] empty_154_fu_640_p2;
wire   [6:0] zext_ln188_4_fu_666_p1;
wire   [6:0] add_ln192_5_fu_669_p2;
wire   [14:0] zext_ln192_fu_675_p1;
wire   [14:0] grp_fu_857_p3;
(* use_dsp48 = "no" *) wire   [14:0] add_ln192_fu_679_p2;
wire   [11:0] empty_149_fu_610_p2;
wire   [11:0] zext_ln188_3_fu_663_p1;
wire   [11:0] add_ln193_2_fu_689_p2;
wire   [11:0] zext_ln188_fu_659_p1;
wire   [11:0] add_ln193_fu_695_p2;
wire   [13:0] mul_ln193_fu_718_p1;
wire  signed [63:0] sext_ln192_fu_741_p1;
wire   [63:0] acc_8_mid275_fu_727_p3;
wire   [55:0] trunc_ln_fu_750_p4;
wire  signed [56:0] sext_ln198_fu_760_p1;
wire  signed [56:0] sext_ln184_fu_734_p1;
wire   [56:0] add_ln198_fu_764_p2;
wire   [42:0] tmp_19_fu_770_p4;
wire   [0:0] icmp_ln39_fu_780_p2;
wire   [0:0] icmp_ln40_fu_786_p2;
wire   [0:0] or_ln39_fu_804_p2;
wire   [14:0] select_ln39_5_fu_796_p3;
wire   [14:0] trunc_ln41_fu_792_p1;
wire   [5:0] p_shl3_fu_826_p3;
wire   [5:0] zext_ln184_2_fu_823_p1;
wire   [5:0] empty_152_fu_833_p2;
wire   [13:0] grp_fu_866_p3;
wire   [13:0] zext_ln185_fu_839_p1;
(* use_dsp48 = "no" *) wire   [13:0] add_ln197_fu_847_p2;
wire   [7:0] grp_fu_857_p0;
wire   [6:0] grp_fu_857_p1;
wire   [2:0] grp_fu_857_p2;
wire   [7:0] grp_fu_866_p0;
wire   [5:0] grp_fu_866_p1;
wire   [2:0] grp_fu_866_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [14:0] grp_fu_857_p00;
wire   [14:0] grp_fu_857_p20;
wire   [13:0] grp_fu_866_p00;
wire   [13:0] grp_fu_866_p20;
wire   [28:0] mul_ln193_fu_718_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 acc_5_fu_102 = 64'd0;
#0 kw_fu_106 = 2'd0;
#0 kh_fu_110 = 2'd0;
#0 indvar_flatten65_fu_114 = 4'd0;
#0 ow_fu_118 = 3'd0;
#0 indvar_flatten80_fu_122 = 7'd0;
#0 oh_fu_126 = 3'd0;
#0 indvar_flatten105_fu_130 = 9'd0;
#0 c_fu_134 = 8'd0;
#0 indvar_flatten140_fu_138 = 17'd0;
#0 ap_done_reg = 1'b0;
end

Shuffle_Model_mul_15s_14ns_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 29 ))
mul_15s_14ns_29_1_1_U491(
    .din0(b2_dw_w_q0),
    .din1(mul_ln193_fu_718_p1),
    .dout(mul_ln193_fu_718_p2)
);

Shuffle_Model_mac_muladd_8ns_7ns_3ns_15_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 3 ),
    .dout_WIDTH( 15 ))
mac_muladd_8ns_7ns_3ns_15_4_1_U492(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_857_p0),
    .din1(grp_fu_857_p1),
    .din2(grp_fu_857_p2),
    .ce(1'b1),
    .dout(grp_fu_857_p3)
);

Shuffle_Model_mac_muladd_8ns_6ns_3ns_14_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 3 ),
    .dout_WIDTH( 14 ))
mac_muladd_8ns_6ns_3ns_14_4_1_U493(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_866_p0),
    .din1(grp_fu_866_p1),
    .din2(grp_fu_866_p2),
    .ce(1'b1),
    .dout(grp_fu_866_p3)
);

Shuffle_Model_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter3_stage0)) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_5_fu_102 <= 64'd0;
        end else if ((ap_enable_reg_pp0_iter6 == 1'b1)) begin
            acc_5_fu_102 <= acc_fu_744_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            c_fu_134 <= 8'd0;
        end else if (((icmp_ln183_fu_250_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            c_fu_134 <= select_ln183_3_fu_277_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten105_fu_130 <= 9'd0;
        end else if (((icmp_ln183_fu_250_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten105_fu_130 <= select_ln184_2_fu_295_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten140_fu_138 <= 17'd0;
        end else if (((icmp_ln183_fu_250_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten140_fu_138 <= add_ln183_fu_256_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            indvar_flatten65_fu_114 <= 4'd0;
        end else if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln183_reg_945_pp0_iter2_reg == 1'd0))) begin
            indvar_flatten65_fu_114 <= select_ln187_3_fu_541_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            indvar_flatten80_fu_122 <= 7'd0;
        end else if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln183_reg_945_pp0_iter2_reg == 1'd0))) begin
            indvar_flatten80_fu_122 <= select_ln185_2_fu_555_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            kh_fu_110 <= 2'd0;
        end else if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln183_reg_945_pp0_iter2_reg == 1'd0))) begin
            kh_fu_110 <= select_ln187_fu_505_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            kw_fu_106 <= 2'd0;
        end else if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln183_reg_945_pp0_iter2_reg == 1'd0))) begin
            kw_fu_106 <= add_ln188_fu_517_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            oh_fu_126 <= 3'd0;
        end else if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln183_reg_945_pp0_iter2_reg == 1'd0))) begin
            oh_fu_126 <= select_ln184_fu_426_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ow_fu_118 <= 3'd0;
        end else if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln183_reg_945_pp0_iter2_reg == 1'd0))) begin
            ow_fu_118 <= select_ln185_fu_471_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln183_reg_945 <= icmp_ln183_fu_250_p2;
        icmp_ln184_reg_949 <= icmp_ln184_fu_265_p2;
        select_ln183_3_reg_958 <= select_ln183_3_fu_277_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        empty_146_reg_978 <= empty_146_fu_446_p2;
        empty_146_reg_978_pp0_iter4_reg <= empty_146_reg_978;
        empty_146_reg_978_pp0_iter5_reg <= empty_146_reg_978_pp0_iter4_reg;
        icmp_ln183_reg_945_pp0_iter2_reg <= icmp_ln183_reg_945;
        icmp_ln184_reg_949_pp0_iter2_reg <= icmp_ln184_reg_949;
        icmp_ln187_2_reg_1009 <= icmp_ln187_2_fu_529_p2;
        icmp_ln187_2_reg_1009_pp0_iter4_reg <= icmp_ln187_2_reg_1009;
        icmp_ln187_2_reg_1009_pp0_iter5_reg <= icmp_ln187_2_reg_1009_pp0_iter4_reg;
        icmp_ln187_2_reg_1009_pp0_iter6_reg <= icmp_ln187_2_reg_1009_pp0_iter5_reg;
        icmp_ln188_2_reg_1005 <= icmp_ln188_2_fu_523_p2;
        icmp_ln188_2_reg_1005_pp0_iter4_reg <= icmp_ln188_2_reg_1005;
        icmp_ln188_2_reg_1005_pp0_iter5_reg <= icmp_ln188_2_reg_1005_pp0_iter4_reg;
        icmp_ln188_2_reg_1005_pp0_iter6_reg <= icmp_ln188_2_reg_1005_pp0_iter5_reg;
        kw_mid2_reg_988 <= kw_mid2_fu_497_p3;
        mul_ln193_reg_1033 <= mul_ln193_fu_718_p2;
        select_ln183_3_reg_958_pp0_iter2_reg <= select_ln183_3_reg_958;
        select_ln183_3_reg_958_pp0_iter3_reg <= select_ln183_3_reg_958_pp0_iter2_reg;
        select_ln183_3_reg_958_pp0_iter4_reg <= select_ln183_3_reg_958_pp0_iter3_reg;
        select_ln184_reg_971 <= select_ln184_fu_426_p3;
        select_ln184_reg_971_pp0_iter4_reg <= select_ln184_reg_971;
        select_ln184_reg_971_pp0_iter5_reg <= select_ln184_reg_971_pp0_iter4_reg;
        select_ln184_reg_971_pp0_iter6_reg <= select_ln184_reg_971_pp0_iter5_reg;
        select_ln185_reg_983 <= select_ln185_fu_471_p3;
        select_ln185_reg_983_pp0_iter4_reg <= select_ln185_reg_983;
        select_ln185_reg_983_pp0_iter5_reg <= select_ln185_reg_983_pp0_iter4_reg;
        select_ln187_reg_994 <= select_ln187_fu_505_p3;
        select_ln39_reg_1043 <= select_ln39_fu_810_p3;
    end
end

always @ (*) begin
    if (((icmp_ln183_fu_250_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln183_reg_945_pp0_iter2_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        b2_dw_b_ce0_local = 1'b1;
    end else begin
        b2_dw_b_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        b2_dw_w_ce0_local = 1'b1;
    end else begin
        b2_dw_w_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        temp_dw_in_ce0_local = 1'b1;
    end else begin
        temp_dw_in_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        temp_dw_out_ce0_local = 1'b1;
    end else begin
        temp_dw_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln187_2_reg_1009_pp0_iter6_reg == 1'd1) & (icmp_ln188_2_reg_1005_pp0_iter6_reg == 1'd1))) begin
        temp_dw_out_we0_local = 1'b1;
    end else begin
        temp_dw_out_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_8_mid275_fu_727_p3 = ((empty_146_reg_978_pp0_iter5_reg[0:0] == 1'b1) ? 64'd0 : acc_5_fu_102);

assign acc_fu_744_p2 = ($signed(sext_ln192_fu_741_p1) + $signed(acc_8_mid275_fu_727_p3));

assign add_ln183_2_fu_271_p2 = (c_fu_134 + 8'd1);

assign add_ln183_fu_256_p2 = (indvar_flatten140_fu_138 + 17'd1);

assign add_ln184_2_fu_289_p2 = (indvar_flatten105_fu_130 + 9'd1);

assign add_ln184_fu_378_p2 = (select_ln183_fu_336_p3 + 3'd1);

assign add_ln185_2_fu_549_p2 = (indvar_flatten80_fu_122 + 7'd1);

assign add_ln185_fu_434_p2 = (ow_mid287_fu_389_p3 + 3'd1);

assign add_ln187_2_fu_535_p2 = (indvar_flatten65_fu_114 + 4'd1);

assign add_ln187_fu_479_p2 = (kh_mid272_fu_451_p3 + 2'd1);

assign add_ln188_fu_517_p2 = (kw_mid2_fu_497_p3 + 2'd1);

assign add_ln192_5_fu_669_p2 = (empty_154_fu_640_p2 + zext_ln188_4_fu_666_p1);

assign add_ln192_fu_679_p2 = (zext_ln192_fu_675_p1 + grp_fu_857_p3);

assign add_ln193_2_fu_689_p2 = (empty_149_fu_610_p2 + zext_ln188_3_fu_663_p1);

assign add_ln193_fu_695_p2 = (add_ln193_2_fu_689_p2 + zext_ln188_fu_659_p1);

assign add_ln197_fu_847_p2 = (grp_fu_866_p3 + zext_ln185_fu_839_p1);

assign add_ln198_fu_764_p2 = ($signed(sext_ln198_fu_760_p1) + $signed(sext_ln184_fu_734_p1));

assign and_ln183_3_fu_414_p2 = (xor_ln183_fu_343_p2 & icmp_ln187_fu_360_p2);

assign and_ln183_4_fu_372_p2 = (xor_ln183_fu_343_p2 & icmp_ln185_fu_366_p2);

assign and_ln183_fu_354_p2 = (xor_ln183_fu_343_p2 & icmp_ln188_fu_348_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign b2_dw_b_address0 = zext_ln183_fu_706_p1;

assign b2_dw_b_ce0 = b2_dw_b_ce0_local;

assign b2_dw_w_address0 = zext_ln193_2_fu_701_p1;

assign b2_dw_w_ce0 = b2_dw_w_ce0_local;

assign empty_145_fu_440_p2 = (exitcond_flatten67_mid2104_fu_420_p2 | and_ln183_4_fu_372_p2);

assign empty_146_fu_446_p2 = (icmp_ln184_reg_949_pp0_iter2_reg | empty_145_fu_440_p2);

assign empty_147_fu_485_p2 = (exitcond_flatten67_mid2104_fu_420_p2 | empty_fu_384_p2);

assign empty_148_fu_491_p2 = (icmp_ln188_mid279_fu_465_p2 | empty_147_fu_485_p2);

assign empty_149_fu_610_p2 = (p_shl4_fu_606_p1 + zext_ln183_6_fu_596_p1);

assign empty_152_fu_833_p2 = (p_shl3_fu_826_p3 - zext_ln184_2_fu_823_p1);

assign empty_153_fu_622_p2 = (zext_ln187_fu_619_p1 + zext_ln184_fu_616_p1);

assign empty_154_fu_640_p2 = (p_shl2_fu_632_p3 + p_cast17_fu_628_p1);

assign empty_155_fu_653_p2 = (p_shl_fu_646_p3 - zext_ln187_fu_619_p1);

assign empty_fu_384_p2 = (icmp_ln184_reg_949_pp0_iter2_reg | and_ln183_4_fu_372_p2);

assign exitcond_flatten67_mid2104_fu_420_p2 = (not_exitcond_flatten82_mid2139_fu_403_p2 & and_ln183_3_fu_414_p2);

assign exitcond_flatten82_not_fu_397_p2 = (icmp_ln185_fu_366_p2 ^ 1'd1);

assign grp_fu_857_p0 = grp_fu_857_p00;

assign grp_fu_857_p00 = select_ln183_3_fu_277_p3;

assign grp_fu_857_p1 = 15'd81;

assign grp_fu_857_p2 = grp_fu_857_p20;

assign grp_fu_857_p20 = select_ln185_fu_471_p3;

assign grp_fu_866_p0 = grp_fu_866_p00;

assign grp_fu_866_p00 = select_ln183_3_reg_958_pp0_iter3_reg;

assign grp_fu_866_p1 = 14'd49;

assign grp_fu_866_p2 = grp_fu_866_p20;

assign grp_fu_866_p20 = select_ln185_reg_983_pp0_iter5_reg;

assign icmp_ln183_fu_250_p2 = ((indvar_flatten140_fu_138 == 17'd102312) ? 1'b1 : 1'b0);

assign icmp_ln184_fu_265_p2 = ((indvar_flatten105_fu_130 == 9'd441) ? 1'b1 : 1'b0);

assign icmp_ln185_fu_366_p2 = ((indvar_flatten80_fu_122 == 7'd63) ? 1'b1 : 1'b0);

assign icmp_ln187_2_fu_529_p2 = ((select_ln187_fu_505_p3 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln187_fu_360_p2 = ((indvar_flatten65_fu_114 == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln188_2_fu_523_p2 = ((add_ln188_fu_517_p2 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln188_fu_348_p2 = ((kw_fu_106 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln188_mid2100_fu_408_p2 = (not_exitcond_flatten82_mid2139_fu_403_p2 & and_ln183_fu_354_p2);

assign icmp_ln188_mid279_fu_465_p2 = (not_exitcond_flatten67_mid2104_fu_459_p2 & icmp_ln188_mid2100_fu_408_p2);

assign icmp_ln39_fu_780_p2 = (($signed(tmp_19_fu_770_p4) > $signed(43'd0)) ? 1'b1 : 1'b0);

assign icmp_ln40_fu_786_p2 = (($signed(add_ln198_fu_764_p2) < $signed(57'd144115188075839488)) ? 1'b1 : 1'b0);

assign kh_mid272_fu_451_p3 = ((empty_146_fu_446_p2[0:0] == 1'b1) ? 2'd0 : kh_fu_110);

assign kw_mid2_fu_497_p3 = ((empty_148_fu_491_p2[0:0] == 1'b1) ? 2'd0 : kw_fu_106);

assign mul_ln193_fu_718_p1 = mul_ln193_fu_718_p10;

assign mul_ln193_fu_718_p10 = temp_dw_in_q0;

assign not_exitcond_flatten67_mid2104_fu_459_p2 = (exitcond_flatten67_mid2104_fu_420_p2 ^ 1'd1);

assign not_exitcond_flatten82_mid2139_fu_403_p2 = (icmp_ln184_reg_949_pp0_iter2_reg | exitcond_flatten82_not_fu_397_p2);

assign or_ln39_fu_804_p2 = (icmp_ln40_fu_786_p2 | icmp_ln39_fu_780_p2);

assign ow_mid287_fu_389_p3 = ((empty_fu_384_p2[0:0] == 1'b1) ? 3'd0 : ow_fu_118);

assign p_cast17_fu_628_p1 = empty_153_fu_622_p2;

assign p_shl2_fu_632_p3 = {{empty_153_fu_622_p2}, {3'd0}};

assign p_shl3_fu_826_p3 = {{select_ln184_reg_971_pp0_iter6_reg}, {3'd0}};

assign p_shl4_fu_606_p1 = tmp_1_fu_599_p3;

assign p_shl_fu_646_p3 = {{select_ln187_reg_994}, {2'd0}};

assign select_ln183_3_fu_277_p3 = ((icmp_ln184_fu_265_p2[0:0] == 1'b1) ? add_ln183_2_fu_271_p2 : c_fu_134);

assign select_ln183_fu_336_p3 = ((icmp_ln184_reg_949_pp0_iter2_reg[0:0] == 1'b1) ? 3'd0 : oh_fu_126);

assign select_ln184_2_fu_295_p3 = ((icmp_ln184_fu_265_p2[0:0] == 1'b1) ? 9'd1 : add_ln184_2_fu_289_p2);

assign select_ln184_fu_426_p3 = ((and_ln183_4_fu_372_p2[0:0] == 1'b1) ? add_ln184_fu_378_p2 : select_ln183_fu_336_p3);

assign select_ln185_2_fu_555_p3 = ((empty_fu_384_p2[0:0] == 1'b1) ? 7'd1 : add_ln185_2_fu_549_p2);

assign select_ln185_fu_471_p3 = ((exitcond_flatten67_mid2104_fu_420_p2[0:0] == 1'b1) ? add_ln185_fu_434_p2 : ow_mid287_fu_389_p3);

assign select_ln187_3_fu_541_p3 = ((empty_146_fu_446_p2[0:0] == 1'b1) ? 4'd1 : add_ln187_2_fu_535_p2);

assign select_ln187_fu_505_p3 = ((icmp_ln188_mid279_fu_465_p2[0:0] == 1'b1) ? add_ln187_fu_479_p2 : kh_mid272_fu_451_p3);

assign select_ln39_5_fu_796_p3 = ((icmp_ln39_fu_780_p2[0:0] == 1'b1) ? 15'd16383 : 15'd16384);

assign select_ln39_fu_810_p3 = ((or_ln39_fu_804_p2[0:0] == 1'b1) ? select_ln39_5_fu_796_p3 : trunc_ln41_fu_792_p1);

assign sext_ln184_fu_734_p1 = $signed(b2_dw_b_q0);

assign sext_ln192_fu_741_p1 = $signed(mul_ln193_reg_1033);

assign sext_ln197_fu_843_p1 = $signed(select_ln39_reg_1043);

assign sext_ln198_fu_760_p1 = $signed(trunc_ln_fu_750_p4);

assign temp_dw_in_address0 = zext_ln192_2_fu_684_p1;

assign temp_dw_in_ce0 = temp_dw_in_ce0_local;

assign temp_dw_out_address0 = zext_ln197_fu_852_p1;

assign temp_dw_out_ce0 = temp_dw_out_ce0_local;

assign temp_dw_out_d0 = sext_ln197_fu_843_p1;

assign temp_dw_out_we0 = temp_dw_out_we0_local;

assign tmp_19_fu_770_p4 = {{add_ln198_fu_764_p2[56:14]}};

assign tmp_1_fu_599_p3 = {{select_ln183_3_reg_958_pp0_iter3_reg}, {3'd0}};

assign trunc_ln41_fu_792_p1 = add_ln198_fu_764_p2[14:0];

assign trunc_ln_fu_750_p4 = {{acc_fu_744_p2[63:8]}};

assign xor_ln183_fu_343_p2 = (icmp_ln184_reg_949_pp0_iter2_reg ^ 1'd1);

assign zext_ln183_6_fu_596_p1 = select_ln183_3_reg_958_pp0_iter3_reg;

assign zext_ln183_fu_706_p1 = select_ln183_3_reg_958_pp0_iter4_reg;

assign zext_ln184_2_fu_823_p1 = select_ln184_reg_971_pp0_iter6_reg;

assign zext_ln184_fu_616_p1 = select_ln184_reg_971;

assign zext_ln185_fu_839_p1 = empty_152_fu_833_p2;

assign zext_ln187_fu_619_p1 = select_ln187_reg_994;

assign zext_ln188_3_fu_663_p1 = kw_mid2_reg_988;

assign zext_ln188_4_fu_666_p1 = kw_mid2_reg_988;

assign zext_ln188_fu_659_p1 = empty_155_fu_653_p2;

assign zext_ln192_2_fu_684_p1 = add_ln192_fu_679_p2;

assign zext_ln192_fu_675_p1 = add_ln192_5_fu_669_p2;

assign zext_ln193_2_fu_701_p1 = add_ln193_fu_695_p2;

assign zext_ln197_fu_852_p1 = add_ln197_fu_847_p2;

endmodule //Shuffle_Model_shuffle_block_s1_6_Pipeline_VITIS_LOOP_183_1_VITIS_LOOP_184_2_VITIS_LOOP_185_3_V
