// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Shuffle_Model_shuffle_block_s1_3_Pipeline_VITIS_LOOP_290_4_VITIS_LOOP_291_5_VITIS_LOOP_292_6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sm2_address0,
        sm2_ce0,
        sm2_q0,
        b2_in_1_address0,
        b2_in_1_ce0,
        b2_in_1_we0,
        b2_in_1_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [18:0] sm2_address0;
output   sm2_ce0;
input  [15:0] sm2_q0;
output  [15:0] b2_in_1_address0;
output   b2_in_1_ce0;
output   b2_in_1_we0;
output  [15:0] b2_in_1_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln290_fu_141_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln291_fu_159_p2;
reg   [0:0] icmp_ln291_reg_444;
reg   [0:0] icmp_ln291_reg_444_pp0_iter1_reg;
wire   [6:0] select_ln290_7_fu_171_p3;
reg   [6:0] select_ln290_7_reg_452;
reg   [6:0] select_ln290_7_reg_452_pp0_iter1_reg;
wire   [3:0] select_ln291_fu_267_p3;
reg   [3:0] select_ln291_reg_462;
wire   [63:0] zext_ln294_8_fu_343_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln293_fu_391_p1;
reg   [3:0] w_i_fu_66;
wire   [3:0] add_ln294_fu_304_p2;
wire    ap_loop_init;
reg   [3:0] h_fu_70;
reg   [7:0] indvar_flatten21_fu_74;
wire   [7:0] select_ln291_4_fu_189_p3;
reg   [7:0] ap_sig_allocacmp_indvar_flatten21_load;
reg   [6:0] c_fu_78;
reg   [6:0] ap_sig_allocacmp_c_load;
reg   [14:0] indvar_flatten36_fu_82;
wire   [14:0] add_ln290_fu_147_p2;
reg   [14:0] ap_sig_allocacmp_indvar_flatten36_load;
reg    sm2_ce0_local;
reg    b2_in_1_we0_local;
reg    b2_in_1_ce0_local;
wire   [6:0] add_ln290_4_fu_165_p2;
wire   [7:0] add_ln291_fu_183_p2;
wire   [0:0] icmp_ln292_fu_230_p2;
wire   [0:0] xor_ln290_fu_225_p2;
wire   [3:0] select_ln290_fu_218_p3;
wire   [0:0] and_ln290_fu_236_p2;
wire   [0:0] empty_fu_248_p2;
wire   [3:0] indvars_iv_next92_dup_fu_242_p2;
wire   [3:0] indvars_iv_next92200_fu_275_p2;
wire   [3:0] indvars_iv_next92_mid1_fu_261_p2;
wire   [3:0] select_ln290_8_fu_281_p3;
wire   [3:0] w_i_13_mid2_fu_253_p3;
wire   [3:0] empty_180_fu_288_p3;
wire   [14:0] tmp2_fu_310_p4;
wire   [12:0] zext_ln292_8_fu_300_p1;
wire   [12:0] add_ln294_7_fu_323_p2;
wire  signed [14:0] sext_ln294_fu_329_p1;
wire   [15:0] zext_ln294_7_fu_333_p1;
wire   [15:0] zext_ln294_fu_319_p1;
wire   [15:0] add_ln294_4_fu_337_p2;
wire   [4:0] tmp_1_fu_365_p3;
wire   [7:0] p_shl_fu_358_p3;
wire   [7:0] p_shl1_fu_372_p1;
wire   [7:0] empty_181_fu_376_p2;
wire   [14:0] grp_fu_396_p3;
wire   [14:0] zext_ln292_fu_382_p1;
(* use_dsp48 = "no" *) wire   [14:0] add_ln293_fu_386_p2;
wire   [7:0] grp_fu_396_p0;
wire   [6:0] grp_fu_396_p1;
wire   [3:0] grp_fu_396_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [14:0] grp_fu_396_p10;
wire   [14:0] grp_fu_396_p20;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 w_i_fu_66 = 4'd0;
#0 h_fu_70 = 4'd0;
#0 indvar_flatten21_fu_74 = 8'd0;
#0 c_fu_78 = 7'd0;
#0 indvar_flatten36_fu_82 = 15'd0;
#0 ap_done_reg = 1'b0;
end

Shuffle_Model_mac_muladd_8ns_7ns_4ns_15_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 4 ),
    .dout_WIDTH( 15 ))
mac_muladd_8ns_7ns_4ns_15_4_1_U302(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_396_p0),
    .din1(grp_fu_396_p1),
    .din2(grp_fu_396_p2),
    .ce(1'b1),
    .dout(grp_fu_396_p3)
);

Shuffle_Model_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln290_fu_141_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            c_fu_78 <= select_ln290_7_fu_171_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_78 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            h_fu_70 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            h_fu_70 <= select_ln291_fu_267_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln290_fu_141_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten21_fu_74 <= select_ln291_4_fu_189_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten21_fu_74 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln290_fu_141_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten36_fu_82 <= add_ln290_fu_147_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten36_fu_82 <= 15'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            w_i_fu_66 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            w_i_fu_66 <= add_ln294_fu_304_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln291_reg_444 <= icmp_ln291_fu_159_p2;
        icmp_ln291_reg_444_pp0_iter1_reg <= icmp_ln291_reg_444;
        select_ln290_7_reg_452 <= select_ln290_7_fu_171_p3;
        select_ln290_7_reg_452_pp0_iter1_reg <= select_ln290_7_reg_452;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        select_ln291_reg_462 <= select_ln291_fu_267_p3;
    end
end

always @ (*) begin
    if (((icmp_ln290_fu_141_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_c_load = 7'd0;
    end else begin
        ap_sig_allocacmp_c_load = c_fu_78;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten21_load = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten21_load = indvar_flatten21_fu_74;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten36_load = 15'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten36_load = indvar_flatten36_fu_82;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        b2_in_1_ce0_local = 1'b1;
    end else begin
        b2_in_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        b2_in_1_we0_local = 1'b1;
    end else begin
        b2_in_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        sm2_ce0_local = 1'b1;
    end else begin
        sm2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln290_4_fu_165_p2 = (ap_sig_allocacmp_c_load + 7'd1);

assign add_ln290_fu_147_p2 = (ap_sig_allocacmp_indvar_flatten36_load + 15'd1);

assign add_ln291_fu_183_p2 = (ap_sig_allocacmp_indvar_flatten21_load + 8'd1);

assign add_ln293_fu_386_p2 = (grp_fu_396_p3 + zext_ln292_fu_382_p1);

assign add_ln294_4_fu_337_p2 = (zext_ln294_7_fu_333_p1 + zext_ln294_fu_319_p1);

assign add_ln294_7_fu_323_p2 = ($signed(zext_ln292_8_fu_300_p1) + $signed(13'd5121));

assign add_ln294_fu_304_p2 = (w_i_13_mid2_fu_253_p3 + 4'd1);

assign and_ln290_fu_236_p2 = (xor_ln290_fu_225_p2 & icmp_ln292_fu_230_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign b2_in_1_address0 = zext_ln293_fu_391_p1;

assign b2_in_1_ce0 = b2_in_1_ce0_local;

assign b2_in_1_d0 = sm2_q0;

assign b2_in_1_we0 = b2_in_1_we0_local;

assign empty_180_fu_288_p3 = ((and_ln290_fu_236_p2[0:0] == 1'b1) ? indvars_iv_next92_mid1_fu_261_p2 : select_ln290_8_fu_281_p3);

assign empty_181_fu_376_p2 = (p_shl_fu_358_p3 - p_shl1_fu_372_p1);

assign empty_fu_248_p2 = (icmp_ln291_reg_444_pp0_iter1_reg | and_ln290_fu_236_p2);

assign grp_fu_396_p0 = 15'd196;

assign grp_fu_396_p1 = grp_fu_396_p10;

assign grp_fu_396_p10 = select_ln290_7_fu_171_p3;

assign grp_fu_396_p2 = grp_fu_396_p20;

assign grp_fu_396_p20 = w_i_13_mid2_fu_253_p3;

assign icmp_ln290_fu_141_p2 = ((ap_sig_allocacmp_indvar_flatten36_load == 15'd22736) ? 1'b1 : 1'b0);

assign icmp_ln291_fu_159_p2 = ((ap_sig_allocacmp_indvar_flatten21_load == 8'd196) ? 1'b1 : 1'b0);

assign icmp_ln292_fu_230_p2 = ((w_i_fu_66 == 4'd14) ? 1'b1 : 1'b0);

assign indvars_iv_next92200_fu_275_p2 = (h_fu_70 + 4'd1);

assign indvars_iv_next92_dup_fu_242_p2 = (select_ln290_fu_218_p3 + 4'd1);

assign indvars_iv_next92_mid1_fu_261_p2 = (select_ln290_fu_218_p3 + 4'd2);

assign p_shl1_fu_372_p1 = tmp_1_fu_365_p3;

assign p_shl_fu_358_p3 = {{select_ln291_reg_462}, {4'd0}};

assign select_ln290_7_fu_171_p3 = ((icmp_ln291_fu_159_p2[0:0] == 1'b1) ? add_ln290_4_fu_165_p2 : ap_sig_allocacmp_c_load);

assign select_ln290_8_fu_281_p3 = ((icmp_ln291_reg_444_pp0_iter1_reg[0:0] == 1'b1) ? 4'd1 : indvars_iv_next92200_fu_275_p2);

assign select_ln290_fu_218_p3 = ((icmp_ln291_reg_444_pp0_iter1_reg[0:0] == 1'b1) ? 4'd0 : h_fu_70);

assign select_ln291_4_fu_189_p3 = ((icmp_ln291_fu_159_p2[0:0] == 1'b1) ? 8'd1 : add_ln291_fu_183_p2);

assign select_ln291_fu_267_p3 = ((and_ln290_fu_236_p2[0:0] == 1'b1) ? indvars_iv_next92_dup_fu_242_p2 : select_ln290_fu_218_p3);

assign sext_ln294_fu_329_p1 = $signed(add_ln294_7_fu_323_p2);

assign sm2_address0 = zext_ln294_8_fu_343_p1;

assign sm2_ce0 = sm2_ce0_local;

assign tmp2_fu_310_p4 = {{{select_ln290_7_reg_452_pp0_iter1_reg}, {empty_180_fu_288_p3}}, {4'd0}};

assign tmp_1_fu_365_p3 = {{select_ln291_reg_462}, {1'd0}};

assign w_i_13_mid2_fu_253_p3 = ((empty_fu_248_p2[0:0] == 1'b1) ? 4'd0 : w_i_fu_66);

assign xor_ln290_fu_225_p2 = (icmp_ln291_reg_444_pp0_iter1_reg ^ 1'd1);

assign zext_ln292_8_fu_300_p1 = w_i_13_mid2_fu_253_p3;

assign zext_ln292_fu_382_p1 = empty_181_fu_376_p2;

assign zext_ln293_fu_391_p1 = add_ln293_fu_386_p2;

assign zext_ln294_7_fu_333_p1 = $unsigned(sext_ln294_fu_329_p1);

assign zext_ln294_8_fu_343_p1 = add_ln294_4_fu_337_p2;

assign zext_ln294_fu_319_p1 = tmp2_fu_310_p4;

endmodule //Shuffle_Model_shuffle_block_s1_3_Pipeline_VITIS_LOOP_290_4_VITIS_LOOP_291_5_VITIS_LOOP_292_6
