// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Shuffle_Model_Shuffle_Model_Pipeline_VITIS_LOOP_514_1_VITIS_LOOP_516_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sm4_address0,
        sm4_ce0,
        sm4_q0,
        max_class_12_out,
        max_class_12_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] sm4_address0;
output   sm4_ce0;
input  [15:0] sm4_q0;
output  [31:0] max_class_12_out;
output   max_class_12_out_ap_vld;

reg ap_idle;
reg max_class_12_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln514_fu_187_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [19:0] fc_w_address0;
wire  signed [14:0] fc_w_q0;
wire   [9:0] fc_b_address0;
wire   [10:0] fc_b_q0;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln514_reg_522;
reg   [0:0] icmp_ln514_reg_522_pp0_iter2_reg;
reg   [0:0] icmp_ln514_reg_522_pp0_iter3_reg;
wire   [0:0] icmp_ln516_fu_205_p2;
reg   [0:0] icmp_ln516_reg_526;
reg   [0:0] icmp_ln516_reg_526_pp0_iter2_reg;
reg   [0:0] icmp_ln516_reg_526_pp0_iter3_reg;
reg   [0:0] icmp_ln516_reg_526_pp0_iter4_reg;
wire   [9:0] select_ln514_2_fu_225_p3;
reg   [9:0] select_ln514_2_reg_533;
reg   [9:0] select_ln514_2_reg_533_pp0_iter2_reg;
reg   [9:0] select_ln514_2_reg_533_pp0_iter3_reg;
reg   [9:0] select_ln514_2_reg_533_pp0_iter4_reg;
reg   [10:0] fc_b_load_reg_569;
wire   [63:0] zext_ln516_fu_241_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln518_fu_256_p1;
wire   [63:0] zext_ln514_fu_290_p1;
reg   [39:0] acc_fu_76;
wire  signed [39:0] grp_fu_457_p3;
reg   [39:0] ap_sig_allocacmp_acc_load;
wire    ap_loop_init;
reg   [10:0] ic_fu_80;
wire   [10:0] add_ln516_fu_261_p2;
reg   [15:0] max_val_11_fu_84;
wire   [15:0] max_val_1_fu_421_p3;
reg   [31:0] max_class_12_fu_88;
wire   [31:0] max_class_1_fu_413_p3;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [31:0] max_class_fu_92;
wire   [31:0] select_ln514_4_fu_323_p3;
reg   [15:0] max_val_fu_96;
wire   [15:0] select_ln514_3_fu_316_p3;
reg   [9:0] oc_fu_100;
reg   [19:0] indvar_flatten217_fu_104;
wire   [19:0] add_ln514_fu_193_p2;
wire    ap_block_pp0_stage0_01001;
reg    sm4_ce0_local;
reg    fc_w_ce0_local;
reg    fc_b_ce0_local;
wire   [9:0] add_ln514_1_fu_219_p2;
wire   [10:0] select_ln514_fu_211_p3;
wire   [19:0] zext_ln516_1_fu_246_p1;
wire   [19:0] tmp_s_fu_233_p3;
wire   [19:0] add_ln518_fu_250_p2;
wire   [31:0] trunc_ln52_1_fu_330_p4;
wire  signed [32:0] sext_ln52_fu_339_p1;
wire  signed [32:0] sext_ln52_1_fu_343_p1;
wire   [32:0] result_fu_346_p2;
wire   [18:0] tmp_1_fu_352_p4;
wire   [0:0] icmp_ln39_fu_362_p2;
wire   [0:0] icmp_ln40_fu_368_p2;
wire   [0:0] or_ln39_fu_386_p2;
wire   [14:0] select_ln39_fu_378_p3;
wire   [14:0] trunc_ln41_fu_374_p1;
wire   [14:0] val_fu_392_p3;
wire  signed [15:0] sext_ln520_fu_400_p1;
wire   [0:0] icmp_ln521_fu_404_p2;
wire   [31:0] zext_ln521_fu_410_p1;
wire  signed [39:0] grp_fu_457_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 acc_fu_76 = 40'd0;
#0 ic_fu_80 = 11'd0;
#0 max_val_11_fu_84 = 16'd0;
#0 max_class_12_fu_88 = 32'd0;
#0 max_class_fu_92 = 32'd0;
#0 max_val_fu_96 = 16'd0;
#0 oc_fu_100 = 10'd0;
#0 indvar_flatten217_fu_104 = 20'd0;
#0 ap_done_reg = 1'b0;
end

Shuffle_Model_Shuffle_Model_Pipeline_VITIS_LOOP_514_1_VITIS_LOOP_516_2_fc_w_ROM_AUTO_1R #(
    .DataWidth( 15 ),
    .AddressRange( 1024000 ),
    .AddressWidth( 20 ))
fc_w_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fc_w_address0),
    .ce0(fc_w_ce0_local),
    .q0(fc_w_q0)
);

Shuffle_Model_Shuffle_Model_Pipeline_VITIS_LOOP_514_1_VITIS_LOOP_516_2_fc_b_ROM_AUTO_1R #(
    .DataWidth( 11 ),
    .AddressRange( 1000 ),
    .AddressWidth( 10 ))
fc_b_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fc_b_address0),
    .ce0(fc_b_ce0_local),
    .q0(fc_b_q0)
);

Shuffle_Model_mac_muladd_16s_15s_40s_40_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 40 ),
    .dout_WIDTH( 40 ))
mac_muladd_16s_15s_40s_40_4_1_U596(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sm4_q0),
    .din1(fc_w_q0),
    .din2(grp_fu_457_p2),
    .ce(1'b1),
    .dout(grp_fu_457_p3)
);

Shuffle_Model_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            acc_fu_76 <= 40'd0;
        end else if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
            acc_fu_76 <= grp_fu_457_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ic_fu_80 <= 11'd0;
        end else if (((icmp_ln514_fu_187_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            ic_fu_80 <= add_ln516_fu_261_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten217_fu_104 <= 20'd0;
        end else if (((icmp_ln514_fu_187_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten217_fu_104 <= add_ln514_fu_193_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            max_class_fu_92 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
            max_class_fu_92 <= select_ln514_4_fu_323_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            max_val_fu_96 <= 16'd49152;
        end else if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
            max_val_fu_96 <= select_ln514_3_fu_316_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            oc_fu_100 <= 10'd0;
        end else if (((icmp_ln514_fu_187_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            oc_fu_100 <= select_ln514_2_fu_225_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln514_reg_522 <= icmp_ln514_fu_187_p2;
        icmp_ln516_reg_526 <= icmp_ln516_fu_205_p2;
        select_ln514_2_reg_533 <= select_ln514_2_fu_225_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        fc_b_load_reg_569 <= fc_b_q0;
        icmp_ln514_reg_522_pp0_iter2_reg <= icmp_ln514_reg_522;
        icmp_ln514_reg_522_pp0_iter3_reg <= icmp_ln514_reg_522_pp0_iter2_reg;
        icmp_ln516_reg_526_pp0_iter2_reg <= icmp_ln516_reg_526;
        icmp_ln516_reg_526_pp0_iter3_reg <= icmp_ln516_reg_526_pp0_iter2_reg;
        icmp_ln516_reg_526_pp0_iter4_reg <= icmp_ln516_reg_526_pp0_iter3_reg;
        select_ln514_2_reg_533_pp0_iter2_reg <= select_ln514_2_reg_533;
        select_ln514_2_reg_533_pp0_iter3_reg <= select_ln514_2_reg_533_pp0_iter2_reg;
        select_ln514_2_reg_533_pp0_iter4_reg <= select_ln514_2_reg_533_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        max_class_12_fu_88 <= max_class_1_fu_413_p3;
        max_val_11_fu_84 <= max_val_1_fu_421_p3;
    end
end

always @ (*) begin
    if (((icmp_ln514_fu_187_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ap_sig_allocacmp_acc_load = grp_fu_457_p3;
    end else begin
        ap_sig_allocacmp_acc_load = acc_fu_76;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        fc_b_ce0_local = 1'b1;
    end else begin
        fc_b_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fc_w_ce0_local = 1'b1;
    end else begin
        fc_w_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln514_reg_522_pp0_iter3_reg == 1'd1))) begin
        max_class_12_out_ap_vld = 1'b1;
    end else begin
        max_class_12_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sm4_ce0_local = 1'b1;
    end else begin
        sm4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln514_1_fu_219_p2 = (oc_fu_100 + 10'd1);

assign add_ln514_fu_193_p2 = (indvar_flatten217_fu_104 + 20'd1);

assign add_ln516_fu_261_p2 = (select_ln514_fu_211_p3 + 11'd1);

assign add_ln518_fu_250_p2 = (zext_ln516_1_fu_246_p1 + tmp_s_fu_233_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign fc_b_address0 = zext_ln514_fu_290_p1;

assign fc_w_address0 = zext_ln518_fu_256_p1;

assign grp_fu_457_p2 = ((icmp_ln516_reg_526_pp0_iter3_reg[0:0] == 1'b1) ? 40'd0 : ap_sig_allocacmp_acc_load);

assign icmp_ln39_fu_362_p2 = (($signed(tmp_1_fu_352_p4) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln40_fu_368_p2 = (($signed(result_fu_346_p2) < $signed(33'd8589918208)) ? 1'b1 : 1'b0);

assign icmp_ln514_fu_187_p2 = ((indvar_flatten217_fu_104 == 20'd1024000) ? 1'b1 : 1'b0);

assign icmp_ln516_fu_205_p2 = ((ic_fu_80 == 11'd1024) ? 1'b1 : 1'b0);

assign icmp_ln521_fu_404_p2 = (($signed(sext_ln520_fu_400_p1) > $signed(select_ln514_3_fu_316_p3)) ? 1'b1 : 1'b0);

assign max_class_12_out = max_class_12_fu_88;

assign max_class_1_fu_413_p3 = ((icmp_ln521_fu_404_p2[0:0] == 1'b1) ? zext_ln521_fu_410_p1 : select_ln514_4_fu_323_p3);

assign max_val_1_fu_421_p3 = ((icmp_ln521_fu_404_p2[0:0] == 1'b1) ? sext_ln520_fu_400_p1 : select_ln514_3_fu_316_p3);

assign or_ln39_fu_386_p2 = (icmp_ln40_fu_368_p2 | icmp_ln39_fu_362_p2);

assign result_fu_346_p2 = ($signed(sext_ln52_fu_339_p1) + $signed(sext_ln52_1_fu_343_p1));

assign select_ln39_fu_378_p3 = ((icmp_ln39_fu_362_p2[0:0] == 1'b1) ? 15'd16383 : 15'd16384);

assign select_ln514_2_fu_225_p3 = ((icmp_ln516_fu_205_p2[0:0] == 1'b1) ? add_ln514_1_fu_219_p2 : oc_fu_100);

assign select_ln514_3_fu_316_p3 = ((icmp_ln516_reg_526_pp0_iter4_reg[0:0] == 1'b1) ? max_val_11_fu_84 : max_val_fu_96);

assign select_ln514_4_fu_323_p3 = ((icmp_ln516_reg_526_pp0_iter4_reg[0:0] == 1'b1) ? max_class_12_fu_88 : max_class_fu_92);

assign select_ln514_fu_211_p3 = ((icmp_ln516_fu_205_p2[0:0] == 1'b1) ? 11'd0 : ic_fu_80);

assign sext_ln520_fu_400_p1 = $signed(val_fu_392_p3);

assign sext_ln52_1_fu_343_p1 = $signed(fc_b_load_reg_569);

assign sext_ln52_fu_339_p1 = $signed(trunc_ln52_1_fu_330_p4);

assign sm4_address0 = zext_ln516_fu_241_p1;

assign sm4_ce0 = sm4_ce0_local;

assign tmp_1_fu_352_p4 = {{result_fu_346_p2[32:14]}};

assign tmp_s_fu_233_p3 = {{select_ln514_2_fu_225_p3}, {10'd0}};

assign trunc_ln41_fu_374_p1 = result_fu_346_p2[14:0];

assign trunc_ln52_1_fu_330_p4 = {{grp_fu_457_p3[39:8]}};

assign val_fu_392_p3 = ((or_ln39_fu_386_p2[0:0] == 1'b1) ? select_ln39_fu_378_p3 : trunc_ln41_fu_374_p1);

assign zext_ln514_fu_290_p1 = select_ln514_2_reg_533_pp0_iter2_reg;

assign zext_ln516_1_fu_246_p1 = select_ln514_fu_211_p3;

assign zext_ln516_fu_241_p1 = select_ln514_fu_211_p3;

assign zext_ln518_fu_256_p1 = add_ln518_fu_250_p2;

assign zext_ln521_fu_410_p1 = select_ln514_2_reg_533_pp0_iter4_reg;

endmodule //Shuffle_Model_Shuffle_Model_Pipeline_VITIS_LOOP_514_1_VITIS_LOOP_516_2
