// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Shuffle_Model_shuffle_block_s2_2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_7_V (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sm3_address0,
        sm3_ce0,
        sm3_we0,
        sm3_d0,
        b2_in_address0,
        b2_in_ce0,
        b2_in_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [17:0] sm3_address0;
output   sm3_ce0;
output   sm3_we0;
output  [15:0] sm3_d0;
output  [16:0] b2_in_address0;
output   b2_in_ce0;
input  [15:0] b2_in_q0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln406_fu_239_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [6:0] s3_0_b2_pw1_b_address0;
wire   [9:0] s3_0_b2_pw1_b_q0;
wire   [13:0] s3_0_b2_pw1_w_address0;
wire  signed [8:0] s3_0_b2_pw1_w_q0;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln407_fu_257_p2;
reg   [0:0] icmp_ln407_reg_825;
reg   [0:0] icmp_ln407_reg_825_pp0_iter2_reg;
reg   [0:0] icmp_ln407_reg_825_pp0_iter3_reg;
reg   [0:0] icmp_ln407_reg_825_pp0_iter4_reg;
reg   [0:0] icmp_ln407_reg_825_pp0_iter5_reg;
reg   [0:0] icmp_ln407_reg_825_pp0_iter6_reg;
reg   [0:0] icmp_ln407_reg_825_pp0_iter7_reg;
reg   [0:0] icmp_ln407_reg_825_pp0_iter8_reg;
wire   [0:0] and_ln406_2_fu_281_p2;
reg   [0:0] and_ln406_2_reg_831;
reg   [0:0] and_ln406_2_reg_831_pp0_iter2_reg;
reg   [0:0] and_ln406_2_reg_831_pp0_iter3_reg;
reg   [0:0] and_ln406_2_reg_831_pp0_iter4_reg;
reg   [0:0] and_ln406_2_reg_831_pp0_iter5_reg;
reg   [0:0] and_ln406_2_reg_831_pp0_iter6_reg;
reg   [0:0] and_ln406_2_reg_831_pp0_iter7_reg;
reg   [0:0] and_ln406_2_reg_831_pp0_iter8_reg;
wire   [6:0] select_ln406_6_fu_293_p3;
reg   [6:0] select_ln406_6_reg_837;
reg   [6:0] select_ln406_6_reg_837_pp0_iter2_reg;
reg   [6:0] select_ln406_6_reg_837_pp0_iter3_reg;
reg   [6:0] select_ln406_6_reg_837_pp0_iter4_reg;
reg   [6:0] select_ln406_6_reg_837_pp0_iter5_reg;
reg   [6:0] select_ln406_6_reg_837_pp0_iter6_reg;
wire   [0:0] empty_fu_301_p2;
reg   [0:0] empty_reg_843;
reg   [0:0] empty_reg_843_pp0_iter2_reg;
reg   [0:0] empty_reg_843_pp0_iter3_reg;
wire   [0:0] icmp_ln410_mid234_fu_325_p2;
reg   [0:0] icmp_ln410_mid234_reg_848;
reg   [0:0] icmp_ln410_mid234_reg_848_pp0_iter2_reg;
reg   [0:0] icmp_ln410_mid234_reg_848_pp0_iter3_reg;
wire   [0:0] empty_70_fu_337_p2;
reg   [0:0] empty_70_reg_853;
reg   [0:0] empty_70_reg_853_pp0_iter2_reg;
reg   [0:0] empty_70_reg_853_pp0_iter3_reg;
reg   [0:0] empty_70_reg_853_pp0_iter4_reg;
reg   [0:0] empty_70_reg_853_pp0_iter5_reg;
reg   [0:0] empty_70_reg_853_pp0_iter6_reg;
wire   [6:0] ic_mid2_fu_343_p3;
reg   [6:0] ic_mid2_reg_858;
reg   [6:0] ic_mid2_reg_858_pp0_iter2_reg;
wire   [0:0] icmp_ln410_2_fu_365_p2;
reg   [0:0] icmp_ln410_2_reg_873;
reg   [0:0] icmp_ln410_2_reg_873_pp0_iter2_reg;
reg   [0:0] icmp_ln410_2_reg_873_pp0_iter3_reg;
reg   [0:0] icmp_ln410_2_reg_873_pp0_iter4_reg;
reg   [0:0] icmp_ln410_2_reg_873_pp0_iter5_reg;
reg   [0:0] icmp_ln410_2_reg_873_pp0_iter6_reg;
reg   [0:0] icmp_ln410_2_reg_873_pp0_iter7_reg;
reg   [0:0] icmp_ln410_2_reg_873_pp0_iter8_reg;
reg   [4:0] oh_load_reg_877;
reg   [4:0] oh_load_reg_877_pp0_iter4_reg;
reg   [4:0] oh_load_reg_877_pp0_iter5_reg;
reg   [4:0] oh_load_reg_877_pp0_iter6_reg;
reg   [4:0] oh_load_reg_877_pp0_iter7_reg;
reg   [4:0] oh_load_reg_877_pp0_iter8_reg;
wire   [4:0] select_ln406_fu_427_p3;
reg   [4:0] select_ln406_reg_882;
reg   [4:0] select_ln406_reg_882_pp0_iter4_reg;
reg   [4:0] select_ln406_reg_882_pp0_iter5_reg;
reg   [4:0] select_ln406_reg_882_pp0_iter6_reg;
reg   [4:0] select_ln406_reg_882_pp0_iter7_reg;
reg   [4:0] select_ln406_reg_882_pp0_iter8_reg;
wire   [4:0] select_ln408_fu_501_p3;
reg   [4:0] select_ln408_reg_897;
reg   [4:0] select_ln408_reg_897_pp0_iter5_reg;
reg   [4:0] select_ln408_reg_897_pp0_iter6_reg;
reg   [4:0] select_ln408_reg_897_pp0_iter7_reg;
wire   [13:0] val_3_fu_639_p3;
reg   [13:0] val_3_reg_937;
wire   [63:0] zext_ln412_fu_517_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln413_fu_522_p1;
wire   [63:0] zext_ln406_fu_552_p1;
wire   [63:0] zext_ln419_1_fu_723_p1;
reg   [30:0] acc_fu_106;
wire  signed [30:0] grp_fu_746_p3;
reg   [30:0] ap_sig_allocacmp_acc_load;
wire    ap_loop_init;
reg   [6:0] ic_fu_110;
wire   [6:0] add_ln410_fu_359_p2;
reg   [4:0] ow_fu_114;
reg   [11:0] indvar_flatten21_fu_118;
wire   [11:0] select_ln408_2_fu_377_p3;
reg   [4:0] oh_fu_122;
wire   [4:0] select_ln407_fu_440_p3;
reg   [16:0] indvar_flatten35_fu_126;
wire   [16:0] select_ln407_2_fu_391_p3;
reg   [6:0] oc_fu_130;
reg   [23:0] indvar_flatten61_fu_134;
wire   [23:0] add_ln406_fu_245_p2;
reg    b2_in_ce0_local;
reg    s3_0_b2_pw1_w_ce0_local;
reg    s3_0_b2_pw1_b_ce0_local;
reg    sm3_we0_local;
wire   [15:0] zext_ln415_fu_714_p1;
reg    sm3_ce0_local;
wire   [0:0] icmp_ln408_fu_275_p2;
wire   [0:0] xor_ln406_fu_263_p2;
wire   [6:0] add_ln406_2_fu_287_p2;
wire   [0:0] exitcond_flatten23_not_fu_307_p2;
wire   [0:0] icmp_ln410_fu_269_p2;
wire   [0:0] and_ln406_fu_319_p2;
wire   [0:0] not_exitcond_flatten23_mid260_fu_313_p2;
wire   [0:0] empty_69_fu_331_p2;
wire   [11:0] add_ln408_fu_371_p2;
wire   [16:0] add_ln407_fu_385_p2;
wire   [4:0] indvars_iv_next72_dup_fu_434_p2;
wire   [6:0] tmp_1_fu_455_p3;
wire   [9:0] p_shl8_fu_447_p3;
wire   [9:0] p_shl9_fu_463_p1;
wire   [9:0] empty_73_fu_467_p2;
wire   [4:0] ow_mid228_fu_488_p3;
wire   [4:0] add_ln419_fu_495_p2;
wire   [16:0] grp_fu_737_p3;
wire   [16:0] zext_ln408_1_fu_508_p1;
(* use_dsp48 = "no" *) wire   [16:0] add_ln412_fu_512_p2;
wire   [13:0] grp_fu_728_p3;
wire   [22:0] trunc_ln_fu_560_p4;
wire  signed [23:0] sext_ln52_fu_569_p1;
wire  signed [23:0] sext_ln407_fu_556_p1;
wire   [23:0] result_fu_573_p2;
wire   [9:0] tmp_8_fu_579_p4;
wire   [0:0] icmp_ln39_fu_589_p2;
wire   [0:0] icmp_ln40_fu_595_p2;
wire   [0:0] or_ln39_fu_613_p2;
wire   [14:0] select_ln39_fu_605_p3;
wire   [14:0] trunc_ln41_fu_601_p1;
wire   [14:0] val_fu_619_p3;
wire   [0:0] tmp_9_fu_631_p3;
wire   [13:0] trunc_ln415_fu_627_p1;
wire   [4:0] add_ln419_3_fu_647_p2;
wire   [4:0] indvars_iv_next72121_fu_660_p2;
wire   [4:0] indvars_iv_next72_mid1_fu_672_p2;
wire   [4:0] select_ln406_5_fu_665_p3;
wire   [4:0] indvars_iv_next72_mid2_fu_677_p3;
wire   [5:0] tmp_7_fu_692_p3;
wire   [9:0] p_shl_fu_684_p3;
wire   [9:0] p_shl7_fu_700_p1;
wire   [9:0] empty_74_fu_704_p2;
wire   [16:0] grp_fu_756_p3;
wire   [16:0] zext_ln408_fu_710_p1;
(* use_dsp48 = "no" *) wire   [16:0] add_ln419_2_fu_718_p2;
wire   [6:0] grp_fu_728_p0;
wire   [6:0] grp_fu_728_p1;
wire   [6:0] grp_fu_728_p2;
wire   [9:0] grp_fu_737_p0;
wire   [6:0] grp_fu_737_p1;
wire   [9:0] grp_fu_737_p2;
wire  signed [30:0] grp_fu_746_p2;
wire   [9:0] grp_fu_756_p0;
wire   [6:0] grp_fu_756_p1;
wire   [4:0] grp_fu_756_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [13:0] grp_fu_728_p00;
wire   [13:0] grp_fu_728_p20;
wire   [16:0] grp_fu_737_p10;
wire   [16:0] grp_fu_737_p20;
wire   [16:0] grp_fu_756_p10;
wire   [16:0] grp_fu_756_p20;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 acc_fu_106 = 31'd0;
#0 ic_fu_110 = 7'd0;
#0 ow_fu_114 = 5'd0;
#0 indvar_flatten21_fu_118 = 12'd0;
#0 oh_fu_122 = 5'd0;
#0 indvar_flatten35_fu_126 = 17'd0;
#0 oc_fu_130 = 7'd0;
#0 indvar_flatten61_fu_134 = 24'd0;
#0 ap_done_reg = 1'b0;
end

Shuffle_Model_shuffle_block_s2_2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_hbi #(
    .DataWidth( 10 ),
    .AddressRange( 116 ),
    .AddressWidth( 7 ))
s3_0_b2_pw1_b_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(s3_0_b2_pw1_b_address0),
    .ce0(s3_0_b2_pw1_b_ce0_local),
    .q0(s3_0_b2_pw1_b_q0)
);

Shuffle_Model_shuffle_block_s2_2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_ibs #(
    .DataWidth( 9 ),
    .AddressRange( 13456 ),
    .AddressWidth( 14 ))
s3_0_b2_pw1_w_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(s3_0_b2_pw1_w_address0),
    .ce0(s3_0_b2_pw1_w_ce0_local),
    .q0(s3_0_b2_pw1_w_q0)
);

Shuffle_Model_mac_muladd_7ns_7ns_7ns_14_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 7 ),
    .dout_WIDTH( 14 ))
mac_muladd_7ns_7ns_7ns_14_4_1_U250(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_728_p0),
    .din1(grp_fu_728_p1),
    .din2(grp_fu_728_p2),
    .ce(1'b1),
    .dout(grp_fu_728_p3)
);

Shuffle_Model_mac_muladd_10ns_7ns_10ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 10 ),
    .dout_WIDTH( 17 ))
mac_muladd_10ns_7ns_10ns_17_4_1_U251(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_737_p0),
    .din1(grp_fu_737_p1),
    .din2(grp_fu_737_p2),
    .ce(1'b1),
    .dout(grp_fu_737_p3)
);

Shuffle_Model_mac_muladd_16s_9s_31s_31_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mac_muladd_16s_9s_31s_31_4_1_U252(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(b2_in_q0),
    .din1(s3_0_b2_pw1_w_q0),
    .din2(grp_fu_746_p2),
    .ce(1'b1),
    .dout(grp_fu_746_p3)
);

Shuffle_Model_mac_muladd_10ns_7ns_5ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 5 ),
    .dout_WIDTH( 17 ))
mac_muladd_10ns_7ns_5ns_17_4_1_U253(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_756_p0),
    .din1(grp_fu_756_p1),
    .din2(grp_fu_756_p2),
    .ce(1'b1),
    .dout(grp_fu_756_p3)
);

Shuffle_Model_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_fu_106 <= 31'd0;
        end else if ((ap_enable_reg_pp0_iter8 == 1'b1)) begin
            acc_fu_106 <= grp_fu_746_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ic_fu_110 <= 7'd0;
        end else if (((icmp_ln406_fu_239_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            ic_fu_110 <= add_ln410_fu_359_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten21_fu_118 <= 12'd0;
        end else if (((icmp_ln406_fu_239_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten21_fu_118 <= select_ln408_2_fu_377_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten35_fu_126 <= 17'd0;
        end else if (((icmp_ln406_fu_239_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten35_fu_126 <= select_ln407_2_fu_391_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten61_fu_134 <= 24'd0;
        end else if (((icmp_ln406_fu_239_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten61_fu_134 <= add_ln406_fu_245_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            oc_fu_130 <= 7'd0;
        end else if (((icmp_ln406_fu_239_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            oc_fu_130 <= select_ln406_6_fu_293_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            oh_fu_122 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            oh_fu_122 <= select_ln407_fu_440_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ow_fu_114 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            ow_fu_114 <= select_ln408_fu_501_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln406_2_reg_831 <= and_ln406_2_fu_281_p2;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        empty_70_reg_853 <= empty_70_fu_337_p2;
        empty_reg_843 <= empty_fu_301_p2;
        ic_mid2_reg_858 <= ic_mid2_fu_343_p3;
        icmp_ln407_reg_825 <= icmp_ln407_fu_257_p2;
        icmp_ln410_2_reg_873 <= icmp_ln410_2_fu_365_p2;
        icmp_ln410_mid234_reg_848 <= icmp_ln410_mid234_fu_325_p2;
        select_ln406_6_reg_837 <= select_ln406_6_fu_293_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        and_ln406_2_reg_831_pp0_iter2_reg <= and_ln406_2_reg_831;
        and_ln406_2_reg_831_pp0_iter3_reg <= and_ln406_2_reg_831_pp0_iter2_reg;
        and_ln406_2_reg_831_pp0_iter4_reg <= and_ln406_2_reg_831_pp0_iter3_reg;
        and_ln406_2_reg_831_pp0_iter5_reg <= and_ln406_2_reg_831_pp0_iter4_reg;
        and_ln406_2_reg_831_pp0_iter6_reg <= and_ln406_2_reg_831_pp0_iter5_reg;
        and_ln406_2_reg_831_pp0_iter7_reg <= and_ln406_2_reg_831_pp0_iter6_reg;
        and_ln406_2_reg_831_pp0_iter8_reg <= and_ln406_2_reg_831_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        empty_70_reg_853_pp0_iter2_reg <= empty_70_reg_853;
        empty_70_reg_853_pp0_iter3_reg <= empty_70_reg_853_pp0_iter2_reg;
        empty_70_reg_853_pp0_iter4_reg <= empty_70_reg_853_pp0_iter3_reg;
        empty_70_reg_853_pp0_iter5_reg <= empty_70_reg_853_pp0_iter4_reg;
        empty_70_reg_853_pp0_iter6_reg <= empty_70_reg_853_pp0_iter5_reg;
        empty_reg_843_pp0_iter2_reg <= empty_reg_843;
        empty_reg_843_pp0_iter3_reg <= empty_reg_843_pp0_iter2_reg;
        ic_mid2_reg_858_pp0_iter2_reg <= ic_mid2_reg_858;
        icmp_ln407_reg_825_pp0_iter2_reg <= icmp_ln407_reg_825;
        icmp_ln407_reg_825_pp0_iter3_reg <= icmp_ln407_reg_825_pp0_iter2_reg;
        icmp_ln407_reg_825_pp0_iter4_reg <= icmp_ln407_reg_825_pp0_iter3_reg;
        icmp_ln407_reg_825_pp0_iter5_reg <= icmp_ln407_reg_825_pp0_iter4_reg;
        icmp_ln407_reg_825_pp0_iter6_reg <= icmp_ln407_reg_825_pp0_iter5_reg;
        icmp_ln407_reg_825_pp0_iter7_reg <= icmp_ln407_reg_825_pp0_iter6_reg;
        icmp_ln407_reg_825_pp0_iter8_reg <= icmp_ln407_reg_825_pp0_iter7_reg;
        icmp_ln410_2_reg_873_pp0_iter2_reg <= icmp_ln410_2_reg_873;
        icmp_ln410_2_reg_873_pp0_iter3_reg <= icmp_ln410_2_reg_873_pp0_iter2_reg;
        icmp_ln410_2_reg_873_pp0_iter4_reg <= icmp_ln410_2_reg_873_pp0_iter3_reg;
        icmp_ln410_2_reg_873_pp0_iter5_reg <= icmp_ln410_2_reg_873_pp0_iter4_reg;
        icmp_ln410_2_reg_873_pp0_iter6_reg <= icmp_ln410_2_reg_873_pp0_iter5_reg;
        icmp_ln410_2_reg_873_pp0_iter7_reg <= icmp_ln410_2_reg_873_pp0_iter6_reg;
        icmp_ln410_2_reg_873_pp0_iter8_reg <= icmp_ln410_2_reg_873_pp0_iter7_reg;
        icmp_ln410_mid234_reg_848_pp0_iter2_reg <= icmp_ln410_mid234_reg_848;
        icmp_ln410_mid234_reg_848_pp0_iter3_reg <= icmp_ln410_mid234_reg_848_pp0_iter2_reg;
        oh_load_reg_877 <= oh_fu_122;
        oh_load_reg_877_pp0_iter4_reg <= oh_load_reg_877;
        oh_load_reg_877_pp0_iter5_reg <= oh_load_reg_877_pp0_iter4_reg;
        oh_load_reg_877_pp0_iter6_reg <= oh_load_reg_877_pp0_iter5_reg;
        oh_load_reg_877_pp0_iter7_reg <= oh_load_reg_877_pp0_iter6_reg;
        oh_load_reg_877_pp0_iter8_reg <= oh_load_reg_877_pp0_iter7_reg;
        select_ln406_6_reg_837_pp0_iter2_reg <= select_ln406_6_reg_837;
        select_ln406_6_reg_837_pp0_iter3_reg <= select_ln406_6_reg_837_pp0_iter2_reg;
        select_ln406_6_reg_837_pp0_iter4_reg <= select_ln406_6_reg_837_pp0_iter3_reg;
        select_ln406_6_reg_837_pp0_iter5_reg <= select_ln406_6_reg_837_pp0_iter4_reg;
        select_ln406_6_reg_837_pp0_iter6_reg <= select_ln406_6_reg_837_pp0_iter5_reg;
        select_ln406_reg_882 <= select_ln406_fu_427_p3;
        select_ln406_reg_882_pp0_iter4_reg <= select_ln406_reg_882;
        select_ln406_reg_882_pp0_iter5_reg <= select_ln406_reg_882_pp0_iter4_reg;
        select_ln406_reg_882_pp0_iter6_reg <= select_ln406_reg_882_pp0_iter5_reg;
        select_ln406_reg_882_pp0_iter7_reg <= select_ln406_reg_882_pp0_iter6_reg;
        select_ln406_reg_882_pp0_iter8_reg <= select_ln406_reg_882_pp0_iter7_reg;
        select_ln408_reg_897 <= select_ln408_fu_501_p3;
        select_ln408_reg_897_pp0_iter5_reg <= select_ln408_reg_897;
        select_ln408_reg_897_pp0_iter6_reg <= select_ln408_reg_897_pp0_iter5_reg;
        select_ln408_reg_897_pp0_iter7_reg <= select_ln408_reg_897_pp0_iter6_reg;
        val_3_reg_937 <= val_3_fu_639_p3;
    end
end

always @ (*) begin
    if (((icmp_ln406_fu_239_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        ap_sig_allocacmp_acc_load = grp_fu_746_p3;
    end else begin
        ap_sig_allocacmp_acc_load = acc_fu_106;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        b2_in_ce0_local = 1'b1;
    end else begin
        b2_in_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        s3_0_b2_pw1_b_ce0_local = 1'b1;
    end else begin
        s3_0_b2_pw1_b_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        s3_0_b2_pw1_w_ce0_local = 1'b1;
    end else begin
        s3_0_b2_pw1_w_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        sm3_ce0_local = 1'b1;
    end else begin
        sm3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (icmp_ln410_2_reg_873_pp0_iter8_reg == 1'd1))) begin
        sm3_we0_local = 1'b1;
    end else begin
        sm3_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln406_2_fu_287_p2 = (oc_fu_130 + 7'd1);

assign add_ln406_fu_245_p2 = (indvar_flatten61_fu_134 + 24'd1);

assign add_ln407_fu_385_p2 = (indvar_flatten35_fu_126 + 17'd1);

assign add_ln408_fu_371_p2 = (indvar_flatten21_fu_118 + 12'd1);

assign add_ln410_fu_359_p2 = (ic_mid2_fu_343_p3 + 7'd1);

assign add_ln412_fu_512_p2 = (grp_fu_737_p3 + zext_ln408_1_fu_508_p1);

assign add_ln419_2_fu_718_p2 = (grp_fu_756_p3 + zext_ln408_fu_710_p1);

assign add_ln419_3_fu_647_p2 = (select_ln408_reg_897_pp0_iter7_reg + 5'd1);

assign add_ln419_fu_495_p2 = (ow_mid228_fu_488_p3 + 5'd1);

assign and_ln406_2_fu_281_p2 = (xor_ln406_fu_263_p2 & icmp_ln408_fu_275_p2);

assign and_ln406_fu_319_p2 = (xor_ln406_fu_263_p2 & icmp_ln410_fu_269_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign b2_in_address0 = zext_ln412_fu_517_p1;

assign b2_in_ce0 = b2_in_ce0_local;

assign empty_69_fu_331_p2 = (icmp_ln410_mid234_fu_325_p2 | and_ln406_2_fu_281_p2);

assign empty_70_fu_337_p2 = (icmp_ln407_fu_257_p2 | empty_69_fu_331_p2);

assign empty_73_fu_467_p2 = (p_shl8_fu_447_p3 - p_shl9_fu_463_p1);

assign empty_74_fu_704_p2 = (p_shl_fu_684_p3 - p_shl7_fu_700_p1);

assign empty_fu_301_p2 = (icmp_ln407_fu_257_p2 | and_ln406_2_fu_281_p2);

assign exitcond_flatten23_not_fu_307_p2 = (icmp_ln408_fu_275_p2 ^ 1'd1);

assign grp_fu_728_p0 = grp_fu_728_p00;

assign grp_fu_728_p00 = select_ln406_6_fu_293_p3;

assign grp_fu_728_p1 = 14'd116;

assign grp_fu_728_p2 = grp_fu_728_p20;

assign grp_fu_728_p20 = ic_mid2_reg_858_pp0_iter2_reg;

assign grp_fu_737_p0 = 17'd784;

assign grp_fu_737_p1 = grp_fu_737_p10;

assign grp_fu_737_p10 = ic_mid2_fu_343_p3;

assign grp_fu_737_p2 = grp_fu_737_p20;

assign grp_fu_737_p20 = empty_73_fu_467_p2;

assign grp_fu_746_p2 = ((empty_70_reg_853_pp0_iter6_reg[0:0] == 1'b1) ? 31'd0 : ap_sig_allocacmp_acc_load);

assign grp_fu_756_p0 = 17'd900;

assign grp_fu_756_p1 = grp_fu_756_p10;

assign grp_fu_756_p10 = select_ln406_6_reg_837_pp0_iter5_reg;

assign grp_fu_756_p2 = grp_fu_756_p20;

assign grp_fu_756_p20 = add_ln419_3_fu_647_p2;

assign ic_mid2_fu_343_p3 = ((empty_70_fu_337_p2[0:0] == 1'b1) ? 7'd0 : ic_fu_110);

assign icmp_ln39_fu_589_p2 = (($signed(tmp_8_fu_579_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln406_fu_239_p2 = ((indvar_flatten61_fu_134 == 24'd10549504) ? 1'b1 : 1'b0);

assign icmp_ln407_fu_257_p2 = ((indvar_flatten35_fu_126 == 17'd90944) ? 1'b1 : 1'b0);

assign icmp_ln408_fu_275_p2 = ((indvar_flatten21_fu_118 == 12'd3248) ? 1'b1 : 1'b0);

assign icmp_ln40_fu_595_p2 = (($signed(result_fu_573_p2) < $signed(24'd16760832)) ? 1'b1 : 1'b0);

assign icmp_ln410_2_fu_365_p2 = ((add_ln410_fu_359_p2 == 7'd116) ? 1'b1 : 1'b0);

assign icmp_ln410_fu_269_p2 = ((ic_fu_110 == 7'd116) ? 1'b1 : 1'b0);

assign icmp_ln410_mid234_fu_325_p2 = (not_exitcond_flatten23_mid260_fu_313_p2 & and_ln406_fu_319_p2);

assign indvars_iv_next72121_fu_660_p2 = (oh_load_reg_877_pp0_iter8_reg + 5'd1);

assign indvars_iv_next72_dup_fu_434_p2 = (select_ln406_fu_427_p3 + 5'd1);

assign indvars_iv_next72_mid1_fu_672_p2 = (select_ln406_reg_882_pp0_iter8_reg + 5'd2);

assign indvars_iv_next72_mid2_fu_677_p3 = ((and_ln406_2_reg_831_pp0_iter8_reg[0:0] == 1'b1) ? indvars_iv_next72_mid1_fu_672_p2 : select_ln406_5_fu_665_p3);

assign not_exitcond_flatten23_mid260_fu_313_p2 = (icmp_ln407_fu_257_p2 | exitcond_flatten23_not_fu_307_p2);

assign or_ln39_fu_613_p2 = (icmp_ln40_fu_595_p2 | icmp_ln39_fu_589_p2);

assign ow_mid228_fu_488_p3 = ((empty_reg_843_pp0_iter3_reg[0:0] == 1'b1) ? 5'd0 : ow_fu_114);

assign p_shl7_fu_700_p1 = tmp_7_fu_692_p3;

assign p_shl8_fu_447_p3 = {{select_ln407_fu_440_p3}, {5'd0}};

assign p_shl9_fu_463_p1 = tmp_1_fu_455_p3;

assign p_shl_fu_684_p3 = {{indvars_iv_next72_mid2_fu_677_p3}, {5'd0}};

assign result_fu_573_p2 = ($signed(sext_ln52_fu_569_p1) + $signed(sext_ln407_fu_556_p1));

assign s3_0_b2_pw1_b_address0 = zext_ln406_fu_552_p1;

assign s3_0_b2_pw1_w_address0 = zext_ln413_fu_522_p1;

assign select_ln39_fu_605_p3 = ((icmp_ln39_fu_589_p2[0:0] == 1'b1) ? 15'd16383 : 15'd16384);

assign select_ln406_5_fu_665_p3 = ((icmp_ln407_reg_825_pp0_iter8_reg[0:0] == 1'b1) ? 5'd1 : indvars_iv_next72121_fu_660_p2);

assign select_ln406_6_fu_293_p3 = ((icmp_ln407_fu_257_p2[0:0] == 1'b1) ? add_ln406_2_fu_287_p2 : oc_fu_130);

assign select_ln406_fu_427_p3 = ((icmp_ln407_reg_825_pp0_iter2_reg[0:0] == 1'b1) ? 5'd0 : oh_fu_122);

assign select_ln407_2_fu_391_p3 = ((icmp_ln407_fu_257_p2[0:0] == 1'b1) ? 17'd1 : add_ln407_fu_385_p2);

assign select_ln407_fu_440_p3 = ((and_ln406_2_reg_831_pp0_iter2_reg[0:0] == 1'b1) ? indvars_iv_next72_dup_fu_434_p2 : select_ln406_fu_427_p3);

assign select_ln408_2_fu_377_p3 = ((empty_fu_301_p2[0:0] == 1'b1) ? 12'd1 : add_ln408_fu_371_p2);

assign select_ln408_fu_501_p3 = ((icmp_ln410_mid234_reg_848_pp0_iter3_reg[0:0] == 1'b1) ? add_ln419_fu_495_p2 : ow_mid228_fu_488_p3);

assign sext_ln407_fu_556_p1 = $signed(s3_0_b2_pw1_b_q0);

assign sext_ln52_fu_569_p1 = $signed(trunc_ln_fu_560_p4);

assign sm3_address0 = zext_ln419_1_fu_723_p1;

assign sm3_ce0 = sm3_ce0_local;

assign sm3_d0 = zext_ln415_fu_714_p1;

assign sm3_we0 = sm3_we0_local;

assign tmp_1_fu_455_p3 = {{select_ln407_fu_440_p3}, {2'd0}};

assign tmp_7_fu_692_p3 = {{indvars_iv_next72_mid2_fu_677_p3}, {1'd0}};

assign tmp_8_fu_579_p4 = {{result_fu_573_p2[23:14]}};

assign tmp_9_fu_631_p3 = val_fu_619_p3[32'd14];

assign trunc_ln415_fu_627_p1 = val_fu_619_p3[13:0];

assign trunc_ln41_fu_601_p1 = result_fu_573_p2[14:0];

assign trunc_ln_fu_560_p4 = {{grp_fu_746_p3[30:8]}};

assign val_3_fu_639_p3 = ((tmp_9_fu_631_p3[0:0] == 1'b1) ? 14'd0 : trunc_ln415_fu_627_p1);

assign val_fu_619_p3 = ((or_ln39_fu_613_p2[0:0] == 1'b1) ? select_ln39_fu_605_p3 : trunc_ln41_fu_601_p1);

assign xor_ln406_fu_263_p2 = (icmp_ln407_fu_257_p2 ^ 1'd1);

assign zext_ln406_fu_552_p1 = select_ln406_6_reg_837_pp0_iter6_reg;

assign zext_ln408_1_fu_508_p1 = select_ln408_fu_501_p3;

assign zext_ln408_fu_710_p1 = empty_74_fu_704_p2;

assign zext_ln412_fu_517_p1 = add_ln412_fu_512_p2;

assign zext_ln413_fu_522_p1 = grp_fu_728_p3;

assign zext_ln415_fu_714_p1 = val_3_reg_937;

assign zext_ln419_1_fu_723_p1 = add_ln419_2_fu_718_p2;

endmodule //Shuffle_Model_shuffle_block_s2_2_Pipeline_VITIS_LOOP_406_5_VITIS_LOOP_407_6_VITIS_LOOP_408_7_V
