// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Shuffle_Model_conv5_avgpool_Pipeline_VITIS_LOOP_485_4_VITIS_LOOP_487_5_VITIS_LOOP_488_6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sm4_address0,
        sm4_ce0,
        sm4_we0,
        sm4_d0,
        c5_out_address0,
        c5_out_ce0,
        c5_out_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] sm4_address0;
output   sm4_ce0;
output   sm4_we0;
output  [15:0] sm4_d0;
output  [15:0] c5_out_address0;
output   c5_out_ce0;
input  [13:0] c5_out_q0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln485_fu_173_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln487_fu_188_p2;
reg   [0:0] icmp_ln487_reg_545;
reg   [0:0] icmp_ln487_reg_545_pp0_iter2_reg;
reg   [0:0] icmp_ln487_reg_545_pp0_iter3_reg;
reg   [0:0] icmp_ln487_reg_545_pp0_iter4_reg;
reg   [9:0] sm4_addr_reg_558;
reg   [9:0] sm4_addr_reg_558_pp0_iter2_reg;
reg   [9:0] sm4_addr_reg_558_pp0_iter3_reg;
reg   [9:0] sm4_addr_reg_558_pp0_iter4_reg;
reg   [9:0] sm4_addr_reg_558_pp0_iter5_reg;
wire   [0:0] and_ln485_fu_260_p2;
reg   [0:0] and_ln485_reg_563;
wire   [0:0] icmp_ln488_1_fu_289_p2;
reg   [0:0] icmp_ln488_1_reg_573;
reg   [0:0] icmp_ln488_1_reg_573_pp0_iter4_reg;
reg   [0:0] icmp_ln488_1_reg_573_pp0_iter5_reg;
wire   [0:0] icmp_ln487_1_fu_355_p2;
reg   [0:0] icmp_ln487_1_reg_582;
reg   [0:0] icmp_ln487_1_reg_582_pp0_iter5_reg;
wire   [63:0] sum_fu_380_p2;
reg   [63:0] sum_reg_586;
wire   [63:0] zext_ln485_fu_208_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln490_1_fu_350_p1;
reg   [63:0] sum_1_fu_88;
wire    ap_loop_init;
reg   [2:0] w_i_fu_92;
wire   [2:0] add_ln488_fu_283_p2;
reg   [2:0] h_fu_96;
wire   [2:0] select_ln487_fu_316_p3;
reg   [5:0] indvar_flatten66_fu_100;
wire   [5:0] select_ln487_1_fu_223_p3;
reg   [10:0] c_fu_104;
wire   [10:0] select_ln485_2_fu_200_p3;
reg   [15:0] indvar_flatten81_fu_108;
wire   [15:0] add_ln485_fu_179_p2;
reg    c5_out_ce0_local;
reg    sm4_we0_local;
wire   [15:0] zext_ln494_fu_485_p1;
reg    sm4_ce0_local;
wire   [10:0] add_ln485_1_fu_194_p2;
wire   [5:0] add_ln487_1_fu_217_p2;
wire   [0:0] icmp_ln488_fu_254_p2;
wire   [0:0] xor_ln485_fu_249_p2;
wire   [0:0] empty_fu_266_p2;
wire   [2:0] w_i_22_mid2_fu_271_p3;
wire   [2:0] select_ln485_fu_303_p3;
wire   [2:0] add_ln487_fu_310_p2;
wire   [5:0] p_shl3_fu_327_p3;
wire   [5:0] zext_ln487_1_fu_323_p1;
wire   [5:0] empty_284_fu_335_p2;
wire   [15:0] grp_fu_490_p3;
wire   [15:0] zext_ln488_fu_341_p1;
(* use_dsp48 = "no" *) wire   [15:0] add_ln490_fu_345_p2;
wire   [63:0] zext_ln490_fu_376_p1;
wire   [63:0] select_ln485_1_fu_369_p3;
wire   [63:0] shl_ln493_fu_391_p2;
wire   [63:0] sum_x5_fu_396_p2;
wire   [41:0] tmp_1_fu_411_p4;
wire   [55:0] trunc_ln_fu_401_p4;
wire   [0:0] icmp_ln39_fu_421_p2;
wire   [0:0] icmp_ln40_fu_427_p2;
wire   [0:0] or_ln39_fu_451_p2;
wire   [15:0] select_ln39_fu_443_p3;
wire   [15:0] trunc_ln1_fu_433_p4;
wire   [15:0] avg_fu_457_p3;
wire   [0:0] tmp_40_fu_469_p3;
wire   [14:0] trunc_ln494_fu_465_p1;
wire   [14:0] avg_1_fu_477_p3;
wire   [10:0] grp_fu_490_p0;
wire   [5:0] grp_fu_490_p1;
wire   [2:0] grp_fu_490_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [15:0] grp_fu_490_p00;
wire   [15:0] grp_fu_490_p20;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 sum_1_fu_88 = 64'd0;
#0 w_i_fu_92 = 3'd0;
#0 h_fu_96 = 3'd0;
#0 indvar_flatten66_fu_100 = 6'd0;
#0 c_fu_104 = 11'd0;
#0 indvar_flatten81_fu_108 = 16'd0;
#0 ap_done_reg = 1'b0;
end

Shuffle_Model_mac_muladd_11ns_6ns_3ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
mac_muladd_11ns_6ns_3ns_16_4_1_U589(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_490_p0),
    .din1(grp_fu_490_p1),
    .din2(grp_fu_490_p2),
    .ce(1'b1),
    .dout(grp_fu_490_p3)
);

Shuffle_Model_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            c_fu_104 <= 11'd0;
        end else if (((icmp_ln485_fu_173_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            c_fu_104 <= select_ln485_2_fu_200_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            h_fu_96 <= 3'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            h_fu_96 <= select_ln487_fu_316_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten66_fu_100 <= 6'd0;
        end else if (((icmp_ln485_fu_173_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten66_fu_100 <= select_ln487_1_fu_223_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten81_fu_108 <= 16'd0;
        end else if (((icmp_ln485_fu_173_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten81_fu_108 <= add_ln485_fu_179_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            sum_1_fu_88 <= 64'd0;
        end else if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
            sum_1_fu_88 <= sum_fu_380_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            w_i_fu_92 <= 3'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            w_i_fu_92 <= add_ln488_fu_283_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        and_ln485_reg_563 <= and_ln485_fu_260_p2;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        icmp_ln487_1_reg_582 <= icmp_ln487_1_fu_355_p2;
        icmp_ln487_1_reg_582_pp0_iter5_reg <= icmp_ln487_1_reg_582;
        icmp_ln487_reg_545_pp0_iter2_reg <= icmp_ln487_reg_545;
        icmp_ln487_reg_545_pp0_iter3_reg <= icmp_ln487_reg_545_pp0_iter2_reg;
        icmp_ln487_reg_545_pp0_iter4_reg <= icmp_ln487_reg_545_pp0_iter3_reg;
        icmp_ln488_1_reg_573 <= icmp_ln488_1_fu_289_p2;
        icmp_ln488_1_reg_573_pp0_iter4_reg <= icmp_ln488_1_reg_573;
        icmp_ln488_1_reg_573_pp0_iter5_reg <= icmp_ln488_1_reg_573_pp0_iter4_reg;
        sm4_addr_reg_558_pp0_iter2_reg <= sm4_addr_reg_558;
        sm4_addr_reg_558_pp0_iter3_reg <= sm4_addr_reg_558_pp0_iter2_reg;
        sm4_addr_reg_558_pp0_iter4_reg <= sm4_addr_reg_558_pp0_iter3_reg;
        sm4_addr_reg_558_pp0_iter5_reg <= sm4_addr_reg_558_pp0_iter4_reg;
        sum_reg_586 <= sum_fu_380_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln487_reg_545 <= icmp_ln487_fu_188_p2;
        sm4_addr_reg_558 <= zext_ln485_fu_208_p1;
    end
end

always @ (*) begin
    if (((icmp_ln485_fu_173_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        c5_out_ce0_local = 1'b1;
    end else begin
        c5_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        sm4_ce0_local = 1'b1;
    end else begin
        sm4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (icmp_ln487_1_reg_582_pp0_iter5_reg == 1'd1) & (icmp_ln488_1_reg_573_pp0_iter5_reg == 1'd1))) begin
        sm4_we0_local = 1'b1;
    end else begin
        sm4_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln485_1_fu_194_p2 = (c_fu_104 + 11'd1);

assign add_ln485_fu_179_p2 = (indvar_flatten81_fu_108 + 16'd1);

assign add_ln487_1_fu_217_p2 = (indvar_flatten66_fu_100 + 6'd1);

assign add_ln487_fu_310_p2 = (select_ln485_fu_303_p3 + 3'd1);

assign add_ln488_fu_283_p2 = (w_i_22_mid2_fu_271_p3 + 3'd1);

assign add_ln490_fu_345_p2 = (grp_fu_490_p3 + zext_ln488_fu_341_p1);

assign and_ln485_fu_260_p2 = (xor_ln485_fu_249_p2 & icmp_ln488_fu_254_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign avg_1_fu_477_p3 = ((tmp_40_fu_469_p3[0:0] == 1'b1) ? 15'd0 : trunc_ln494_fu_465_p1);

assign avg_fu_457_p3 = ((or_ln39_fu_451_p2[0:0] == 1'b1) ? select_ln39_fu_443_p3 : trunc_ln1_fu_433_p4);

assign c5_out_address0 = zext_ln490_1_fu_350_p1;

assign c5_out_ce0 = c5_out_ce0_local;

assign empty_284_fu_335_p2 = (p_shl3_fu_327_p3 - zext_ln487_1_fu_323_p1);

assign empty_fu_266_p2 = (icmp_ln487_reg_545_pp0_iter2_reg | and_ln485_fu_260_p2);

assign grp_fu_490_p0 = grp_fu_490_p00;

assign grp_fu_490_p00 = select_ln485_2_fu_200_p3;

assign grp_fu_490_p1 = 16'd49;

assign grp_fu_490_p2 = grp_fu_490_p20;

assign grp_fu_490_p20 = w_i_22_mid2_fu_271_p3;

assign icmp_ln39_fu_421_p2 = (($signed(tmp_1_fu_411_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln40_fu_427_p2 = (($signed(trunc_ln_fu_401_p4) < $signed(56'd72057594037911552)) ? 1'b1 : 1'b0);

assign icmp_ln485_fu_173_p2 = ((indvar_flatten81_fu_108 == 16'd50176) ? 1'b1 : 1'b0);

assign icmp_ln487_1_fu_355_p2 = ((select_ln487_fu_316_p3 == 3'd6) ? 1'b1 : 1'b0);

assign icmp_ln487_fu_188_p2 = ((indvar_flatten66_fu_100 == 6'd49) ? 1'b1 : 1'b0);

assign icmp_ln488_1_fu_289_p2 = ((add_ln488_fu_283_p2 == 3'd7) ? 1'b1 : 1'b0);

assign icmp_ln488_fu_254_p2 = ((w_i_fu_92 == 3'd7) ? 1'b1 : 1'b0);

assign or_ln39_fu_451_p2 = (icmp_ln40_fu_427_p2 | icmp_ln39_fu_421_p2);

assign p_shl3_fu_327_p3 = {{select_ln487_fu_316_p3}, {3'd0}};

assign select_ln39_fu_443_p3 = ((icmp_ln39_fu_421_p2[0:0] == 1'b1) ? 16'd16383 : 16'd49152);

assign select_ln485_1_fu_369_p3 = ((icmp_ln487_reg_545_pp0_iter4_reg[0:0] == 1'b1) ? 64'd0 : sum_1_fu_88);

assign select_ln485_2_fu_200_p3 = ((icmp_ln487_fu_188_p2[0:0] == 1'b1) ? add_ln485_1_fu_194_p2 : c_fu_104);

assign select_ln485_fu_303_p3 = ((icmp_ln487_reg_545_pp0_iter3_reg[0:0] == 1'b1) ? 3'd0 : h_fu_96);

assign select_ln487_1_fu_223_p3 = ((icmp_ln487_fu_188_p2[0:0] == 1'b1) ? 6'd1 : add_ln487_1_fu_217_p2);

assign select_ln487_fu_316_p3 = ((and_ln485_reg_563[0:0] == 1'b1) ? add_ln487_fu_310_p2 : select_ln485_fu_303_p3);

assign shl_ln493_fu_391_p2 = sum_reg_586 << 64'd2;

assign sm4_address0 = sm4_addr_reg_558_pp0_iter5_reg;

assign sm4_ce0 = sm4_ce0_local;

assign sm4_d0 = zext_ln494_fu_485_p1;

assign sm4_we0 = sm4_we0_local;

assign sum_fu_380_p2 = (zext_ln490_fu_376_p1 + select_ln485_1_fu_369_p3);

assign sum_x5_fu_396_p2 = (shl_ln493_fu_391_p2 + sum_reg_586);

assign tmp_1_fu_411_p4 = {{sum_x5_fu_396_p2[63:22]}};

assign tmp_40_fu_469_p3 = avg_fu_457_p3[32'd15];

assign trunc_ln1_fu_433_p4 = {{sum_x5_fu_396_p2[23:8]}};

assign trunc_ln494_fu_465_p1 = avg_fu_457_p3[14:0];

assign trunc_ln_fu_401_p4 = {{sum_x5_fu_396_p2[63:8]}};

assign w_i_22_mid2_fu_271_p3 = ((empty_fu_266_p2[0:0] == 1'b1) ? 3'd0 : w_i_fu_92);

assign xor_ln485_fu_249_p2 = (icmp_ln487_reg_545_pp0_iter2_reg ^ 1'd1);

assign zext_ln485_fu_208_p1 = select_ln485_2_fu_200_p3;

assign zext_ln487_1_fu_323_p1 = select_ln487_fu_316_p3;

assign zext_ln488_fu_341_p1 = empty_284_fu_335_p2;

assign zext_ln490_1_fu_350_p1 = add_ln490_fu_345_p2;

assign zext_ln490_fu_376_p1 = c5_out_q0;

assign zext_ln494_fu_485_p1 = avg_1_fu_477_p3;

endmodule //Shuffle_Model_conv5_avgpool_Pipeline_VITIS_LOOP_485_4_VITIS_LOOP_487_5_VITIS_LOOP_488_6
