// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Shuffle_Model_shuffle_block_s1_7_Pipeline_VITIS_LOOP_325_13_VITIS_LOOP_326_14_VITIS_LOOP_327_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sm2_address0,
        sm2_ce0,
        sm2_we0,
        sm2_d0,
        concat_1_address0,
        concat_1_ce0,
        concat_1_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [18:0] sm2_address0;
output   sm2_ce0;
output   sm2_we0;
output  [15:0] sm2_d0;
output  [16:0] concat_1_address0;
output   concat_1_ce0;
input  [15:0] concat_1_q0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln325_fu_135_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln326_fu_153_p2;
reg   [0:0] icmp_ln326_reg_423;
reg   [0:0] icmp_ln326_reg_423_pp0_iter1_reg;
reg   [0:0] icmp_ln326_reg_423_pp0_iter2_reg;
wire   [8:0] select_ln325_2_fu_165_p3;
reg   [8:0] select_ln325_2_reg_431;
wire   [0:0] and_ln325_fu_223_p2;
reg   [0:0] and_ln325_reg_446;
wire   [2:0] add_ln328_fu_246_p2;
reg   [2:0] add_ln328_reg_457;
wire   [2:0] indvars_iv_next34_mid2_fu_292_p3;
reg   [2:0] indvars_iv_next34_mid2_reg_462;
wire   [63:0] zext_ln329_fu_333_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln328_1_fu_361_p1;
reg   [2:0] w_i_fu_60;
wire    ap_loop_init;
reg   [2:0] h_fu_64;
wire   [2:0] select_ln326_fu_299_p3;
reg   [5:0] indvar_flatten161_fu_68;
wire   [5:0] select_ln326_1_fu_183_p3;
reg   [5:0] ap_sig_allocacmp_indvar_flatten161_load;
reg   [8:0] c_fu_72;
reg   [8:0] ap_sig_allocacmp_c_load;
reg   [14:0] indvar_flatten176_fu_76;
wire   [14:0] add_ln325_1_fu_141_p2;
reg   [14:0] ap_sig_allocacmp_indvar_flatten176_load;
reg    concat_1_ce0_local;
reg    sm2_we0_local;
reg    sm2_ce0_local;
wire   [8:0] add_ln325_fu_159_p2;
wire   [5:0] add_ln326_fu_177_p2;
wire   [0:0] icmp_ln327_fu_217_p2;
wire   [0:0] xor_ln325_fu_212_p2;
wire   [0:0] empty_fu_229_p2;
wire   [2:0] w_i_6_mid2_fu_234_p3;
wire   [2:0] indvars_iv_next34240_fu_267_p2;
wire   [2:0] select_ln325_fu_260_p3;
wire   [2:0] indvars_iv_next34_mid1_fu_286_p2;
wire   [2:0] select_ln325_1_fu_273_p3;
wire   [2:0] indvars_iv_next34_dup_fu_280_p2;
wire   [5:0] p_shl1_fu_310_p3;
wire   [5:0] zext_ln326_fu_306_p1;
wire   [5:0] empty_110_fu_318_p2;
wire   [14:0] grp_fu_366_p3;
wire   [14:0] p_cast35_fu_324_p1;
(* use_dsp48 = "no" *) wire   [14:0] add_ln329_fu_328_p2;
wire   [5:0] tmp_1_fu_346_p3;
wire   [15:0] grp_fu_375_p3;
wire   [15:0] zext_ln327_fu_352_p1;
(* use_dsp48 = "no" *) wire   [15:0] add_ln328_1_fu_356_p2;
wire   [8:0] grp_fu_366_p0;
wire   [5:0] grp_fu_366_p1;
wire   [2:0] grp_fu_366_p2;
wire   [8:0] grp_fu_375_p0;
wire   [6:0] grp_fu_375_p1;
wire   [2:0] grp_fu_375_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [14:0] grp_fu_366_p00;
wire   [14:0] grp_fu_366_p20;
wire   [15:0] grp_fu_375_p00;
wire   [15:0] grp_fu_375_p20;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 w_i_fu_60 = 3'd0;
#0 h_fu_64 = 3'd0;
#0 indvar_flatten161_fu_68 = 6'd0;
#0 c_fu_72 = 9'd0;
#0 indvar_flatten176_fu_76 = 15'd0;
#0 ap_done_reg = 1'b0;
end

Shuffle_Model_mac_muladd_9ns_6ns_3ns_15_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 3 ),
    .dout_WIDTH( 15 ))
mac_muladd_9ns_6ns_3ns_15_4_1_U557(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_366_p0),
    .din1(grp_fu_366_p1),
    .din2(grp_fu_366_p2),
    .ce(1'b1),
    .dout(grp_fu_366_p3)
);

Shuffle_Model_mac_muladd_9ns_7ns_3ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
mac_muladd_9ns_7ns_3ns_16_4_1_U558(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_375_p0),
    .din1(grp_fu_375_p1),
    .din2(grp_fu_375_p2),
    .ce(1'b1),
    .dout(grp_fu_375_p3)
);

Shuffle_Model_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln325_fu_135_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            c_fu_72 <= select_ln325_2_fu_165_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_72 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            h_fu_64 <= 3'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            h_fu_64 <= select_ln326_fu_299_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln325_fu_135_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten161_fu_68 <= select_ln326_1_fu_183_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten161_fu_68 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln325_fu_135_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten176_fu_76 <= add_ln325_1_fu_141_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten176_fu_76 <= 15'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            w_i_fu_60 <= 3'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            w_i_fu_60 <= add_ln328_fu_246_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln328_reg_457 <= add_ln328_fu_246_p2;
        and_ln325_reg_446 <= and_ln325_fu_223_p2;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        icmp_ln326_reg_423_pp0_iter2_reg <= icmp_ln326_reg_423_pp0_iter1_reg;
        indvars_iv_next34_mid2_reg_462 <= indvars_iv_next34_mid2_fu_292_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln326_reg_423 <= icmp_ln326_fu_153_p2;
        icmp_ln326_reg_423_pp0_iter1_reg <= icmp_ln326_reg_423;
        select_ln325_2_reg_431 <= select_ln325_2_fu_165_p3;
    end
end

always @ (*) begin
    if (((icmp_ln325_fu_135_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_c_load = 9'd0;
    end else begin
        ap_sig_allocacmp_c_load = c_fu_72;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten161_load = 6'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten161_load = indvar_flatten161_fu_68;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten176_load = 15'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten176_load = indvar_flatten176_fu_76;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        concat_1_ce0_local = 1'b1;
    end else begin
        concat_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        sm2_ce0_local = 1'b1;
    end else begin
        sm2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        sm2_we0_local = 1'b1;
    end else begin
        sm2_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln325_1_fu_141_p2 = (ap_sig_allocacmp_indvar_flatten176_load + 15'd1);

assign add_ln325_fu_159_p2 = (ap_sig_allocacmp_c_load + 9'd1);

assign add_ln326_fu_177_p2 = (ap_sig_allocacmp_indvar_flatten161_load + 6'd1);

assign add_ln328_1_fu_356_p2 = (grp_fu_375_p3 + zext_ln327_fu_352_p1);

assign add_ln328_fu_246_p2 = (w_i_6_mid2_fu_234_p3 + 3'd1);

assign add_ln329_fu_328_p2 = (grp_fu_366_p3 + p_cast35_fu_324_p1);

assign and_ln325_fu_223_p2 = (xor_ln325_fu_212_p2 & icmp_ln327_fu_217_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign concat_1_address0 = zext_ln329_fu_333_p1;

assign concat_1_ce0 = concat_1_ce0_local;

assign empty_110_fu_318_p2 = (p_shl1_fu_310_p3 - zext_ln326_fu_306_p1);

assign empty_fu_229_p2 = (icmp_ln326_reg_423_pp0_iter1_reg | and_ln325_fu_223_p2);

assign grp_fu_366_p0 = grp_fu_366_p00;

assign grp_fu_366_p00 = select_ln325_2_fu_165_p3;

assign grp_fu_366_p1 = 15'd49;

assign grp_fu_366_p2 = grp_fu_366_p20;

assign grp_fu_366_p20 = w_i_6_mid2_fu_234_p3;

assign grp_fu_375_p0 = grp_fu_375_p00;

assign grp_fu_375_p00 = select_ln325_2_reg_431;

assign grp_fu_375_p1 = 16'd81;

assign grp_fu_375_p2 = grp_fu_375_p20;

assign grp_fu_375_p20 = add_ln328_reg_457;

assign icmp_ln325_fu_135_p2 = ((ap_sig_allocacmp_indvar_flatten176_load == 15'd22736) ? 1'b1 : 1'b0);

assign icmp_ln326_fu_153_p2 = ((ap_sig_allocacmp_indvar_flatten161_load == 6'd49) ? 1'b1 : 1'b0);

assign icmp_ln327_fu_217_p2 = ((w_i_fu_60 == 3'd7) ? 1'b1 : 1'b0);

assign indvars_iv_next34240_fu_267_p2 = (h_fu_64 + 3'd1);

assign indvars_iv_next34_dup_fu_280_p2 = (select_ln325_fu_260_p3 + 3'd1);

assign indvars_iv_next34_mid1_fu_286_p2 = (select_ln325_fu_260_p3 + 3'd2);

assign indvars_iv_next34_mid2_fu_292_p3 = ((and_ln325_reg_446[0:0] == 1'b1) ? indvars_iv_next34_mid1_fu_286_p2 : select_ln325_1_fu_273_p3);

assign p_cast35_fu_324_p1 = empty_110_fu_318_p2;

assign p_shl1_fu_310_p3 = {{select_ln326_fu_299_p3}, {3'd0}};

assign select_ln325_1_fu_273_p3 = ((icmp_ln326_reg_423_pp0_iter2_reg[0:0] == 1'b1) ? 3'd1 : indvars_iv_next34240_fu_267_p2);

assign select_ln325_2_fu_165_p3 = ((icmp_ln326_fu_153_p2[0:0] == 1'b1) ? add_ln325_fu_159_p2 : ap_sig_allocacmp_c_load);

assign select_ln325_fu_260_p3 = ((icmp_ln326_reg_423_pp0_iter2_reg[0:0] == 1'b1) ? 3'd0 : h_fu_64);

assign select_ln326_1_fu_183_p3 = ((icmp_ln326_fu_153_p2[0:0] == 1'b1) ? 6'd1 : add_ln326_fu_177_p2);

assign select_ln326_fu_299_p3 = ((and_ln325_reg_446[0:0] == 1'b1) ? indvars_iv_next34_dup_fu_280_p2 : select_ln325_fu_260_p3);

assign sm2_address0 = zext_ln328_1_fu_361_p1;

assign sm2_ce0 = sm2_ce0_local;

assign sm2_d0 = concat_1_q0;

assign sm2_we0 = sm2_we0_local;

assign tmp_1_fu_346_p3 = {{indvars_iv_next34_mid2_reg_462}, {indvars_iv_next34_mid2_reg_462}};

assign w_i_6_mid2_fu_234_p3 = ((empty_fu_229_p2[0:0] == 1'b1) ? 3'd0 : w_i_fu_60);

assign xor_ln325_fu_212_p2 = (icmp_ln326_reg_423_pp0_iter1_reg ^ 1'd1);

assign zext_ln326_fu_306_p1 = select_ln326_fu_299_p3;

assign zext_ln327_fu_352_p1 = tmp_1_fu_346_p3;

assign zext_ln328_1_fu_361_p1 = add_ln328_1_fu_356_p2;

assign zext_ln329_fu_333_p1 = add_ln329_fu_328_p2;

endmodule //Shuffle_Model_shuffle_block_s1_7_Pipeline_VITIS_LOOP_325_13_VITIS_LOOP_326_14_VITIS_LOOP_327_1
