// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Shuffle_Model_dw_conv3x3_17 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sm3_address0,
        sm3_ce0,
        sm3_q0,
        b2_dw_out_address0,
        b2_dw_out_ce0,
        b2_dw_out_we0,
        b2_dw_out_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [17:0] sm3_address0;
output   sm3_ce0;
input  [15:0] sm3_q0;
output  [14:0] b2_dw_out_address0;
output   b2_dw_out_ce0;
output   b2_dw_out_we0;
output  [14:0] b2_dw_out_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln183_fu_265_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [5:0] s2_0_b2_dw_b_address0;
wire   [9:0] s2_0_b2_dw_b_q0;
wire   [9:0] s2_0_b2_dw_w_address0;
wire  signed [11:0] s2_0_b2_dw_w_q0;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln183_reg_951;
wire   [0:0] icmp_ln184_fu_277_p2;
reg   [0:0] icmp_ln184_reg_955;
wire   [0:0] xor_ln183_fu_283_p2;
reg   [0:0] xor_ln183_reg_963;
wire   [0:0] icmp_ln185_fu_289_p2;
reg   [0:0] icmp_ln185_reg_969;
wire   [0:0] and_ln183_13_fu_295_p2;
reg   [0:0] and_ln183_13_reg_974;
wire   [0:0] empty_fu_301_p2;
reg   [0:0] empty_reg_980;
reg   [0:0] empty_reg_980_pp0_iter2_reg;
reg   [0:0] empty_reg_980_pp0_iter3_reg;
wire   [5:0] select_ln183_8_fu_395_p3;
reg   [5:0] select_ln183_8_reg_986;
reg   [5:0] select_ln183_8_reg_986_pp0_iter3_reg;
reg   [5:0] select_ln183_8_reg_986_pp0_iter4_reg;
reg   [5:0] select_ln183_8_reg_986_pp0_iter5_reg;
wire   [0:0] exitcond_flatten_mid238_fu_429_p2;
reg   [0:0] exitcond_flatten_mid238_reg_994;
reg   [0:0] exitcond_flatten_mid238_reg_994_pp0_iter3_reg;
wire   [4:0] select_ln184_fu_435_p3;
reg   [4:0] select_ln184_reg_999;
reg   [4:0] select_ln184_reg_999_pp0_iter3_reg;
reg   [4:0] select_ln184_reg_999_pp0_iter4_reg;
reg   [4:0] select_ln184_reg_999_pp0_iter5_reg;
reg   [4:0] select_ln184_reg_999_pp0_iter6_reg;
reg   [4:0] select_ln184_reg_999_pp0_iter7_reg;
wire   [0:0] empty_232_fu_447_p2;
reg   [0:0] empty_232_reg_1005;
reg   [0:0] empty_232_reg_1005_pp0_iter3_reg;
reg   [0:0] empty_232_reg_1005_pp0_iter4_reg;
reg   [0:0] empty_232_reg_1005_pp0_iter5_reg;
reg   [0:0] empty_232_reg_1005_pp0_iter6_reg;
wire   [1:0] kw_mid2_fu_489_p3;
reg   [1:0] kw_mid2_reg_1010;
reg   [1:0] kw_mid2_reg_1010_pp0_iter3_reg;
reg   [1:0] kw_mid2_reg_1010_pp0_iter4_reg;
wire   [1:0] select_ln187_fu_497_p3;
reg   [1:0] select_ln187_reg_1016;
reg   [1:0] select_ln187_reg_1016_pp0_iter3_reg;
reg   [1:0] select_ln187_reg_1016_pp0_iter4_reg;
wire   [0:0] icmp_ln188_7_fu_527_p2;
reg   [0:0] icmp_ln188_7_reg_1027;
reg   [0:0] icmp_ln188_7_reg_1027_pp0_iter3_reg;
reg   [0:0] icmp_ln188_7_reg_1027_pp0_iter4_reg;
reg   [0:0] icmp_ln188_7_reg_1027_pp0_iter5_reg;
reg   [0:0] icmp_ln188_7_reg_1027_pp0_iter6_reg;
reg   [0:0] icmp_ln188_7_reg_1027_pp0_iter7_reg;
wire   [0:0] icmp_ln187_fu_533_p2;
reg   [0:0] icmp_ln187_reg_1031;
reg   [0:0] icmp_ln187_reg_1031_pp0_iter3_reg;
reg   [0:0] icmp_ln187_reg_1031_pp0_iter4_reg;
reg   [0:0] icmp_ln187_reg_1031_pp0_iter5_reg;
reg   [0:0] icmp_ln187_reg_1031_pp0_iter6_reg;
reg   [0:0] icmp_ln187_reg_1031_pp0_iter7_reg;
wire   [4:0] select_ln185_fu_594_p3;
reg   [4:0] select_ln185_reg_1035;
reg   [4:0] select_ln185_reg_1035_pp0_iter5_reg;
reg   [4:0] select_ln185_reg_1035_pp0_iter6_reg;
wire   [27:0] mul_ln193_fu_709_p2;
reg   [27:0] mul_ln193_reg_1070;
wire   [14:0] select_ln39_fu_801_p3;
reg   [14:0] select_ln39_reg_1080;
reg    ap_condition_exit_pp0_iter2_stage0;
wire   [63:0] zext_ln192_7_fu_675_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln193_fu_692_p1;
wire   [63:0] zext_ln183_fu_697_p1;
wire   [63:0] zext_ln197_fu_847_p1;
reg   [63:0] acc_10_fu_114;
wire   [63:0] acc_fu_735_p2;
wire    ap_loop_init;
reg   [1:0] kw_fu_118;
wire   [1:0] add_ln188_fu_521_p2;
reg   [1:0] kh_fu_122;
reg   [3:0] indvar_flatten_fu_126;
wire   [3:0] select_ln187_8_fu_545_p3;
reg   [4:0] ow_fu_130;
reg   [8:0] indvar_flatten14_fu_134;
wire   [8:0] select_ln185_7_fu_313_p3;
reg   [4:0] oh_fu_138;
reg   [12:0] indvar_flatten39_fu_142;
wire   [12:0] select_ln184_7_fu_327_p3;
reg   [5:0] c_fu_146;
reg   [18:0] indvar_flatten74_fu_150;
wire   [18:0] add_ln183_fu_271_p2;
reg    sm3_ce0_local;
reg    s2_0_b2_dw_w_ce0_local;
reg    s2_0_b2_dw_b_ce0_local;
reg    b2_dw_out_we0_local;
reg    b2_dw_out_ce0_local;
wire   [8:0] add_ln185_7_fu_307_p2;
wire   [12:0] add_ln184_7_fu_321_p2;
wire   [0:0] icmp_ln188_fu_372_p2;
wire   [5:0] add_ln18382_fu_389_p2;
wire   [4:0] select_ln183_fu_365_p3;
wire   [0:0] exitcond_flatten16_not_fu_408_p2;
wire   [0:0] and_ln183_fu_378_p2;
wire   [0:0] not_exitcond_flatten16_mid273_fu_413_p2;
wire   [0:0] icmp_ln18796_fu_383_p2;
wire   [0:0] and_ln183_14_fu_424_p2;
wire   [4:0] add_ln184_fu_402_p2;
wire   [0:0] empty_231_fu_442_p2;
wire   [0:0] icmp_ln188_mid234_fu_418_p2;
wire   [0:0] not_exitcond_flatten_mid238_fu_460_p2;
wire   [1:0] kh_mid26_fu_452_p3;
wire   [0:0] empty_233_fu_478_p2;
wire   [0:0] icmp_ln188_mid213_fu_466_p2;
wire   [0:0] empty_234_fu_483_p2;
wire   [1:0] add_ln187_fu_472_p2;
wire   [3:0] add_ln187_7_fu_539_p2;
wire   [4:0] ow_mid221_fu_581_p3;
wire   [4:0] add_ln185_fu_588_p2;
wire   [5:0] tmp_2_fu_601_p3;
wire   [8:0] tmp_1_4_fu_627_p3;
wire   [9:0] p_shl101_fu_634_p1;
wire   [9:0] zext_ln183_15_fu_624_p1;
wire   [3:0] p_shl_fu_647_p3;
wire   [3:0] zext_ln187_2_fu_644_p1;
wire   [3:0] empty_241_fu_654_p2;
wire   [11:0] grp_fu_861_p4;
wire   [17:0] zext_ln192_fu_667_p1;
wire   [17:0] grp_fu_852_p3;
(* use_dsp48 = "no" *) wire   [17:0] add_ln192_fu_670_p2;
wire   [9:0] empty_236_fu_638_p2;
wire   [9:0] zext_ln188_9_fu_664_p1;
wire   [9:0] add_ln193_7_fu_680_p2;
wire   [9:0] zext_ln188_fu_660_p1;
wire   [9:0] add_ln193_fu_686_p2;
wire  signed [63:0] sext_ln192_fu_732_p1;
wire   [63:0] acc_11_mid29_fu_718_p3;
wire   [55:0] trunc_ln_fu_741_p4;
wire  signed [56:0] sext_ln198_fu_751_p1;
wire  signed [56:0] sext_ln184_fu_725_p1;
wire   [56:0] add_ln198_fu_755_p2;
wire   [42:0] tmp_33_fu_761_p4;
wire   [0:0] icmp_ln39_fu_771_p2;
wire   [0:0] icmp_ln40_fu_777_p2;
wire   [0:0] or_ln39_fu_795_p2;
wire   [14:0] select_ln39_10_fu_787_p3;
wire   [14:0] trunc_ln41_fu_783_p1;
wire   [6:0] tmp_32_fu_821_p3;
wire   [9:0] p_shl2_fu_814_p3;
wire   [9:0] p_shl100_fu_828_p1;
wire   [9:0] empty_238_fu_832_p2;
wire   [14:0] grp_fu_872_p3;
wire   [14:0] zext_ln185_fu_838_p1;
(* use_dsp48 = "no" *) wire   [14:0] add_ln197_fu_842_p2;
wire   [11:0] grp_fu_852_p0;
wire   [5:0] grp_fu_852_p1;
wire   [5:0] grp_fu_852_p2;
wire   [1:0] grp_fu_861_p0;
wire   [5:0] grp_fu_861_p1;
wire   [5:0] grp_fu_861_p2;
wire   [1:0] grp_fu_861_p3;
wire   [9:0] grp_fu_872_p0;
wire   [5:0] grp_fu_872_p1;
wire   [4:0] grp_fu_872_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [17:0] grp_fu_852_p10;
wire   [17:0] grp_fu_852_p20;
wire   [5:0] grp_fu_861_p00;
wire   [11:0] grp_fu_861_p30;
wire   [14:0] grp_fu_872_p10;
wire   [14:0] grp_fu_872_p20;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 acc_10_fu_114 = 64'd0;
#0 kw_fu_118 = 2'd0;
#0 kh_fu_122 = 2'd0;
#0 indvar_flatten_fu_126 = 4'd0;
#0 ow_fu_130 = 5'd0;
#0 indvar_flatten14_fu_134 = 9'd0;
#0 oh_fu_138 = 5'd0;
#0 indvar_flatten39_fu_142 = 13'd0;
#0 c_fu_146 = 6'd0;
#0 indvar_flatten74_fu_150 = 19'd0;
#0 ap_done_reg = 1'b0;
end

Shuffle_Model_dw_conv3x3_17_s2_0_b2_dw_b_ROM_AUTO_1R #(
    .DataWidth( 10 ),
    .AddressRange( 58 ),
    .AddressWidth( 6 ))
s2_0_b2_dw_b_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(s2_0_b2_dw_b_address0),
    .ce0(s2_0_b2_dw_b_ce0_local),
    .q0(s2_0_b2_dw_b_q0)
);

Shuffle_Model_dw_conv3x3_17_s2_0_b2_dw_w_ROM_AUTO_1R #(
    .DataWidth( 12 ),
    .AddressRange( 522 ),
    .AddressWidth( 10 ))
s2_0_b2_dw_w_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(s2_0_b2_dw_w_address0),
    .ce0(s2_0_b2_dw_w_ce0_local),
    .q0(s2_0_b2_dw_w_q0)
);

Shuffle_Model_mul_12s_16s_28_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 28 ))
mul_12s_16s_28_1_1_U68(
    .din0(s2_0_b2_dw_w_q0),
    .din1(sm3_q0),
    .dout(mul_ln193_fu_709_p2)
);

Shuffle_Model_mac_muladd_12ns_6ns_6ns_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 6 ),
    .dout_WIDTH( 18 ))
mac_muladd_12ns_6ns_6ns_18_4_1_U69(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_852_p0),
    .din1(grp_fu_852_p1),
    .din2(grp_fu_852_p2),
    .ce(1'b1),
    .dout(grp_fu_852_p3)
);

Shuffle_Model_ama_addmuladd_2ns_6ns_6ns_2ns_12_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 6 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 12 ))
ama_addmuladd_2ns_6ns_6ns_2ns_12_4_1_U70(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_861_p0),
    .din1(grp_fu_861_p1),
    .din2(grp_fu_861_p2),
    .din3(grp_fu_861_p3),
    .ce(1'b1),
    .dout(grp_fu_861_p4)
);

Shuffle_Model_mac_muladd_10ns_6ns_5ns_15_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 5 ),
    .dout_WIDTH( 15 ))
mac_muladd_10ns_6ns_5ns_15_4_1_U71(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_872_p0),
    .din1(grp_fu_872_p1),
    .din2(grp_fu_872_p2),
    .ce(1'b1),
    .dout(grp_fu_872_p3)
);

Shuffle_Model_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter2_stage0)) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_10_fu_114 <= 64'd0;
        end else if ((ap_enable_reg_pp0_iter7 == 1'b1)) begin
            acc_10_fu_114 <= acc_fu_735_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            c_fu_146 <= 6'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln183_reg_951 == 1'd0))) begin
            c_fu_146 <= select_ln183_8_fu_395_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten14_fu_134 <= 9'd0;
        end else if (((icmp_ln183_fu_265_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten14_fu_134 <= select_ln185_7_fu_313_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten39_fu_142 <= 13'd0;
        end else if (((icmp_ln183_fu_265_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten39_fu_142 <= select_ln184_7_fu_327_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten74_fu_150 <= 19'd0;
        end else if (((icmp_ln183_fu_265_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten74_fu_150 <= add_ln183_fu_271_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            indvar_flatten_fu_126 <= 4'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln183_reg_951 == 1'd0))) begin
            indvar_flatten_fu_126 <= select_ln187_8_fu_545_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            kh_fu_122 <= 2'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln183_reg_951 == 1'd0))) begin
            kh_fu_122 <= select_ln187_fu_497_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            kw_fu_118 <= 2'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln183_reg_951 == 1'd0))) begin
            kw_fu_118 <= add_ln188_fu_521_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            oh_fu_138 <= 5'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln183_reg_951 == 1'd0))) begin
            oh_fu_138 <= select_ln184_fu_435_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ow_fu_130 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            ow_fu_130 <= select_ln185_fu_594_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln183_13_reg_974 <= and_ln183_13_fu_295_p2;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        empty_reg_980 <= empty_fu_301_p2;
        icmp_ln183_reg_951 <= icmp_ln183_fu_265_p2;
        icmp_ln184_reg_955 <= icmp_ln184_fu_277_p2;
        icmp_ln185_reg_969 <= icmp_ln185_fu_289_p2;
        xor_ln183_reg_963 <= xor_ln183_fu_283_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        empty_232_reg_1005 <= empty_232_fu_447_p2;
        empty_232_reg_1005_pp0_iter3_reg <= empty_232_reg_1005;
        empty_232_reg_1005_pp0_iter4_reg <= empty_232_reg_1005_pp0_iter3_reg;
        empty_232_reg_1005_pp0_iter5_reg <= empty_232_reg_1005_pp0_iter4_reg;
        empty_232_reg_1005_pp0_iter6_reg <= empty_232_reg_1005_pp0_iter5_reg;
        empty_reg_980_pp0_iter2_reg <= empty_reg_980;
        empty_reg_980_pp0_iter3_reg <= empty_reg_980_pp0_iter2_reg;
        exitcond_flatten_mid238_reg_994 <= exitcond_flatten_mid238_fu_429_p2;
        exitcond_flatten_mid238_reg_994_pp0_iter3_reg <= exitcond_flatten_mid238_reg_994;
        icmp_ln187_reg_1031 <= icmp_ln187_fu_533_p2;
        icmp_ln187_reg_1031_pp0_iter3_reg <= icmp_ln187_reg_1031;
        icmp_ln187_reg_1031_pp0_iter4_reg <= icmp_ln187_reg_1031_pp0_iter3_reg;
        icmp_ln187_reg_1031_pp0_iter5_reg <= icmp_ln187_reg_1031_pp0_iter4_reg;
        icmp_ln187_reg_1031_pp0_iter6_reg <= icmp_ln187_reg_1031_pp0_iter5_reg;
        icmp_ln187_reg_1031_pp0_iter7_reg <= icmp_ln187_reg_1031_pp0_iter6_reg;
        icmp_ln188_7_reg_1027 <= icmp_ln188_7_fu_527_p2;
        icmp_ln188_7_reg_1027_pp0_iter3_reg <= icmp_ln188_7_reg_1027;
        icmp_ln188_7_reg_1027_pp0_iter4_reg <= icmp_ln188_7_reg_1027_pp0_iter3_reg;
        icmp_ln188_7_reg_1027_pp0_iter5_reg <= icmp_ln188_7_reg_1027_pp0_iter4_reg;
        icmp_ln188_7_reg_1027_pp0_iter6_reg <= icmp_ln188_7_reg_1027_pp0_iter5_reg;
        icmp_ln188_7_reg_1027_pp0_iter7_reg <= icmp_ln188_7_reg_1027_pp0_iter6_reg;
        kw_mid2_reg_1010 <= kw_mid2_fu_489_p3;
        kw_mid2_reg_1010_pp0_iter3_reg <= kw_mid2_reg_1010;
        kw_mid2_reg_1010_pp0_iter4_reg <= kw_mid2_reg_1010_pp0_iter3_reg;
        mul_ln193_reg_1070 <= mul_ln193_fu_709_p2;
        select_ln183_8_reg_986 <= select_ln183_8_fu_395_p3;
        select_ln183_8_reg_986_pp0_iter3_reg <= select_ln183_8_reg_986;
        select_ln183_8_reg_986_pp0_iter4_reg <= select_ln183_8_reg_986_pp0_iter3_reg;
        select_ln183_8_reg_986_pp0_iter5_reg <= select_ln183_8_reg_986_pp0_iter4_reg;
        select_ln184_reg_999 <= select_ln184_fu_435_p3;
        select_ln184_reg_999_pp0_iter3_reg <= select_ln184_reg_999;
        select_ln184_reg_999_pp0_iter4_reg <= select_ln184_reg_999_pp0_iter3_reg;
        select_ln184_reg_999_pp0_iter5_reg <= select_ln184_reg_999_pp0_iter4_reg;
        select_ln184_reg_999_pp0_iter6_reg <= select_ln184_reg_999_pp0_iter5_reg;
        select_ln184_reg_999_pp0_iter7_reg <= select_ln184_reg_999_pp0_iter6_reg;
        select_ln185_reg_1035 <= select_ln185_fu_594_p3;
        select_ln185_reg_1035_pp0_iter5_reg <= select_ln185_reg_1035;
        select_ln185_reg_1035_pp0_iter6_reg <= select_ln185_reg_1035_pp0_iter5_reg;
        select_ln187_reg_1016 <= select_ln187_fu_497_p3;
        select_ln187_reg_1016_pp0_iter3_reg <= select_ln187_reg_1016;
        select_ln187_reg_1016_pp0_iter4_reg <= select_ln187_reg_1016_pp0_iter3_reg;
        select_ln39_reg_1080 <= select_ln39_fu_801_p3;
    end
end

always @ (*) begin
    if (((icmp_ln183_fu_265_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln183_reg_951 == 1'd1))) begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        b2_dw_out_ce0_local = 1'b1;
    end else begin
        b2_dw_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (icmp_ln187_reg_1031_pp0_iter7_reg == 1'd1) & (icmp_ln188_7_reg_1027_pp0_iter7_reg == 1'd1))) begin
        b2_dw_out_we0_local = 1'b1;
    end else begin
        b2_dw_out_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        s2_0_b2_dw_b_ce0_local = 1'b1;
    end else begin
        s2_0_b2_dw_b_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        s2_0_b2_dw_w_ce0_local = 1'b1;
    end else begin
        s2_0_b2_dw_w_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        sm3_ce0_local = 1'b1;
    end else begin
        sm3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_11_mid29_fu_718_p3 = ((empty_232_reg_1005_pp0_iter6_reg[0:0] == 1'b1) ? 64'd0 : acc_10_fu_114);

assign acc_fu_735_p2 = ($signed(sext_ln192_fu_732_p1) + $signed(acc_11_mid29_fu_718_p3));

assign add_ln18382_fu_389_p2 = (c_fu_146 + 6'd1);

assign add_ln183_fu_271_p2 = (indvar_flatten74_fu_150 + 19'd1);

assign add_ln184_7_fu_321_p2 = (indvar_flatten39_fu_142 + 13'd1);

assign add_ln184_fu_402_p2 = (select_ln183_fu_365_p3 + 5'd1);

assign add_ln185_7_fu_307_p2 = (indvar_flatten14_fu_134 + 9'd1);

assign add_ln185_fu_588_p2 = (ow_mid221_fu_581_p3 + 5'd1);

assign add_ln187_7_fu_539_p2 = (indvar_flatten_fu_126 + 4'd1);

assign add_ln187_fu_472_p2 = (kh_mid26_fu_452_p3 + 2'd1);

assign add_ln188_fu_521_p2 = (kw_mid2_fu_489_p3 + 2'd1);

assign add_ln192_fu_670_p2 = (zext_ln192_fu_667_p1 + grp_fu_852_p3);

assign add_ln193_7_fu_680_p2 = (empty_236_fu_638_p2 + zext_ln188_9_fu_664_p1);

assign add_ln193_fu_686_p2 = (add_ln193_7_fu_680_p2 + zext_ln188_fu_660_p1);

assign add_ln197_fu_842_p2 = (grp_fu_872_p3 + zext_ln185_fu_838_p1);

assign add_ln198_fu_755_p2 = ($signed(sext_ln198_fu_751_p1) + $signed(sext_ln184_fu_725_p1));

assign and_ln183_13_fu_295_p2 = (xor_ln183_fu_283_p2 & icmp_ln185_fu_289_p2);

assign and_ln183_14_fu_424_p2 = (xor_ln183_reg_963 & icmp_ln18796_fu_383_p2);

assign and_ln183_fu_378_p2 = (xor_ln183_reg_963 & icmp_ln188_fu_372_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign b2_dw_out_address0 = zext_ln197_fu_847_p1;

assign b2_dw_out_ce0 = b2_dw_out_ce0_local;

assign b2_dw_out_d0 = select_ln39_reg_1080;

assign b2_dw_out_we0 = b2_dw_out_we0_local;

assign empty_231_fu_442_p2 = (exitcond_flatten_mid238_fu_429_p2 | and_ln183_13_reg_974);

assign empty_232_fu_447_p2 = (icmp_ln184_reg_955 | empty_231_fu_442_p2);

assign empty_233_fu_478_p2 = (exitcond_flatten_mid238_fu_429_p2 | empty_reg_980);

assign empty_234_fu_483_p2 = (icmp_ln188_mid213_fu_466_p2 | empty_233_fu_478_p2);

assign empty_236_fu_638_p2 = (p_shl101_fu_634_p1 + zext_ln183_15_fu_624_p1);

assign empty_238_fu_832_p2 = (p_shl2_fu_814_p3 - p_shl100_fu_828_p1);

assign empty_241_fu_654_p2 = (p_shl_fu_647_p3 - zext_ln187_2_fu_644_p1);

assign empty_fu_301_p2 = (icmp_ln184_fu_277_p2 | and_ln183_13_fu_295_p2);

assign exitcond_flatten16_not_fu_408_p2 = (icmp_ln185_reg_969 ^ 1'd1);

assign exitcond_flatten_mid238_fu_429_p2 = (not_exitcond_flatten16_mid273_fu_413_p2 & and_ln183_14_fu_424_p2);

assign grp_fu_852_p0 = 18'd3364;

assign grp_fu_852_p1 = grp_fu_852_p10;

assign grp_fu_852_p10 = select_ln183_8_fu_395_p3;

assign grp_fu_852_p2 = grp_fu_852_p20;

assign grp_fu_852_p20 = tmp_2_fu_601_p3;

assign grp_fu_861_p0 = grp_fu_861_p00;

assign grp_fu_861_p00 = select_ln187_fu_497_p3;

assign grp_fu_861_p1 = {{select_ln184_fu_435_p3}, {1'd0}};

assign grp_fu_861_p2 = 12'd58;

assign grp_fu_861_p3 = grp_fu_861_p30;

assign grp_fu_861_p30 = kw_mid2_reg_1010_pp0_iter3_reg;

assign grp_fu_872_p0 = 15'd784;

assign grp_fu_872_p1 = grp_fu_872_p10;

assign grp_fu_872_p10 = select_ln183_8_reg_986_pp0_iter4_reg;

assign grp_fu_872_p2 = grp_fu_872_p20;

assign grp_fu_872_p20 = select_ln185_reg_1035_pp0_iter6_reg;

assign icmp_ln183_fu_265_p2 = ((indvar_flatten74_fu_150 == 19'd409248) ? 1'b1 : 1'b0);

assign icmp_ln184_fu_277_p2 = ((indvar_flatten39_fu_142 == 13'd7056) ? 1'b1 : 1'b0);

assign icmp_ln185_fu_289_p2 = ((indvar_flatten14_fu_134 == 9'd252) ? 1'b1 : 1'b0);

assign icmp_ln18796_fu_383_p2 = ((indvar_flatten_fu_126 == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln187_fu_533_p2 = ((select_ln187_fu_497_p3 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln188_7_fu_527_p2 = ((add_ln188_fu_521_p2 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln188_fu_372_p2 = ((kw_fu_118 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln188_mid213_fu_466_p2 = (not_exitcond_flatten_mid238_fu_460_p2 & icmp_ln188_mid234_fu_418_p2);

assign icmp_ln188_mid234_fu_418_p2 = (not_exitcond_flatten16_mid273_fu_413_p2 & and_ln183_fu_378_p2);

assign icmp_ln39_fu_771_p2 = (($signed(tmp_33_fu_761_p4) > $signed(43'd0)) ? 1'b1 : 1'b0);

assign icmp_ln40_fu_777_p2 = (($signed(add_ln198_fu_755_p2) < $signed(57'd144115188075839488)) ? 1'b1 : 1'b0);

assign kh_mid26_fu_452_p3 = ((empty_232_fu_447_p2[0:0] == 1'b1) ? 2'd0 : kh_fu_122);

assign kw_mid2_fu_489_p3 = ((empty_234_fu_483_p2[0:0] == 1'b1) ? 2'd0 : kw_fu_118);

assign not_exitcond_flatten16_mid273_fu_413_p2 = (icmp_ln184_reg_955 | exitcond_flatten16_not_fu_408_p2);

assign not_exitcond_flatten_mid238_fu_460_p2 = (exitcond_flatten_mid238_fu_429_p2 ^ 1'd1);

assign or_ln39_fu_795_p2 = (icmp_ln40_fu_777_p2 | icmp_ln39_fu_771_p2);

assign ow_mid221_fu_581_p3 = ((empty_reg_980_pp0_iter3_reg[0:0] == 1'b1) ? 5'd0 : ow_fu_130);

assign p_shl100_fu_828_p1 = tmp_32_fu_821_p3;

assign p_shl101_fu_634_p1 = tmp_1_4_fu_627_p3;

assign p_shl2_fu_814_p3 = {{select_ln184_reg_999_pp0_iter7_reg}, {5'd0}};

assign p_shl_fu_647_p3 = {{select_ln187_reg_1016_pp0_iter4_reg}, {2'd0}};

assign s2_0_b2_dw_b_address0 = zext_ln183_fu_697_p1;

assign s2_0_b2_dw_w_address0 = zext_ln193_fu_692_p1;

assign select_ln183_8_fu_395_p3 = ((icmp_ln184_reg_955[0:0] == 1'b1) ? add_ln18382_fu_389_p2 : c_fu_146);

assign select_ln183_fu_365_p3 = ((icmp_ln184_reg_955[0:0] == 1'b1) ? 5'd0 : oh_fu_138);

assign select_ln184_7_fu_327_p3 = ((icmp_ln184_fu_277_p2[0:0] == 1'b1) ? 13'd1 : add_ln184_7_fu_321_p2);

assign select_ln184_fu_435_p3 = ((and_ln183_13_reg_974[0:0] == 1'b1) ? add_ln184_fu_402_p2 : select_ln183_fu_365_p3);

assign select_ln185_7_fu_313_p3 = ((empty_fu_301_p2[0:0] == 1'b1) ? 9'd1 : add_ln185_7_fu_307_p2);

assign select_ln185_fu_594_p3 = ((exitcond_flatten_mid238_reg_994_pp0_iter3_reg[0:0] == 1'b1) ? add_ln185_fu_588_p2 : ow_mid221_fu_581_p3);

assign select_ln187_8_fu_545_p3 = ((empty_232_fu_447_p2[0:0] == 1'b1) ? 4'd1 : add_ln187_7_fu_539_p2);

assign select_ln187_fu_497_p3 = ((icmp_ln188_mid213_fu_466_p2[0:0] == 1'b1) ? add_ln187_fu_472_p2 : kh_mid26_fu_452_p3);

assign select_ln39_10_fu_787_p3 = ((icmp_ln39_fu_771_p2[0:0] == 1'b1) ? 15'd16383 : 15'd16384);

assign select_ln39_fu_801_p3 = ((or_ln39_fu_795_p2[0:0] == 1'b1) ? select_ln39_10_fu_787_p3 : trunc_ln41_fu_783_p1);

assign sext_ln184_fu_725_p1 = $signed(s2_0_b2_dw_b_q0);

assign sext_ln192_fu_732_p1 = $signed(mul_ln193_reg_1070);

assign sext_ln198_fu_751_p1 = $signed(trunc_ln_fu_741_p4);

assign sm3_address0 = zext_ln192_7_fu_675_p1;

assign sm3_ce0 = sm3_ce0_local;

assign tmp_1_4_fu_627_p3 = {{select_ln183_8_reg_986_pp0_iter4_reg}, {3'd0}};

assign tmp_2_fu_601_p3 = {{select_ln185_fu_594_p3}, {1'd0}};

assign tmp_32_fu_821_p3 = {{select_ln184_reg_999_pp0_iter7_reg}, {2'd0}};

assign tmp_33_fu_761_p4 = {{add_ln198_fu_755_p2[56:14]}};

assign trunc_ln41_fu_783_p1 = add_ln198_fu_755_p2[14:0];

assign trunc_ln_fu_741_p4 = {{acc_fu_735_p2[63:8]}};

assign xor_ln183_fu_283_p2 = (icmp_ln184_fu_277_p2 ^ 1'd1);

assign zext_ln183_15_fu_624_p1 = select_ln183_8_reg_986_pp0_iter4_reg;

assign zext_ln183_fu_697_p1 = select_ln183_8_reg_986_pp0_iter5_reg;

assign zext_ln185_fu_838_p1 = empty_238_fu_832_p2;

assign zext_ln187_2_fu_644_p1 = select_ln187_reg_1016_pp0_iter4_reg;

assign zext_ln188_9_fu_664_p1 = kw_mid2_reg_1010_pp0_iter4_reg;

assign zext_ln188_fu_660_p1 = empty_241_fu_654_p2;

assign zext_ln192_7_fu_675_p1 = add_ln192_fu_670_p2;

assign zext_ln192_fu_667_p1 = grp_fu_861_p4;

assign zext_ln193_fu_692_p1 = add_ln193_fu_686_p2;

assign zext_ln197_fu_847_p1 = add_ln197_fu_842_p2;

endmodule //Shuffle_Model_dw_conv3x3_17
